#!/usr/bin/env bash
# Claude Code SessionStart hook → handrail brief (stdout is injected into context).
# Generated by `handrail init` — engine path baked in; re-run init if the engine moves.
input="$(cat)"; sid="$(jq -r '.session_id // "default"' <<<"$input")"
exec "${HANDRAIL_BIN:-handrail}" brief --session "$sid"
