import { defineStrings } from '@/lib/i18n'

export const DOCUMENT_CHAT = defineStrings({
  en: {
    title: 'Document discussion · Codex', open: 'Open document conversation', commands: 'Document commands', search: 'Search document actions…', noMatch: 'No matching actions.',
    description: 'Shared with this project. Responses are drafts to review here.',
    discuss: 'Discuss document', grill: 'Grill sections', draft_tests: 'Draft tests', draft_questions: 'Draft questions',
    discussPrompt: 'Help me discuss this document. Identify what needs clarification and ask me a focused question.',
    grillPrompt: 'Challenge assumptions and ambiguities in the selected sections. Start with the most important questions.',
    draft_testsPrompt: 'Draft concrete acceptance tests for the selected sections, including important edge cases. Explain which requirement each test covers.',
    draft_questionsPrompt: 'Draft focused questions about gaps, ambiguities and missing decisions in the selected sections.',
    scope: 'Context for this message', whole: 'Whole document', sections: 'Selected sections', choose: 'Choose at least one section or explicitly select the whole document.',
    selected: '{n} sections', removed: 'Removed section', untitled: 'Untitled section', exact: 'Only checked sections are included; their children are separate choices.',
    action: 'Action', prompt: 'Your instruction or reply', send: 'Send', sending: 'Sending…', retry: 'Retry', member: 'Project member',
    empty: 'Start a discussion, challenge requirements, or draft tests and questions.', loading: 'Loading discussion…',
    queued: 'Queued · waiting for the agent service', running: 'Working…', failed: 'The agent run failed.',
    loadFailed: 'Could not load the discussion.', sendFailed: 'Could not confirm delivery. Retry checks the same request and context.',
    tooLong: 'Your message exceeds 8,000 UTF-8 bytes. Please shorten it.', turnLimit: 'This discussion has reached its turn limit. History remains available.',
    permission: 'You can read this discussion. Asking Codex requires human and write permissions.', close: 'Close discussion',
    pending: 'Resolve the pending request before changing its context or instruction.',
  },
  de: {
    title: 'Dokumentgespräch · Codex', open: 'Dokumentgespräch öffnen', commands: 'Dokumentaktionen', search: 'Dokumentaktionen suchen…', noMatch: 'Keine passende Aktion.',
    description: 'Im Projekt geteilt. Antworten sind hier prüfbare Entwürfe.',
    discuss: 'Dokument besprechen', grill: 'Abschnitte hinterfragen', draft_tests: 'Tests entwerfen', draft_questions: 'Fragen entwerfen',
    discussPrompt: 'Hilf mir, dieses Dokument zu besprechen. Zeige Klärungsbedarf und stelle mir eine gezielte Frage.',
    grillPrompt: 'Hinterfrage Annahmen und Unklarheiten in den ausgewählten Abschnitten. Beginne mit den wichtigsten Fragen.',
    draft_testsPrompt: 'Entwirf konkrete Akzeptanztests für die ausgewählten Abschnitte, einschließlich wichtiger Randfälle. Erkläre die geprüfte Anforderung.',
    draft_questionsPrompt: 'Entwirf gezielte Fragen zu Lücken, Unklarheiten und fehlenden Entscheidungen in den ausgewählten Abschnitten.',
    scope: 'Kontext für diese Nachricht', whole: 'Ganzes Dokument', sections: 'Ausgewählte Abschnitte', choose: 'Wähle mindestens einen Abschnitt oder ausdrücklich das ganze Dokument.',
    selected: '{n} Abschnitte', removed: 'Entfernter Abschnitt', untitled: 'Unbenannter Abschnitt', exact: 'Nur angekreuzte Abschnitte werden einbezogen; Unterabschnitte sind separate Optionen.',
    action: 'Aktion', prompt: 'Deine Anweisung oder Antwort', send: 'Senden', sending: 'Wird gesendet…', retry: 'Erneut versuchen', member: 'Projektmitglied',
    empty: 'Besprich das Dokument, hinterfrage Anforderungen oder entwirf Tests und Fragen.', loading: 'Gespräch wird geladen…',
    queued: 'In der Warteschlange · wartet auf den Agentendienst', running: 'In Arbeit…', failed: 'Der Agentenlauf ist fehlgeschlagen.',
    loadFailed: 'Das Gespräch konnte nicht geladen werden.', sendFailed: 'Zustellung nicht bestätigt. Erneut versuchen prüft dieselbe Anfrage mit demselben Kontext.',
    tooLong: 'Deine Nachricht überschreitet 8.000 UTF-8-Bytes. Bitte kürze sie.', turnLimit: 'Dieses Gespräch hat sein Nachrichtenlimit erreicht. Der Verlauf bleibt verfügbar.',
    permission: 'Du kannst dieses Gespräch lesen. Für Codex werden human- und write-Berechtigungen benötigt.', close: 'Gespräch schließen',
    pending: 'Kläre zuerst die ausstehende Anfrage, bevor du ihren Kontext oder die Anweisung änderst.',
  },
})
