//! Embed `web/dist/assets/` into the binary as a name → bytes manifest.
//!
//! This replaces four `include_str!`s named one by one in `src/api/mod.rs`. The
//! reason it had to change is code splitting: the editor route is far too large
//! to sit in the single `app.js` chunk (`web/scripts/check-size.mjs` says in as
//! many words that the answer to a bundle creeping toward its budget is to split
//! per route, not to raise the budget), and a dynamic `import()` emits a chunk
//! whose name nothing could know at the time this file is compiled.
//!
//! **The security property the four fixed names bought is kept.** It was never
//! the literal names that mattered — it was that there is no directory to
//! traverse and no path to sanitize. A compile-time manifest is still an exact
//! lookup table: a request either matches an entry generated here or it 404s.
//! `../` reaches nothing because nothing here consults a filesystem at runtime.
//!
//! Node stays out of `cargo build`. `web/dist/` is committed for exactly that
//! reason, and this reads the committed directory — it never runs a bundler.
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let dist = root.join("web/dist");
    let assets = dist.join("assets");

    // Rebuild when the bundle changes. `web/dist/` is committed, so this fires on
    // a checkout or a `npm run build`, which is precisely the "TWO builds" rule
    // in CLAUDE.md — this is the half that notices.
    println!("cargo:rerun-if-changed=web/dist");
    println!("cargo:rerun-if-changed=build.rs");

    let mut files = match std::fs::read_dir(&assets) {
        Ok(dir) => dir
            .filter_map(Result::ok)
            .map(|e| e.path())
            .filter(|p| p.is_file())
            .collect::<Vec<_>>(),
        Err(e) => panic!(
            "cannot read {}: {e}\n\
             web/dist/ is committed and must be present. Run `npm run build` in web/.",
            assets.display()
        ),
    };
    // Sorted so the generated file is byte-stable across machines; an unsorted
    // read_dir would churn the build cache for no reason.
    files.sort();

    assert!(
        !files.is_empty(),
        "no assets in {} — run `npm run build` in web/",
        assets.display()
    );

    let mut out = String::new();
    out.push_str(
        "/// Every embedded asset: (path below `/`, MIME type, bytes).\n\
         ///\n\
         /// Generated by build.rs from the committed `web/dist/assets/`.\n\
         pub static ASSETS: &[(&str, &str, &[u8])] = &[\n",
    );

    for path in &files {
        let name = path.file_name().unwrap().to_str().unwrap_or_else(|| {
            panic!("asset name is not UTF-8: {}", path.display());
        });
        // The route is `/assets/{file}`. A nested directory would need a
        // different route shape, so refuse rather than silently not serving it.
        let mime = mime_for(path);
        writeln!(
            out,
            "    (\"assets/{name}\", \"{mime}\", include_bytes!(r\"{}\")),",
            path.display()
        )
        .unwrap();
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("assets.rs");
    std::fs::write(&dest, out).expect("write assets.rs");
}

/// MIME by extension, with an explicit list rather than a crate.
///
/// Unknown extensions are a hard error, not `application/octet-stream`: an asset
/// the bundler started emitting that we serve with the wrong type fails in the
/// browser in a way that is tedious to trace, and the fix — add a line here — is
/// trivial once the build says so.
fn mime_for(path: &Path) -> &'static str {
    match path.extension().and_then(|e| e.to_str()) {
        Some("js") | Some("mjs") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("map") | Some("json") => "application/json; charset=utf-8",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("webp") => "image/webp",
        Some("woff2") => "font/woff2",
        Some("woff") => "font/woff",
        other => panic!(
            "unknown asset extension {other:?} for {}\n\
             Add it to mime_for() in build.rs.",
            path.display()
        ),
    }
}
