import { afterEach, describe, expect, it, vi } from 'vitest'
import { diagramEngine, mountDiagram } from './diagram'

const { render } = vi.hoisted(() => ({ render: vi.fn() }))
vi.mock('./api', () => ({ api: render }))
const tick = () => new Promise((resolve) => setTimeout(resolve, 300))
const access = { token: 'test-token', project: 'demo' }
const svg = (text = '') => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 204 263">${text}</svg>`
afterEach(() => { render.mockReset() })

describe('Kroki rendering', () => {
  it.each(['mermaid', 'plantuml', 'd2'] as const)('renders %s with project credentials and isolates SVG', async (engine) => {
    render.mockResolvedValue({ svg: svg('<script>alert(1)</script>') })
    const host = document.createElement('div')
    const cancel = mountDiagram(host, 'source', engine, access)
    await tick()
    expect(render).toHaveBeenCalledWith('test-token', '/diagrams/render', expect.objectContaining({
      method: 'POST', body: JSON.stringify({ project: 'demo', engine, source: 'source' }), signal: expect.any(AbortSignal),
    }))
    expect(host.querySelector('svg, script')).toBeNull()
    expect(host.querySelector('img')?.src).toMatch(/^data:image\/svg\+xml/)
    expect(host.querySelector('img')?.width).toBe(204)
    expect(host.querySelector('img')?.height).toBe(263)
    cancel()
  })
  it('ignores an older render and aborts its request after editing', async () => {
    let finish!: (result: { svg: string }) => void
    render.mockImplementationOnce(() => new Promise((resolve) => { finish = resolve }))
    const host = document.createElement('div')
    const cancel = mountDiagram(host, 'old', 'd2', access)
    await tick()
    cancel()
    expect(render.mock.calls[0]![2].signal.aborted).toBe(true)
    render.mockResolvedValueOnce({ svg: svg('new') })
    const stop = mountDiagram(host, 'new', 'd2', access)
    await tick()
    finish({ svg: svg('old') })
    await Promise.resolve()
    await Promise.resolve()
    expect(decodeURIComponent(host.querySelector('img')!.src)).toContain('new')
    stop()
  })
  it('preserves the last good image visibly outdated during errors and retries', async () => {
    render.mockResolvedValueOnce({ svg: svg() })
    const host = document.createElement('div')
    const first = mountDiagram(host, 'valid', 'plantuml', access)
    await tick()
    first()
    const previous = host.querySelector('img')
    render.mockRejectedValueOnce(new Error('Kroki is unavailable — configure the service.'))
    const stop = mountDiagram(host, 'bad', 'plantuml', access)
    expect(host.textContent).toContain('outdated')
    await tick()
    expect(host.querySelector('img')).toBe(previous)
    expect(host.textContent).toContain('configure the service')
    render.mockResolvedValueOnce({ svg: svg('fixed') })
    host.querySelector('button')!.click()
    await tick()
    expect(host.textContent).not.toContain('outdated')
    expect(decodeURIComponent(host.querySelector('img')!.src)).toContain('fixed')
    stop()
  })
  it('debounces, requires project access, and bounds UTF-8 source size', async () => {
    const host = document.createElement('div')
    mountDiagram(host, 'unused', 'd2', access)()
    await tick()
    expect(render).not.toHaveBeenCalled()
    mountDiagram(host, 'source')
    expect(host.textContent).toContain('Select a project')
    mountDiagram(host, 'é'.repeat(25_001), 'd2', access)
    expect(host.textContent).toContain('too large')
    expect(render).not.toHaveBeenCalled()
  })
  it('queues large documents with at most two renders and skips cancelled queued work', async () => {
    const finish: ((value: { svg: string }) => void)[] = []
    render.mockImplementation(() => new Promise(resolve => finish.push(resolve)))
    const stops = Array.from({ length: 7 }, (_, i) => mountDiagram(document.createElement('div'), `source-${i}`, 'd2', access))
    await tick()
    expect(render).toHaveBeenCalledTimes(2)
    stops[3]!()
    finish[0]!({ svg: svg() }); finish[1]!({ svg: svg() })
    await tick()
    expect(render).toHaveBeenCalledTimes(4)
    expect(render.mock.calls.map(call => JSON.parse(call[2].body).source)).toEqual(['source-0', 'source-1', 'source-2', 'source-4'])
    finish[2]!({ svg: svg() }); finish[3]!({ svg: svg() })
    await tick()
    expect(render).toHaveBeenCalledTimes(6)
    finish[4]!({ svg: svg() }); finish[5]!({ svg: svg() })
    await tick()
    stops.forEach(stop => stop())
  })
  it('maps Salt and puml fences to PlantUML without interpreting ordinary code', () => {
    expect(diagramEngine('SALT')).toBe('plantuml')
    expect(diagramEngine('puml')).toBe('plantuml')
    expect(diagramEngine('javascript')).toBeNull()
  })
})
