// DE/EN strings for /settings.
// EN is the reference shape — a DE table that drifts is a compile error.
import { defineStrings } from '@/lib/i18n'

export const STR = defineStrings({
  en: {
    settings: 'Settings',
    specification: 'Specification',
    board: 'Board',
    inbox: 'Inbox',
    documents: 'Documents',
    initiatives: 'Initiatives',
    mindmaps: 'Mindmaps',
    schedules: 'Schedules',
    verification: 'Verification',
    environments: 'Environments',

    gateTokenSub: "An admin token. Without 'admin' this page has nothing to show you.",
    gateLabel: 'API token',
    gateOpen: 'Open',
    gateEmpty: 'Paste a token to continue.',

    // Section rail
    navOverview: 'Overview',
    navOverviewHint: 'The token you are signed in with',
    navData: 'Data',
    navDataHint: 'Back up the whole store',
    navAccess: 'Access',
    navAccessHint: 'Tokens that can reach the API',
    navProjects: 'Projects',
    navProjectsHint: 'Create and remove projects',
    navLibrary: 'Workflows',
    navLibraryHint: 'Reusable state machines',
    navPeople: 'People',
    navPeopleHint: 'Who work can be addressed to',
    peopleTitle: 'People',
    peopleSub:
      'Who a decision can be addressed to. A person is not a login and grants no access — what a credential may do is its scopes. Adding someone is how a question stops going to "whoever has the expertise" and starts waiting on them.',
    peopleEmpty: 'Nobody yet. Add someone with: takomo user new <handle> --name "Full Name"',
    peoplePerson: 'Person',
    peopleProjects: 'Can be handed work in',
    peopleNoProjects: 'no project yet — add one to make them assignable',
    peopleStatus: 'Status',
    peopleActive: 'Active',
    peopleDisabled: 'Disabled',
    peopleDisable: 'Disable',
    peopleEnable: 'Enable',
    peopleDisableHint:
      'Stops new work being addressed to them. Not a delete and not a revocation: every past decision keeps their name on it, and their credentials keep working — revoke those to end access.',
    peopleAdd: 'Add person',
    peopleEdit: 'Edit',
    personAddTitle: 'Add a person',
    personAddSub:
      'Somebody a decision can be addressed to. This grants no access on its own — scopes are what a credential may do.',
    personEditTitle: 'Edit person',
    personEditSub: 'Their display name, email, and which projects can hand them work.',
    personHandle: 'Handle',
    personHandlePh: 'ada',
    personHandleHint:
      'Lowercase, e.g. ada or j.chen. Their stable identity, and usable as a person:<handle> tag. The real name goes below.',
    personHandleFixed:
      'Fixed: every person:<handle> reference and every assignment resolves through it. Change the name instead.',
    personName: 'Name',
    personNamePh: 'Ada Lovelace',
    personNameHint: 'What a reader sees on a question waiting on them.',
    personEmail: 'Email',
    personEmailPh: 'ada@example.com',
    personEmailHint: 'For a human reader — Takomo never sends mail. Clear it to remove it.',
    personProjects: 'Can be handed work in',
    personProjectsHint:
      'Membership says who may be handed work in a project. Separate from what their credentials may read or write.',
    personNoProjectsPicked:
      'No project picked — they will be in the directory but cannot be assigned anything.',
    personSave: 'Save',
    personAdd: 'Add',
    personNeedHandle: 'A handle is required — it is how this person is referenced everywhere.',
    personBadHandle:
      'A handle must be lowercase and match ^[a-z0-9][a-z0-9._-]*$, e.g. ada or j.chen. Put the real name in Name.',

    signOut: 'Sign out',
    navExpand: 'Expand navigation',
    navCollapse: 'Collapse navigation',
    navAccount: 'Account',
    notAdminTitle: 'This token is not an admin',
    notAdmin:
      "Everything on this page needs the 'admin' scope. Sign in with an admin token, or mint one on the server:",
    notAdminCmd: 'takomo token create --actor you --scopes read,write,human,admin',

    // Overview
    overviewTitle: 'This token',
    overviewSub: 'Who the API thinks you are, and what it will let you do.',
    factActor: 'Actor',
    factScopes: 'Scopes',
    factProjects: 'Projects',
    factTokenId: 'Token id',
    allProjects: 'All projects',

    // Data
    dataTitle: 'Database export',
    dataSub:
      'Downloads the entire store as one SQLite file — every project, plus tokens, OAuth clients, shares, answer grants and the event log.',
    dataHow:
      'Taken with VACUUM INTO, so it is a consistent snapshot including writes still in the WAL. Open it directly with sqlite3.',
    dataWarnTitle: 'Treat the file as a credential',
    dataWarn:
      'It contains token hashes and OAuth client secrets. Anyone holding it holds the contents of this Takomo.',
    dataScopedTitle: 'Not available to this token',
    dataScoped:
      'A whole-database export cannot be narrowed to a project allowlist, so a token limited to specific projects is refused. Use an unrestricted admin token, or export a single project from the board.',
    dataBtn: 'Download database',
    dataBusy: 'Preparing…',
    dataDone: 'Downloaded {name} ({size})',

    // Access
    accessTitle: 'Tokens',
    accessSub: 'Every credential that can reach this API. Revoking one takes effect immediately.',
    accessEmpty: 'No tokens yet.',
    accessNew: 'New token',
    tokThisToken: 'this token',
    tokScopes: 'Scopes',
    tokProjects: 'Projects',
    tokLastUsed: 'last used',
    tokNeverUsed: 'never used',
    tokRevoked: 'revoked',
    tokExpired: 'expired',
    tokRevoke: 'Revoke',

    newTokTitle: 'New token',
    newTokSub: 'The plaintext is shown once, at creation, and never again.',
    newTokActor: 'Actor',
    newTokActorPh: 'agent:ci',
    newTokActorHint: 'Who this credential belongs to — a person, a machine, a job.',
    newTokScopes: 'Scopes',
    newTokRead: 'Read tickets, questions and events.',
    newTokWrite: 'Create and change tickets; claim work.',
    newTokHuman: 'Answer questions and approve schedules.',
    newTokAdmin: 'Manage tokens and projects, and export the database.',
    newTokProjects: 'Limit to projects',
    newTokProjectsHint: 'This token will only see the projects selected above.',
    newTokAll: 'Nothing selected — the token reaches every project.',
    newTokCreate: 'Create token',
    newTokCancel: 'Cancel',
    newTokNeedActor: 'An actor is required.',
    newTokNeedScope: 'Pick at least one scope.',

    revealTitle: 'Copy this token now',
    revealSub:
      'It is shown once and cannot be recovered — Takomo stores only a hash. If you lose it, revoke it and mint another.',
    revealCopy: 'Copy',
    revealCopied: 'Copied',
    revealDone: 'Done',

    confirmRevokeTitle: 'Revoke this token?',
    confirmRevokeBody: 'Anything using {actor} stops working immediately. This cannot be undone.',
    confirmRevokeYes: 'Revoke token',

    // Projects
    projTitle: 'Projects',
    projSub: 'Each project has its own workflow, tickets and schedules.',
    projEmpty: 'No projects yet.',
    projNew: 'New project',
    projDelete: 'Delete',
    newProjTitle: 'New project',
    newProjSub: 'The id prefixes every ticket in this project and cannot be changed later.',
    newProjId: 'Id',
    newProjIdPh: 'demo',
    newProjIdHint: 'Lowercase letters, digits and dashes.',
    newProjIdInvalid: 'Use lowercase letters, digits and dashes, starting with a letter or digit.',
    newProjName: 'Name',
    newProjNamePh: 'Demo',
    newProjNameHint: 'Shown in the project picker. Defaults to the id.',
    newProjCreate: 'Create project',
    newProjCancel: 'Cancel',
    // Project detail — moved here from the board's dialog.
    projOpen: 'Configure',
    projBack: 'All projects',
    projLoadErr: 'Could not load projects.',
    projWorkflowLabel: 'Workflow',
    projLangLabel: 'Question language',
    projLangHelp:
      'The human-facing language agents should phrase ask-a-human questions in (e.g. “German”). Leave empty for no preference.',
    projLangPh: 'e.g. German',
    projStyleLabel: 'Style guide',
    projStyleHelp:
      'The house style for text agents write — ticket titles and bodies, comments, and questions. Agents get it on every work-loop call, before they write.',
    projStylePh:
      'e.g. Two sentences max. Plain language, no marketing voice. Prefer a yes/no or a short choice over an open question.',
    projChars: '{n}/{max} characters',
    projTtlLabel: 'Answer-link lifetime (seconds)',
    projTtlHelp:
      'How long a link handed to someone outside the org to answer exactly one question stays valid. An individual link can override this when it is minted. Unlike the two fields above, this one is enforced.',
    projClaimTtlLabel: 'Default claim lifetime (seconds)',
    projClaimTtlHelp:
      'How long an agent holds a ticket when it asks for no lifetime of its own. When it lapses the sweeper returns the ticket to the queue, even if work is still going — agents extend it with takomo_heartbeat.',
    projMaxClaimTtlLabel: 'Maximum claim lifetime (seconds)',
    projMaxClaimTtlHelp:
      'The ceiling an agent may ask for when claiming. It is also how long a crashed agent blocks a ticket, since only expired claims are released — higher means fewer heartbeats but slower recovery.',
    projSave: 'Save',
    projSaving: 'Saving…',
    projSaved: 'Saved.',
    projOver: 'The style guide is over the limit.',
    projReadOnly:
      "Read-only — this token has no 'admin' scope. Changing these settings needs an admin token.",
    // Workflow editor
    wfTitle: 'Workflow',
    wfSubtitle:
      'The state machine every ticket in this project moves through. Drag a box to move it, drag from its right edge to draw a transition, and click anything to edit it.',
    wfAddState: 'State',
    wfStartFrom: 'Start from…',
    wfApply: 'Apply workflow',
    wfApplying: 'Applying…',
    wfApplied: 'Applied.',
    wfRevert: 'Discard changes',
    wfSaveAs: 'Save to library…',
    wfProblems: 'This workflow cannot be applied yet',
    wfValid: 'Ready to apply',
    wfChecking: 'Checking…',
    wfBlockedTitle: 'Tickets would be stranded',
    wfBlockedBody:
      'These states hold tickets but are missing from your draft. Takomo refuses a workflow that leaves a ticket in a state it no longer defines — move them first, then apply.',
    wfBlockedRow: '{n} ticket(s)',
    wfOpenBoard: 'open the board',
    wfCanvasInitial: 'start',
    wfCanvasClaimable: 'claimable',
    wfCanvasTerminal: 'terminal',
    wfCanvasHint: 'Workflow diagram. States are boxes; arrows are transitions.',
    wfReadOnly: "Read-only — changing a workflow needs the 'admin' scope.",
    wfNewStateId: 'New state',
    wfNothing: 'Select a state or a transition to edit it.',
    wfStateTitle: 'State',
    wfTransitionTitle: 'Transition',
    wfId: 'Id',
    wfIdHint: 'Renaming updates every transition that references it.',
    wfCategory: 'Category',
    wfClaimable: 'Claimable',
    wfClaimableHint: 'Tickets here enter the ready queue and can be claimed by an agent.',
    wfTerminal: 'Terminal',
    wfTerminalHint: 'Ends the lifecycle. A done blocker no longer blocks anything.',
    wfMakeInitial: 'Make the start state',
    wfIsInitial: 'This is the start state',
    wfDeleteState: 'Delete state',
    wfDeleteTransition: 'Delete transition',
    wfRequires: 'Requires',
    wfReqClaim: 'The caller must hold the ticket’s lease.',
    wfReqHuman: "The caller's token must carry the 'human' scope — the approval gate.",
    wfReqNoChildren: 'Every child ticket must be finished.',
    wfReqNoBlockers: 'Every ticket this one is blocked by must be finished.',
    wfReqHasLink:
      'The ticket must carry a link under a named key — evidence a later reader can check.',
    wfReqHasLinkHint: "Usually 'commit': a full SHA stays verifiable long after the ticket is forgotten.",
    wfLinkKey: 'Link key',
    wfFrom: 'from',
    wfTo: 'to',
    wfSaveAsPrompt: 'Name for the saved workflow',
    wfSavedToLibrary: 'Saved to the library.',
    confirmDeleteProjTitle: 'Delete this project?',
    confirmDeleteProjBody:
      'Deleting {id} removes its tickets, questions, schedules and checklist data. This cannot be undone. To stop work on it without losing anything, archive it instead.',
    confirmDeleteProjYes: 'Delete project',

    // Archive — the reversible alternative to delete.
    projArchived: 'Archived',
    projArchivedBanner:
      'This project is archived. Nothing can be changed under it — tickets, claims, transitions, comments, questions, tags, schedules — and its tickets are out of the ready queue, so no agent is offered work here. Everything is still readable, and nothing was deleted.',
    projArchive: 'Archive project',
    projUnarchive: 'Put back to work',
    confirmArchiveTitle: 'Archive this project?',
    confirmArchiveBody:
      'Work on {id} stops: every write is refused and its tickets leave the ready queue. Nothing is deleted and every page still reads, so you can undo this at any time.',
    confirmArchiveYes: 'Archive project',
    confirmArchiveForceTitle: 'Someone is working on this project',
    confirmArchiveForceBody:
      'A worker holds a live lease on {id}. Archiving now ends that lease — the agent finds out on its next call and stops, and any work it has not written down is lost. Wait for the lease to expire, or archive anyway.',
    confirmArchiveForceYes: 'End the lease and archive',
    projArchivedToast: '{id} is archived. Nothing under it can change until you put it back.',
    projUnarchivedToast: '{id} is back to work.',

    // Workflow library
    libTitle: 'Workflow library',
    libSub:
      'Named state machines that can be applied to any project. Applying copies the document onto the project, so deleting an entry here never changes a project already using it.',
    libEmpty: 'No saved workflows yet. Open a project, shape its workflow, and use “Save to library…”.',
    libBuiltin: 'ships with takomo',
    libStates: '{n} states',
    libTransitions: '{n} transitions',
    libRename: 'Rename',
    libDelete: 'Delete',
    libRenamePrompt: 'New name',
    libBuiltinLocked:
      'This workflow ships with the server and is reseeded on every start, so a change here would be undone at the next restart. Start a project from it and save the result under a new name.',
    confirmDeleteWfTitle: 'Delete this workflow?',
    confirmDeleteWfBody:
      'Removes “{name}” from the library. Projects already using it keep their workflow — applying copies the document, so nothing breaks.',
    confirmDeleteWfYes: 'Delete workflow',

    cancel: 'Cancel',
    requestFailed: 'Request failed.',
  },
  de: {
    settings: 'Einstellungen',
    specification: 'Spezifikation',
    board: 'Board',
    inbox: 'Posteingang',
    documents: 'Dokumente',
    initiatives: 'Initiativen',
    mindmaps: 'Mindmaps',
    schedules: 'Zeitpläne',
    verification: 'Verifizierung',
    environments: 'Umgebungen',

    gateTokenSub: "Ein Admin-Token. Ohne 'admin' hat diese Seite nichts zu zeigen.",
    gateLabel: 'API-Token',
    gateOpen: 'Öffnen',
    gateEmpty: 'Zum Fortfahren ein Token einfügen.',

    navOverview: 'Übersicht',
    navOverviewHint: 'Das Token, mit dem du angemeldet bist',
    navData: 'Daten',
    navDataHint: 'Den gesamten Speicher sichern',
    navAccess: 'Zugriff',
    navAccessHint: 'Tokens, die die API erreichen',
    navProjects: 'Projekte',
    navProjectsHint: 'Projekte anlegen und entfernen',
    navLibrary: 'Workflows',
    navLibraryHint: 'Wiederverwendbare Zustandsautomaten',
    navPeople: 'Personen',
    navPeopleHint: 'An wen Arbeit gerichtet werden kann',
    peopleTitle: 'Personen',
    peopleSub:
      'An wen eine Entscheidung gerichtet werden kann. Eine Person ist kein Login und gew\u00e4hrt keinen Zugriff — was eine Zugangsberechtigung darf, sind ihre Scopes. Mit einer Person h\u00f6rt eine Frage auf, an \u201eirgendwen mit der Expertise\u201c zu gehen, und wartet auf sie.',
    peopleEmpty:
      'Noch niemand. Person anlegen mit: takomo user new <handle> --name "Vollst\u00e4ndiger Name"',
    peoplePerson: 'Person',
    peopleProjects: 'Kann Arbeit erhalten in',
    peopleNoProjects: 'noch kein Projekt — ohne Mitgliedschaft nicht adressierbar',
    peopleStatus: 'Status',
    peopleActive: 'Aktiv',
    peopleDisabled: 'Deaktiviert',
    peopleDisable: 'Deaktivieren',
    peopleEnable: 'Aktivieren',
    peopleDisableHint:
      'Verhindert, dass neue Arbeit an sie gerichtet wird. Kein L\u00f6schen und kein Widerruf: jede fr\u00fchere Entscheidung beh\u00e4lt ihren Namen, und ihre Zugangsberechtigungen funktionieren weiter — diese widerrufen, um den Zugriff zu beenden.',
    peopleAdd: 'Person hinzuf\u00fcgen',
    peopleEdit: 'Bearbeiten',
    personAddTitle: 'Person hinzuf\u00fcgen',
    personAddSub:
      'Jemand, an den eine Entscheidung gerichtet werden kann. Das gew\u00e4hrt allein keinen Zugriff \u2014 was eine Zugangsberechtigung darf, sind ihre Scopes.',
    personEditTitle: 'Person bearbeiten',
    personEditSub: 'Anzeigename, E-Mail und in welchen Projekten sie Arbeit erhalten kann.',
    personHandle: 'Handle',
    personHandlePh: 'ada',
    personHandleHint:
      'Kleinbuchstaben, z.\u00a0B. ada oder j.chen. Die feste Identit\u00e4t, auch als person:<handle>-Tag nutzbar. Der echte Name steht unten.',
    personHandleFixed:
      'Unver\u00e4nderlich: jede person:<handle>-Referenz und jede Zuweisung l\u00f6st dar\u00fcber auf. Stattdessen den Namen \u00e4ndern.',
    personName: 'Name',
    personNamePh: 'Ada Lovelace',
    personNameHint: 'Was bei einer Frage steht, die auf sie wartet.',
    personEmail: 'E-Mail',
    personEmailPh: 'ada@example.com',
    personEmailHint:
      'Nur zur Information \u2014 Takomo versendet keine E-Mails. Leeren entfernt sie.',
    personProjects: 'Kann Arbeit erhalten in',
    personProjectsHint:
      'Die Mitgliedschaft sagt, wer in einem Projekt Arbeit erhalten kann. Unabh\u00e4ngig davon, was ihre Zugangsberechtigungen lesen oder schreiben d\u00fcrfen.',
    personNoProjectsPicked:
      'Kein Projekt gew\u00e4hlt \u2014 die Person steht dann im Verzeichnis, kann aber nichts zugewiesen bekommen.',
    personSave: 'Speichern',
    personAdd: 'Hinzuf\u00fcgen',
    personNeedHandle:
      'Ein Handle ist erforderlich \u2014 dar\u00fcber wird die Person \u00fcberall referenziert.',
    personBadHandle:
      'Ein Handle muss klein geschrieben sein und ^[a-z0-9][a-z0-9._-]*$ entsprechen, z.\u00a0B. ada oder j.chen. Der echte Name geh\u00f6rt in Name.',

    signOut: 'Abmelden',
    navExpand: 'Navigation ausklappen',
    navCollapse: 'Navigation einklappen',
    navAccount: 'Konto',
    notAdminTitle: 'Dieses Token ist kein Admin',
    notAdmin:
      "Alles auf dieser Seite benötigt den 'admin'-Scope. Melde dich mit einem Admin-Token an oder erzeuge eines auf dem Server:",
    notAdminCmd: 'takomo token create --actor du --scopes read,write,human,admin',

    overviewTitle: 'Dieses Token',
    overviewSub: 'Wofür die API dich hält und was sie dich tun lässt.',
    factActor: 'Akteur',
    factScopes: 'Scopes',
    factProjects: 'Projekte',
    factTokenId: 'Token-Id',
    allProjects: 'Alle Projekte',

    dataTitle: 'Datenbank-Export',
    dataSub:
      'Lädt den gesamten Speicher als eine SQLite-Datei herunter — alle Projekte, dazu Tokens, OAuth-Clients, Freigaben, Antwort-Grants und das Ereignisprotokoll.',
    dataHow:
      'Per VACUUM INTO erstellt, also ein konsistenter Snapshot inklusive Schreibvorgängen, die noch im WAL liegen. Direkt mit sqlite3 zu öffnen.',
    dataWarnTitle: 'Behandle die Datei wie ein Geheimnis',
    dataWarn:
      'Sie enthält Token-Hashes und OAuth-Client-Secrets. Wer sie hat, hat den Inhalt dieses Takomo.',
    dataScopedTitle: 'Für dieses Token nicht verfügbar',
    dataScoped:
      'Ein Gesamt-Export lässt sich nicht auf eine Projekt-Freigabeliste einschränken, daher wird ein auf bestimmte Projekte begrenztes Token abgelehnt. Nutze ein uneingeschränktes Admin-Token oder exportiere ein einzelnes Projekt vom Board aus.',
    dataBtn: 'Datenbank herunterladen',
    dataBusy: 'Wird vorbereitet…',
    dataDone: '{name} heruntergeladen ({size})',

    accessTitle: 'Tokens',
    accessSub:
      'Alle Zugangsdaten, die diese API erreichen können. Ein Widerruf wirkt sofort.',
    accessEmpty: 'Noch keine Tokens.',
    accessNew: 'Neues Token',
    tokThisToken: 'dieses Token',
    tokScopes: 'Scopes',
    tokProjects: 'Projekte',
    tokLastUsed: 'zuletzt benutzt',
    tokNeverUsed: 'nie benutzt',
    tokRevoked: 'widerrufen',
    tokExpired: 'abgelaufen',
    tokRevoke: 'Widerrufen',

    newTokTitle: 'Neues Token',
    newTokSub: 'Der Klartext wird einmal bei der Erstellung angezeigt und nie wieder.',
    newTokActor: 'Akteur',
    newTokActorPh: 'agent:ci',
    newTokActorHint: 'Wem dieses Token gehört — einer Person, einer Maschine, einem Job.',
    newTokScopes: 'Scopes',
    newTokRead: 'Tickets, Fragen und Ereignisse lesen.',
    newTokWrite: 'Tickets anlegen und ändern; Arbeit übernehmen.',
    newTokHuman: 'Fragen beantworten und Zeitpläne freigeben.',
    newTokAdmin: 'Tokens und Projekte verwalten und die Datenbank exportieren.',
    newTokProjects: 'Auf Projekte begrenzen',
    newTokProjectsHint: 'Dieses Token sieht nur die oben ausgewählten Projekte.',
    newTokAll: 'Nichts ausgewählt — das Token erreicht alle Projekte.',
    newTokCreate: 'Token erstellen',
    newTokCancel: 'Abbrechen',
    newTokNeedActor: 'Ein Akteur ist erforderlich.',
    newTokNeedScope: 'Mindestens einen Scope auswählen.',

    revealTitle: 'Kopiere dieses Token jetzt',
    revealSub:
      'Es wird einmal angezeigt und ist nicht wiederherstellbar — Takomo speichert nur einen Hash. Wenn du es verlierst, widerrufe es und erzeuge ein neues.',
    revealCopy: 'Kopieren',
    revealCopied: 'Kopiert',
    revealDone: 'Fertig',

    confirmRevokeTitle: 'Dieses Token widerrufen?',
    confirmRevokeBody:
      'Alles, was {actor} nutzt, funktioniert sofort nicht mehr. Das lässt sich nicht rückgängig machen.',
    confirmRevokeYes: 'Token widerrufen',

    projTitle: 'Projekte',
    projSub: 'Jedes Projekt hat einen eigenen Workflow, eigene Tickets und Zeitpläne.',
    projEmpty: 'Noch keine Projekte.',
    projNew: 'Neues Projekt',
    projDelete: 'Löschen',
    newProjTitle: 'Neues Projekt',
    newProjSub:
      'Die Id steht vor jedem Ticket dieses Projekts und kann später nicht geändert werden.',
    newProjId: 'Id',
    newProjIdPh: 'demo',
    newProjIdHint: 'Kleinbuchstaben, Ziffern und Bindestriche.',
    newProjIdInvalid:
      'Kleinbuchstaben, Ziffern und Bindestriche verwenden, beginnend mit Buchstabe oder Ziffer.',
    newProjName: 'Name',
    newProjNamePh: 'Demo',
    newProjNameHint: 'Wird in der Projektauswahl angezeigt. Standard ist die Id.',
    newProjCreate: 'Projekt erstellen',
    newProjCancel: 'Abbrechen',
    projOpen: 'Konfigurieren',
    projBack: 'Alle Projekte',
    projLoadErr: 'Projekte konnten nicht geladen werden.',
    projWorkflowLabel: 'Workflow',
    projLangLabel: 'Sprache der Fragen',
    projLangHelp:
      'Die menschlich sichtbare Sprache, in der Agenten Fragen an Menschen stellen sollen (z. B. „German“). Leer lassen für keine Vorgabe.',
    projLangPh: 'z. B. German',
    projStyleLabel: 'Stil-Leitfaden',
    projStyleHelp:
      'Der Hausstil für Texte, die Agenten schreiben — Ticket-Titel und -Beschreibungen, Kommentare und Fragen. Agenten erhalten ihn bei jedem Arbeitsschritt, bevor sie schreiben.',
    projStylePh:
      'z. B. Maximal zwei Sätze. Klare Sprache, kein Marketing-Ton. Lieber eine Ja/Nein-Frage als eine offene.',
    projChars: '{n}/{max} Zeichen',
    projTtlLabel: 'Gültigkeit des Antwort-Links (Sekunden)',
    projTtlHelp:
      'Wie lange ein Antwort-Link gültig bleibt, den jemand außerhalb der Organisation für genau eine Frage erhält. Ein einzelner Link kann beim Erstellen davon abweichen. Anders als die beiden Felder oben wird dies erzwungen.',
    projClaimTtlLabel: 'Standard-Laufzeit eines Claims (Sekunden)',
    projClaimTtlHelp:
      'Wie lange ein Agent ein Ticket standardmäßig hält, wenn er beim Claim keine eigene Laufzeit angibt. Läuft sie ab, gibt der Sweeper das Ticket zurück in die Warteschlange — auch wenn noch daran gearbeitet wird. Agenten verlängern mit takomo_heartbeat.',
    projMaxClaimTtlLabel: 'Maximale Laufzeit eines Claims (Sekunden)',
    projMaxClaimTtlHelp:
      'Die Obergrenze, die ein Agent beim Claim anfordern darf. Das ist zugleich die Zeit, die ein abgestürzter Agent ein Ticket blockiert, denn nur abgelaufene Claims werden freigegeben — höher heißt weniger Heartbeats, aber langsamere Erholung.',
    projSave: 'Speichern',
    projSaving: 'Speichern…',
    projSaved: 'Gespeichert.',
    projOver: 'Der Stil-Leitfaden ist zu lang.',
    projReadOnly:
      "Nur lesbar — dieses Token hat keine 'admin'-Berechtigung. Ändern erfordert ein Admin-Token.",
    wfTitle: 'Workflow',
    wfSubtitle:
      'Der Zustandsautomat, den jedes Ticket dieses Projekts durchläuft. Ziehe ein Feld, um es zu bewegen, ziehe von seinem rechten Rand, um einen Übergang zu zeichnen, und klicke auf etwas, um es zu bearbeiten.',
    wfAddState: 'Zustand',
    wfStartFrom: 'Beginnen mit…',
    wfApply: 'Workflow anwenden',
    wfApplying: 'Wird angewendet…',
    wfApplied: 'Angewendet.',
    wfRevert: 'Änderungen verwerfen',
    wfSaveAs: 'In Bibliothek speichern…',
    wfProblems: 'Dieser Workflow kann noch nicht angewendet werden',
    wfValid: 'Bereit zum Anwenden',
    wfChecking: 'Wird geprüft…',
    wfBlockedTitle: 'Tickets würden stranden',
    wfBlockedBody:
      'Diese Zustände enthalten Tickets, fehlen aber in deinem Entwurf. Takomo lehnt einen Workflow ab, der ein Ticket in einem Zustand zurücklässt, den er nicht mehr kennt — verschiebe sie zuerst.',
    wfBlockedRow: '{n} Ticket(s)',
    wfOpenBoard: 'Board öffnen',
    wfCanvasInitial: 'Start',
    wfCanvasClaimable: 'übernehmbar',
    wfCanvasTerminal: 'endgültig',
    wfCanvasHint: 'Workflow-Diagramm. Zustände sind Felder, Pfeile sind Übergänge.',
    wfReadOnly: "Nur lesbar — einen Workflow zu ändern erfordert den 'admin'-Scope.",
    wfNewStateId: 'Neuer Zustand',
    wfNothing: 'Wähle einen Zustand oder Übergang aus, um ihn zu bearbeiten.',
    wfStateTitle: 'Zustand',
    wfTransitionTitle: 'Übergang',
    wfId: 'Id',
    wfIdHint: 'Beim Umbenennen werden alle Übergänge mitgeführt, die ihn referenzieren.',
    wfCategory: 'Kategorie',
    wfClaimable: 'Übernehmbar',
    wfClaimableHint:
      'Tickets hier kommen in die Warteschlange und können von einem Agenten übernommen werden.',
    wfTerminal: 'Endgültig',
    wfTerminalHint: 'Beendet den Lebenszyklus. Ein erledigter Blocker blockiert nichts mehr.',
    wfMakeInitial: 'Als Startzustand setzen',
    wfIsInitial: 'Das ist der Startzustand',
    wfDeleteState: 'Zustand löschen',
    wfDeleteTransition: 'Übergang löschen',
    wfRequires: 'Erfordert',
    wfReqClaim: 'Der Aufrufer muss das Lease des Tickets halten.',
    wfReqHuman: "Das Token des Aufrufers braucht den 'human'-Scope — das Freigabe-Gate.",
    wfReqNoChildren: 'Alle Unter-Tickets müssen abgeschlossen sein.',
    wfReqNoBlockers: 'Alle blockierenden Tickets müssen abgeschlossen sein.',
    wfReqHasLink:
      'Das Ticket muss einen Link unter einem benannten Schlüssel tragen — ein Nachweis, den ein späterer Leser prüfen kann.',
    wfReqHasLinkHint:
      "Meist 'commit': ein vollständiger SHA bleibt prüfbar, lange nachdem das Ticket vergessen ist.",
    wfLinkKey: 'Link-Schlüssel',
    wfFrom: 'von',
    wfTo: 'nach',
    wfSaveAsPrompt: 'Name für den gespeicherten Workflow',
    wfSavedToLibrary: 'In der Bibliothek gespeichert.',
    confirmDeleteProjTitle: 'Dieses Projekt löschen?',
    confirmDeleteProjBody:
      'Mit {id} werden dessen Tickets, Fragen, Zeitpläne und Checklisten-Daten entfernt. Das lässt sich nicht rückgängig machen. Wer die Arbeit nur beenden will, ohne etwas zu verlieren, archiviert es stattdessen.',
    confirmDeleteProjYes: 'Projekt löschen',

    projArchived: 'Archiviert',
    projArchivedBanner:
      'Dieses Projekt ist archiviert. Darunter lässt sich nichts mehr ändern — Tickets, Claims, Übergänge, Kommentare, Fragen, Tags, Zeitpläne — und seine Tickets sind aus der Ready-Queue, es wird also keinem Agenten mehr Arbeit daraus angeboten. Lesbar bleibt alles, gelöscht wurde nichts.',
    projArchive: 'Projekt archivieren',
    projUnarchive: 'Wieder in Betrieb nehmen',
    confirmArchiveTitle: 'Dieses Projekt archivieren?',
    confirmArchiveBody:
      'Die Arbeit an {id} endet: Jeder Schreibzugriff wird abgelehnt und seine Tickets verlassen die Ready-Queue. Gelöscht wird nichts und jede Seite bleibt lesbar — rückgängig machen lässt es sich jederzeit.',
    confirmArchiveYes: 'Projekt archivieren',
    confirmArchiveForceTitle: 'Jemand arbeitet gerade an diesem Projekt',
    confirmArchiveForceBody:
      'Auf {id} liegt ein aktiver Claim. Ein Archivieren beendet diese Lease jetzt — der Agent erfährt es beim nächsten Aufruf und hört auf; was er nicht festgehalten hat, ist verloren. Warte auf den Ablauf der Lease, oder archiviere trotzdem.',
    confirmArchiveForceYes: 'Lease beenden und archivieren',
    projArchivedToast: '{id} ist archiviert. Darunter ändert sich nichts, bis du es zurückholst.',
    projUnarchivedToast: '{id} ist wieder in Betrieb.',

    libTitle: 'Workflow-Bibliothek',
    libSub:
      'Benannte Zustandsautomaten, die auf jedes Projekt angewendet werden können. Beim Anwenden wird das Dokument in das Projekt kopiert — ein Löschen hier ändert also nie ein Projekt, das ihn bereits nutzt.',
    libEmpty:
      'Noch keine gespeicherten Workflows. Öffne ein Projekt, gestalte seinen Workflow und nutze „In Bibliothek speichern…“.',
    libBuiltin: 'wird mitgeliefert',
    libStates: '{n} Zustände',
    libTransitions: '{n} Übergänge',
    libRename: 'Umbenennen',
    libDelete: 'Löschen',
    libRenamePrompt: 'Neuer Name',
    libBuiltinLocked:
      'Dieser Workflow wird mit dem Server ausgeliefert und bei jedem Start neu gesetzt — eine Änderung hier wäre beim nächsten Neustart weg. Starte ein Projekt damit und speichere das Ergebnis unter einem neuen Namen.',
    confirmDeleteWfTitle: 'Diesen Workflow löschen?',
    confirmDeleteWfBody:
      'Entfernt „{name}“ aus der Bibliothek. Projekte, die ihn nutzen, behalten ihren Workflow — beim Anwenden wird das Dokument kopiert, es geht nichts kaputt.',
    confirmDeleteWfYes: 'Workflow löschen',

    cancel: 'Abbrechen',
    requestFailed: 'Anfrage fehlgeschlagen.',
  },
})
