// DE/EN strings for /schedules, ported verbatim from src/schedules.html.
// EN is the reference shape — a DE table that drifts is a compile error.
import { defineStrings } from '@/lib/i18n'

export const STR = defineStrings({
  en: {
    schedules: 'Schedules',
    board: 'Board',
    inbox: 'Inbox',
    initiatives: 'Initiatives',
    settings: 'Settings',
    gateTokenSub: "A token with 'read'. Activating, pausing or creating additionally needs 'human'.",
    gateLabel: 'API token',
    gateOpen: 'Open',
    allProjects: 'All projects',
    newSchedule: 'New schedule',
    newSub:
      'A schedule creates an ordinary ticket on a cadence. The ticket links back to it — and to nothing else.',
    groupPending: 'Waiting for you',
    groupActive: 'Active',
    groupStopped: 'Stopped',
    emptyAll:
      'No schedules yet. A schedule creates a ticket on a cadence — a weekly review, a key rotation, a nightly backup check.',
    bannerPending: 'An agent proposed a schedule. Nothing fires until you activate it.',
    statusPending: 'waiting',
    statusActive: 'active',
    statusPaused: 'paused',
    statusRejected: 'rejected',
    statusRetired: 'retired',
    actActivate: 'Activate',
    actReject: 'Reject',
    actPause: 'Pause',
    actResume: 'Resume',
    actRun: 'Run now',
    actDelete: 'Delete',
    outDone: 'done',
    outOpen: 'open',
    outNf: 'not fulfilled',
    nextAt: 'next',
    noneScheduled: 'paused — nothing scheduled',
    proposedBy: 'proposed by',
    lastN: 'last',
    nowArrow: 'now →',
    neverFired: 'has never fired',
    unitDay: 'daily',
    unitWeek: 'weekly',
    unitMonth: 'monthly',
    everyN: 'every',
    onDay: 'on day',
    pluralDays: 'days',
    pluralWeeks: 'weeks',
    pluralMonths: 'months',
    cadenceLabel: 'Cadence',
    fName: 'Name',
    fNamePh: 'Weekly review',
    fEvery: 'Unit',
    fInterval: 'Interval',
    fDays: 'Weekdays',
    fDayOfMonth: 'Day of month',
    fAt: 'Time',
    fTz: 'Timezone',
    fTitle: 'Ticket title',
    fTitlePh: 'Weekly review — {week}',
    fTitleHint: 'Placeholders: {date} {week} {month} {slot}',
    fBody: 'Ticket body',
    fLabels: 'Labels',
    fLabelsPh: 'comma-separated',
    fRationale: 'Rationale',
    fRationalePh: 'Why does this work recur?',
    previewLabel: 'The next slots',
    create: 'Create',
    cancel: 'Cancel',
    confirmDelete: 'Delete this schedule? The tickets it already created are kept.',
    confirmReject: 'Reject this proposal? That is final.',
    needHuman: "Your token needs the 'human' scope for that.",
    created: 'Schedule created.',
    pendingCreated: 'Recorded, but not active yet — a human has to activate it.',
    ranNew: 'Ticket created:',
    ranNothing: 'That slot already had a ticket, so nothing was created.',
    saved: 'Saved.',
    deleted: 'Deleted. The tickets were kept.',
    pickDay: 'Pick at least one weekday.',
    gateNoRead: "That token has no 'read' scope.",
    refresh: 'Refresh',
    signOut: 'Sign out',
    navExpand: 'Expand navigation',
    navCollapse: 'Collapse navigation',
    navAccount: 'Account',
    projectSearch: 'Search projects',
    projectNoMatch: 'No project matches “{q}”',
    project: 'project',
    requestFailed: 'Request failed',
    dismiss: 'Dismiss',
    tokenNeeded: 'Enter a token.',
  },
  de: {
    schedules: 'Zeitpläne',
    board: 'Board',
    inbox: 'Inbox',
    initiatives: 'Initiativen',
    settings: 'Einstellungen',
    gateTokenSub:
      "Token mit 'read'. Zum Aktivieren, Pausieren oder Anlegen braucht es zusätzlich 'human'.",
    gateLabel: 'API-Token',
    gateOpen: 'Öffnen',
    allProjects: 'Alle Projekte',
    newSchedule: 'Neuer Zeitplan',
    newSub:
      'Ein Zeitplan legt in einem Rhythmus ein ganz normales Ticket an. Das Ticket verweist zurück — und auf nichts sonst.',
    groupPending: 'Wartet auf dich',
    groupActive: 'Aktiv',
    groupStopped: 'Gestoppt',
    emptyAll:
      'Noch keine Zeitpläne. Ein Zeitplan legt in einem Rhythmus ein Ticket an — wöchentlicher Review, Schlüsselrotation, tägliche Backup-Prüfung.',
    bannerPending: 'Ein Agent hat einen Zeitplan vorgeschlagen. Bis du ihn aktivierst, passiert nichts.',
    statusPending: 'wartet',
    statusActive: 'aktiv',
    statusPaused: 'pausiert',
    statusRejected: 'abgelehnt',
    statusRetired: 'beendet',
    actActivate: 'Aktivieren',
    actReject: 'Ablehnen',
    actPause: 'Pausieren',
    actResume: 'Fortsetzen',
    actRun: 'Jetzt ausführen',
    actDelete: 'Löschen',
    outDone: 'erledigt',
    outOpen: 'offen',
    outNf: 'nicht erfüllt',
    nextAt: 'nächstes',
    noneScheduled: 'pausiert — nichts geplant',
    proposedBy: 'vorgeschlagen von',
    lastN: 'letzte',
    nowArrow: 'jetzt →',
    neverFired: 'noch nie ausgeführt',
    unitDay: 'täglich',
    unitWeek: 'wöchentlich',
    unitMonth: 'monatlich',
    everyN: 'alle',
    onDay: 'am',
    pluralDays: 'Tage',
    pluralWeeks: 'Wochen',
    pluralMonths: 'Monate',
    cadenceLabel: 'Rhythmus',
    fName: 'Name',
    fNamePh: 'Wöchentlicher Review',
    fEvery: 'Einheit',
    fInterval: 'Intervall',
    fDays: 'Wochentage',
    fDayOfMonth: 'Tag im Monat',
    fAt: 'Uhrzeit',
    fTz: 'Zeitzone',
    fTitle: 'Ticket-Titel',
    fTitlePh: 'Wöchentlicher Review — {week}',
    fTitleHint: 'Platzhalter: {date} {week} {month} {slot}',
    fBody: 'Ticket-Text',
    fLabels: 'Labels',
    fLabelsPh: 'komma-getrennt',
    fRationale: 'Begründung',
    fRationalePh: 'Warum kehrt diese Arbeit wieder?',
    previewLabel: 'Die nächsten Termine',
    create: 'Anlegen',
    cancel: 'Abbrechen',
    confirmDelete: 'Diesen Zeitplan löschen? Die bereits angelegten Tickets bleiben erhalten.',
    confirmReject: 'Diesen Vorschlag ablehnen? Das ist endgültig.',
    needHuman: "Dafür braucht dein Token den 'human'-Scope.",
    created: 'Zeitplan angelegt.',
    pendingCreated: 'Angelegt, aber noch nicht aktiv — ein Mensch muss ihn aktivieren.',
    ranNew: 'Ticket angelegt:',
    ranNothing: 'Dieser Termin hatte schon ein Ticket — es wurde keins angelegt.',
    saved: 'Gespeichert.',
    deleted: 'Gelöscht. Die Tickets sind geblieben.',
    pickDay: 'Wähle mindestens einen Wochentag.',
    gateNoRead: "Dieses Token hat keinen 'read'-Scope.",
    refresh: 'Aktualisieren',
    signOut: 'Abmelden',
    navExpand: 'Navigation ausklappen',
    navCollapse: 'Navigation einklappen',
    navAccount: 'Konto',
    projectSearch: 'Projekte suchen',
    projectNoMatch: 'Kein Projekt passt zu „{q}“',
    project: 'Projekt',
    requestFailed: 'Anfrage fehlgeschlagen',
    dismiss: 'Schließen',
    tokenNeeded: 'Token eingeben.',
  },
})

export type Strings = (typeof STR)['en']
