// DE/EN strings for /board, extracted verbatim from src/board.html.
//
// 127 keys — lifted mechanically and checked for key-set and order equality
// before being written here. EN is the reference shape, so a DE table that
// drifts is a compile error rather than an `undefined` shown to German readers.
import { defineStrings } from '@/lib/i18n'

export const STR = defineStrings({
  en: {
    // ---- added by the port: the two grant modes ----
    // The original hardcoded these in English. `#s=` and especially `#a=` are the
    // surfaces shown to people OUTSIDE the fleet — an answer link goes to an
    // outside expert, in a project that may well set a question language — so
    // they were the last place that should have been English-only.
    shareRO: "Read-only share",
    shareExpired: "This shared link has expired.",
    shareEmpty: "Nothing is shared here yet.",
    validUntil: "Valid until",
    grantThanks: "Thank you — your answer was recorded.",
    grantSpent: "This link has already been used.",
    grantExpired: "This link has expired or is no longer valid.",
    ticketCtx: "Ticket context",
    submit: "Submit",
    typeFirst: "Type an answer first.",
    sendFirst: "Select an answer first.",
    customDivider: "or your own instruction",
    customPlaceholder: "Write your own instruction …",
    board: "Board",
    inbox: "Inbox",
    initiatives: "Initiatives",
    schedules: "Schedules",
    fromSchedule: "from schedule",
    notFulfilled: "not fulfilled",
    gateSub: "Read-only kanban. Paste a read token to view a project's tickets.",
    gateTokenLabel: "Read token",
    gateProjectLabel: "Project",
    gateOpen: "Open board",
    archived: "archived",
    askHuman: "Ask a human",
    refresh: "Refresh",
    signout: "Sign out",
    navExpand: "Expand navigation",
    navCollapse: "Collapse navigation",
    navAccount: "Account",
    idle: "idle",
    loading: "loading…",
    live: "live",
    reconnecting: "reconnecting…",
    fullInbox: "full inbox →",
    mine: "mine",
    description: "Description",
    dependencies: "Dependencies",
    links: "Links",
    labels: "Labels",
    comments: "Comments",
    promotions: "Promotions",
    proofCommit: "Proof commit",
    noComments: "No comments.",
    blockedN: "Blocked — {n} open question(s)",
    answerInInbox: "Answer in Inbox →",
    answeringResumes: "Answering resumes this ticket.",
    decisionRouted: "A decision is routed for this ticket.",
    allClear: "All clear — no open questions.",
    noneForTicket: "No open questions for this ticket.",
    cantAnswer: "This token cannot answer (no 'human' scope). Showing the queue read-only.",
    couldNotLoadQ: "Could not load questions: ",
    blocking: "blocking",
    advisory: "advisory",
    awaiting: "awaiting ",
    awaitingSub: " — a human asked for more info. Full thread in the inbox.",
    inConversation: "in conversation",
    inConvN: "In conversation — {n} question(s) with the agent",
    inConvSub: "A human asked for more research. The agent owes the next reply.",
    readThread: "Read the thread in the Inbox →",
    state: "state",
    claimedBy: "claimed by",
    unclaimed: "unclaimed",
    question1: "1 question",
    questionsN: "{n} questions",
    openQ: "open question(s)",
    allEpics: "All epics",
    allTickets: "All tickets",
    allTags: "All tags",
    allValues: "All",
    tagsHdr: "Tags",
    groupEpic: "by epic",
    noEpic: "No epic",
    showMore: "+ {n} more",
    showLess: "show less",
    recommends: "recommends:",
    notePlaceholder: "optional note…",
    answerPlaceholder: "your answer…",
    approve: "Approve",
    reject: "Reject",
    yes: "Yes",
    no: "No",
    send: "Send",
    noDescription: "(no description)",
    blockedByRel: "blocked by ",
    agoSep: " ago · ",
    refLabel: "ref ",
    settings: "Settings",
    setTitle: "Project settings",
    setSub: "How this project writes, how long an answer link stays valid, and how long an agent holds a ticket.",
    setLangLabel: "Question language",
    setLangHelp: "The human-facing language agents should phrase ask-a-human questions in (e.g. “German”). Leave empty for no preference.",
    setLangPh: "e.g. German",
    setStyleLabel: "Style guide",
    setStyleHelp: "The house style for text agents write — ticket titles and bodies, comments, and questions. Agents get it on every work-loop call, before they write.",
    setStylePh: "e.g. Two sentences max. Plain language, no marketing voice. Prefer a yes/no or a short choice over an open question.",
    setTtlLabel: "Answer-link lifetime",
    setTtlHelp: "How long a link handed to someone outside the org to answer exactly one question stays valid. An individual link can override this when it is minted. Unlike the two fields above, this one is enforced.",
    setTtlDefault: "Default (7 days)",
    setTtl24h: "24 hours",
    setTtl3d: "3 days",
    setTtl7d: "7 days",
    setTtl14d: "14 days",
    setTtl30d: "30 days (maximum)",
    setTtlSecs: "seconds",
    setClaimTtlLabel: "Default claim lifetime",
    setClaimTtlHelp: "How long an agent holds a ticket when it asks for no lifetime of its own. When it lapses the sweeper returns the ticket to the queue, even if work is still going — agents extend it with takomo_heartbeat.",
    setClaimTtlDefault: "Default (15 minutes)",
    setMaxClaimTtlLabel: "Maximum claim lifetime",
    setMaxClaimTtlHelp: "The ceiling an agent may ask for when claiming. It is also how long a crashed agent blocks a ticket, since only expired claims are released — higher means fewer heartbeats but slower recovery.",
    setMaxClaimTtlDefault: "Default (1 hour)",
    setDur5m: "5 minutes",
    setDur15m: "15 minutes",
    setDur30m: "30 minutes",
    setDur1h: "1 hour",
    setDur2h: "2 hours",
    setDur4h: "4 hours",
    setDur8h: "8 hours",
    setDur24h: "24 hours",
    setChars: "characters",
    setOver: "over the limit",
    setSave: "Save",
    setSaving: "Saving…",
    setSaved: "Saved.",
    setCancel: "Cancel",
    setLoading: "loading…",
    setLoadErr: "Could not load settings: ",
    setReadOnly: "Read-only — this token has no 'admin' scope. Changing these settings needs an admin token.",
    setClose: "Close",
    taTicket: "Filter by ticket (id or title)",
    taClear: "Clear filter",
    taNoMatch: "No match for “{q}”",
    taMore: "+{n} more — keep typing to narrow",
    taCount: "{n} matches",
    taCount1: "1 match",
    taCountMore: "showing {shown} of {n}",
    clearFilters: "Clear filters",
    noMatchFilters: "No tickets match these filters.",
    taTagValue: "Filter by tag value (handle or name)",
    taLabel: "Filter by labels (more than one allowed)",
    allLabels: "All labels",
    taAddMore: "add another…",
    taRemove: "Remove “{v}”",
    taAnyOf: "Shows tickets carrying ANY of the selected labels — picking more broadens, never narrows.",
    filters: "Filters",
  },
  de: {
    // ---- added by the port: the two grant modes ----
    shareRO: "Nur-Lesen-Freigabe",
    shareExpired: "Dieser Freigabe-Link ist abgelaufen.",
    shareEmpty: "Hier ist noch nichts freigegeben.",
    validUntil: "Gültig bis",
    grantThanks: "Danke — deine Antwort wurde gespeichert.",
    grantSpent: "Dieser Link wurde bereits verwendet.",
    grantExpired: "Dieser Link ist abgelaufen oder ungültig.",
    ticketCtx: "Ticket-Kontext",
    submit: "Absenden",
    typeFirst: "Zuerst eine Antwort eingeben.",
    sendFirst: "Zuerst eine Antwort auswählen.",
    customDivider: "oder eigene Anweisung",
    customPlaceholder: "Eigene Anweisung schreiben …",
    board: "Board",
    inbox: "Inbox",
    initiatives: "Initiativen",
    schedules: "Zeitpläne",
    fromSchedule: "aus Zeitplan",
    notFulfilled: "nicht erfüllt",
    gateSub: "Nur-Lese-Kanban. Lese-Token einfügen, um die Tickets eines Projekts zu sehen.",
    gateTokenLabel: "Lese-Token",
    gateProjectLabel: "Projekt",
    gateOpen: "Board öffnen",
    archived: "archiviert",
    askHuman: "Mensch fragen",
    refresh: "Aktualisieren",
    signout: "Abmelden",
    navExpand: "Navigation ausklappen",
    navCollapse: "Navigation einklappen",
    navAccount: "Konto",
    idle: "bereit",
    loading: "lädt…",
    live: "live",
    reconnecting: "neu verbinden…",
    fullInbox: "volle Inbox →",
    mine: "nur meine",
    description: "Beschreibung",
    dependencies: "Abhängigkeiten",
    links: "Links",
    labels: "Labels",
    comments: "Kommentare",
    promotions: "Promotions",
    proofCommit: "Nachweis-Commit",
    noComments: "Keine Kommentare.",
    blockedN: "Blockiert — {n} offene Frage(n)",
    answerInInbox: "In der Inbox beantworten →",
    answeringResumes: "Antworten setzt dieses Ticket fort.",
    decisionRouted: "Eine Entscheidung wird geroutet.",
    allClear: "Alles erledigt — keine offenen Fragen.",
    noneForTicket: "Keine offenen Fragen für dieses Ticket.",
    cantAnswer: "Dieses Token kann nicht antworten (keine 'human'-Berechtigung). Warteschlange nur lesbar.",
    couldNotLoadQ: "Fragen konnten nicht geladen werden: ",
    blocking: "blockierend",
    advisory: "beratend",
    awaiting: "wartet auf ",
    awaitingSub: " — ein Mensch hat um mehr Kontext gebeten. Voller Verlauf in der Inbox.",
    inConversation: "im Gespräch",
    inConvN: "Im Gespräch — {n} Frage(n) beim Agenten",
    inConvSub: "Ein Mensch hat um mehr Recherche gebeten. Der nächste Beitrag liegt beim Agenten.",
    readThread: "Verlauf in der Inbox lesen →",
    state: "Status",
    claimedBy: "beansprucht von",
    unclaimed: "frei",
    question1: "1 Frage",
    questionsN: "{n} Fragen",
    openQ: "offene Frage(n)",
    allEpics: "Alle Epics",
    allTickets: "Alle Tickets",
    allTags: "Alle Tags",
    allValues: "Alle",
    tagsHdr: "Tags",
    groupEpic: "nach Epic",
    noEpic: "Ohne Epic",
    showMore: "+ {n} weitere",
    showLess: "weniger anzeigen",
    recommends: "empfiehlt:",
    notePlaceholder: "Notiz (optional)…",
    answerPlaceholder: "Deine Antwort…",
    approve: "Genehmigen",
    reject: "Ablehnen",
    yes: "Ja",
    no: "Nein",
    send: "Senden",
    noDescription: "(keine Beschreibung)",
    blockedByRel: "blockiert von ",
    agoSep: " · ",
    refLabel: "Ref ",
    settings: "Einstellungen",
    setTitle: "Projekt-Einstellungen",
    setSub: "Wie dieses Projekt schreibt, wie lange ein Antwort-Link gilt und wie lange ein Agent ein Ticket hält.",
    setLangLabel: "Sprache der Fragen",
    setLangHelp: "Die menschlich sichtbare Sprache, in der Agenten Fragen an Menschen stellen sollen (z. B. „German“). Leer lassen für keine Vorgabe.",
    setLangPh: "z. B. German",
    setStyleLabel: "Stil-Leitfaden",
    setStyleHelp: "Der Hausstil für Texte, die Agenten schreiben — Ticket-Titel und -Beschreibungen, Kommentare und Fragen. Agenten erhalten ihn bei jedem Arbeitsschritt, bevor sie schreiben.",
    setStylePh: "z. B. Maximal zwei Sätze. Klare Sprache, kein Marketing-Ton. Lieber eine Ja/Nein-Frage als eine offene.",
    setTtlLabel: "Gültigkeit des Antwort-Links",
    setTtlHelp: "Wie lange ein Antwort-Link gültig bleibt, den jemand außerhalb der Organisation für genau eine Frage erhält. Ein einzelner Link kann beim Erstellen davon abweichen. Anders als die beiden Felder oben wird dies erzwungen.",
    setTtlDefault: "Standard (7 Tage)",
    setTtl24h: "24 Stunden",
    setTtl3d: "3 Tage",
    setTtl7d: "7 Tage",
    setTtl14d: "14 Tage",
    setTtl30d: "30 Tage (Maximum)",
    setTtlSecs: "Sekunden",
    setClaimTtlLabel: "Standard-Laufzeit eines Claims",
    setClaimTtlHelp: "Wie lange ein Agent ein Ticket standardmäßig hält, wenn er beim Claim keine eigene Laufzeit angibt. Läuft sie ab, gibt der Sweeper das Ticket zurück in die Warteschlange — auch wenn noch daran gearbeitet wird. Agenten verlängern mit takomo_heartbeat.",
    setClaimTtlDefault: "Standard (15 Minuten)",
    setMaxClaimTtlLabel: "Maximale Laufzeit eines Claims",
    setMaxClaimTtlHelp: "Die Obergrenze, die ein Agent beim Claim anfordern darf. Das ist zugleich die Zeit, die ein abgestürzter Agent ein Ticket blockiert, denn nur abgelaufene Claims werden freigegeben — höher heißt weniger Heartbeats, aber langsamere Erholung.",
    setMaxClaimTtlDefault: "Standard (1 Stunde)",
    setDur5m: "5 Minuten",
    setDur15m: "15 Minuten",
    setDur30m: "30 Minuten",
    setDur1h: "1 Stunde",
    setDur2h: "2 Stunden",
    setDur4h: "4 Stunden",
    setDur8h: "8 Stunden",
    setDur24h: "24 Stunden",
    setChars: "Zeichen",
    setOver: "über dem Limit",
    setSave: "Speichern",
    setSaving: "Speichern…",
    setSaved: "Gespeichert.",
    setCancel: "Abbrechen",
    setLoading: "lädt…",
    setLoadErr: "Einstellungen konnten nicht geladen werden: ",
    setReadOnly: "Nur lesbar — dieses Token hat keine 'admin'-Berechtigung. Ändern erfordert ein Admin-Token.",
    setClose: "Schließen",
    taTicket: "Nach Ticket filtern (ID oder Titel)",
    taClear: "Filter löschen",
    taNoMatch: "Kein Treffer für „{q}“",
    taMore: "+{n} weitere — weitertippen zum Eingrenzen",
    taCount: "{n} Treffer",
    taCount1: "1 Treffer",
    taCountMore: "{shown} von {n} angezeigt",
    clearFilters: "Filter zurücksetzen",
    noMatchFilters: "Keine Tickets passen zu diesen Filtern.",
    taTagValue: "Nach Tag-Wert filtern (Handle oder Name)",
    taLabel: "Nach Labels filtern (mehrere möglich)",
    allLabels: "Alle Labels",
    taAddMore: "weiteres hinzufügen…",
    taRemove: "„{v}“ entfernen",
    taAnyOf: "Zeigt Tickets mit einem BELIEBIGEN der gewählten Labels — mehr wählen erweitert, grenzt nie ein.",
    filters: "Filter",
  },
})

export type Strings = (typeof STR)['en']
