// DE/EN strings for /board, extracted verbatim from src/board.html.
//
// 127 keys — lifted mechanically and checked for key-set and order equality
// before being written here. EN is the reference shape, so a DE table that
// drifts is a compile error rather than an `undefined` shown to German readers.
//
// Several keys share a name with inbox/strings.ts but carry different text
// (takomo-2hk4) — advisory, allClear, gateOpen, groupEpic, noneForTicket. The
// tables stay per-page; see board-inbox-strings.test.ts for the explicit list.
import { defineStrings } from '@/lib/i18n'

export const STR = defineStrings({
  en: {
    // ---- added by the port: the two grant modes ----
    // The original hardcoded these in English. `#s=` and especially `#a=` are the
    // surfaces shown to people OUTSIDE the fleet — an answer link goes to an
    // outside expert, in a project that may well set a question language — so
    // they were the last place that should have been English-only.
    shareRO: "Read-only share",
    shareExpired: "This shared link has expired.",
    shareEmpty: "Nothing is shared here yet.",
    validUntil: "Valid until",
    grantThanks: "Thank you — your answer was recorded.",
    grantSpent: "This link has already been used.",
    grantExpired: "This link has expired or is no longer valid.",
    ticketCtx: "Ticket context",
    submit: "Submit",
    typeFirst: "Type an answer first.",
    sendFirst: "Select an answer first.",
    customDivider: "or your own instruction",
    customPlaceholder: "Write your own instruction …",
    specification: "Specification",
    board: "Board",
    epics: "Epics",
    epGateSub: "Paste a token to view a project’s epics.",
    epGateOpen: "Open epics",
    epNoProject: "Create a project to organize its epics.",
    epLoadError: "Could not load epics.",
    epRefreshError: "Could not refresh epics. Showing the last loaded version.",
    epRetry: "Try again",
    inbox: "Inbox",
    documents: "Documents",
    initiatives: "Initiatives",
    mindmaps: "Mindmaps",
    schedules: "Schedules",
    verification: "Verification",
    environments: "Environments",
    fromSchedule: "from schedule",
    notFulfilled: "not fulfilled",
    gateSub: "Read-only kanban. Paste a read token to view a project's tickets.",
    gateTokenLabel: "Read token",
    gateProjectLabel: "Project",
    gateOpen: "Open board",
    archived: "archived",
    askHuman: "Ask a human",
    askAssignee: 'Waiting on',
    askAssigneeHint: 'One person, by name — as well as, or instead of, a domain. For an approval this is the gate: only they can answer it.',
    askAssigneeAnyone: 'Anyone with the expertise',
    refresh: "Refresh",
    signout: "Sign out",
    navExpand: "Expand navigation",
    navCollapse: "Collapse navigation",
    navAccount: "Account",
    project: "project",
    projectSearch: "Search projects",
    projectNoMatch: "No project matches “{q}”",
    projArchived: 'Archived',
    projArchivedHint:
      'This project is archived: nothing under it can be changed until an admin puts it back. Everything here still reads.',
    idle: "idle",
    loading: "loading…",
    live: "live",
    reconnecting: "reconnecting…",
    fullInbox: "full inbox →",
    mine: "mine",
    description: "Description",
    dependencies: "Dependencies",
    links: "Links",
    labels: "Labels",
    comments: "Comments",
    promotions: "Promotions",
    proofCommit: "Proof commit",
    noComments: "No comments.",
    blockedN: "Blocked — {n} open question(s)",
    answerInInbox: "Answer in Inbox →",
    answeringResumes: "Answering resumes this ticket.",
    decisionRouted: "A decision is routed for this ticket.",
    allClear: "All clear — no open questions.",
    noneForTicket: "No open questions for this ticket.",
    cantAnswer: "This token cannot answer (no 'human' scope). Showing the queue read-only.",
    couldNotLoadQ: "Could not load questions: ",
    blocking: "blocking",
    advisory: "advisory",
    awaiting: "awaiting ",
    awaitingSub: " — a human asked for more info. Full thread in the inbox.",
    inConversation: "in conversation",
    inConvN: "In conversation — {n} question(s) with the agent",
    inConvSub: "A human asked for more research. The agent owes the next reply.",
    readThread: "Read the thread in the Inbox →",
    state: "state",
    claimedBy: "claimed by",
    unclaimed: "unclaimed",
    question1: "1 question",
    questionsN: "{n} questions",
    openQ: "open question(s)",
    allEpics: "All epics",
    allTickets: "All tickets",
    allTags: "All tags",
    allValues: "All",
    tagsHdr: "Tags",
    groupEpic: "by epic",
    noEpic: "No epic",
    viewLabel: "View",
    viewBoard: "Board",
    viewEpics: "Epics",
    epHeld: "held",
    epStalled: "stalled",
    epAwaiting: "awaiting an answer",
    epFlagged: "flagged",
    epReady: "ready",
    epBacklog: "backlog",
    epHeldBy: "held by",
    epIdle: "idle",
    epIndefinite: "no expiry",
    epNoLane: "No initiative",
    epEmpty: "No epics in this project.",
    epEmptyHint: "An epic groups the work of one version; create a ticket of type epic.",
    epProgress: "Progress",
    epColEpic: "Epic",
    epColState: "State",
    epColLanes: "Initiatives",
    epColHolder: "Holder",
    epColLastActivity: "Last activity",
    epSortAsc: "sorted ascending",
    epSortDesc: "sorted descending",
    epSortNone: "sortable",
    epFilterStateCategory: "Category",
    epFilterLane: "Initiative",
    epFilterClaimed: "Claim",
    epFilterAll: "All",
    epFilterClaimedYes: "Claimed",
    epFilterClaimedNo: "Unclaimed",
    epPresets: "Quick views",
    epPresetRecentCreated: "Recently created",
    epPresetNearlyComplete: "Nearly complete",
    epPresetNotStarted: "Not started",
    epPresetStalled: "Stalled",
    epPresetAwaiting: "Awaiting answer",
    epPresetUnclaimed: "Unclaimed",
    epPresetFlagged: "Flagged",
    epUnclaimed: "unclaimed",
    epLastActivityUnknown: "unknown (unclaimed)",
    epStalledMarker: "stalled",
    showMore: "+ {n} more",
    showLess: "show less",
    recommends: "recommends:",
    notePlaceholder: "optional note…",
    answerPlaceholder: "your answer…",
    approve: "Approve",
    reject: "Reject",
    yes: "Yes",
    no: "No",
    send: "Send",
    noDescription: "(no description)",
    blockedByRel: "blocked by ",
    agoSep: " ago · ",
    refLabel: "ref ",
    settings: "Settings",
    // Borrowed by the ask/inbox drawers. Named for what they are now that the
    // project-settings dialog they were introduced for lives in /settings.
    close: "Close",
    cancel: "Cancel",
    askLangHint: "The human-facing language agents should phrase ask-a-human questions in (e.g. \u201cGerman\u201d). Leave empty for no preference.",
    taTicket: "Filter by ticket (id or title)",
    taClear: "Clear filter",
    taNoMatch: "No match for “{q}”",
    taMore: "+{n} more — keep typing to narrow",
    taCount: "{n} matches",
    taCount1: "1 match",
    taCountMore: "showing {shown} of {n}",
    clearFilters: "Clear filters",
    noMatchFilters: "No tickets match these filters.",
    taTagValue: "Filter by tag value (handle or name)",
    taLabel: "Filter by labels (more than one allowed)",
    allLabels: "All labels",
    taAddMore: "add another…",
    taRemove: "Remove “{v}”",
    taAnyOf: "Shows tickets carrying ANY of the selected labels — picking more broadens, never narrows.",
    filters: "Filters",
  },
  de: {
    // ---- added by the port: the two grant modes ----
    shareRO: "Nur-Lesen-Freigabe",
    shareExpired: "Dieser Freigabe-Link ist abgelaufen.",
    shareEmpty: "Hier ist noch nichts freigegeben.",
    validUntil: "Gültig bis",
    grantThanks: "Danke — deine Antwort wurde gespeichert.",
    grantSpent: "Dieser Link wurde bereits verwendet.",
    grantExpired: "Dieser Link ist abgelaufen oder ungültig.",
    ticketCtx: "Ticket-Kontext",
    submit: "Absenden",
    typeFirst: "Zuerst eine Antwort eingeben.",
    sendFirst: "Zuerst eine Antwort auswählen.",
    customDivider: "oder eigene Anweisung",
    customPlaceholder: "Eigene Anweisung schreiben …",
    specification: "Spezifikation",
    board: "Board",
    epics: "Epics",
    epGateSub: "Füge einen Token ein, um die Epics eines Projekts zu sehen.",
    epGateOpen: "Epics öffnen",
    epNoProject: "Erstelle ein Projekt, um seine Epics zu organisieren.",
    epLoadError: "Epics konnten nicht geladen werden.",
    epRefreshError: "Epics konnten nicht aktualisiert werden. Die zuletzt geladene Version wird angezeigt.",
    epRetry: "Erneut versuchen",
    inbox: "Inbox",
    documents: "Dokumente",
    initiatives: "Initiativen",
    mindmaps: "Mindmaps",
    schedules: "Zeitpläne",
    verification: "Verifizierung",
    environments: "Umgebungen",
    fromSchedule: "aus Zeitplan",
    notFulfilled: "nicht erfüllt",
    gateSub: "Nur-Lese-Kanban. Lese-Token einfügen, um die Tickets eines Projekts zu sehen.",
    gateTokenLabel: "Lese-Token",
    gateProjectLabel: "Projekt",
    gateOpen: "Board öffnen",
    archived: "archiviert",
    askHuman: "Mensch fragen",
    askAssignee: 'Wartet auf',
    askAssigneeHint: 'Eine Person namentlich — zusätzlich zu oder anstelle einer Domäne. Bei einer Freigabe ist das die Hürde: nur sie kann antworten.',
    askAssigneeAnyone: 'Jede Person mit der Expertise',
    refresh: "Aktualisieren",
    signout: "Abmelden",
    navExpand: "Navigation ausklappen",
    navCollapse: "Navigation einklappen",
    navAccount: "Konto",
    project: "Projekt",
    projectSearch: "Projekte suchen",
    projectNoMatch: "Kein Projekt passt zu „{q}“",
    projArchived: 'Archiviert',
    projArchivedHint:
      'Dieses Projekt ist archiviert: Darunter lässt sich nichts ändern, bis ein Admin es zurückholt. Lesen funktioniert hier weiterhin.',
    idle: "bereit",
    loading: "lädt…",
    live: "live",
    reconnecting: "neu verbinden…",
    fullInbox: "volle Inbox →",
    mine: "nur meine",
    description: "Beschreibung",
    dependencies: "Abhängigkeiten",
    links: "Links",
    labels: "Labels",
    comments: "Kommentare",
    promotions: "Promotions",
    proofCommit: "Nachweis-Commit",
    noComments: "Keine Kommentare.",
    blockedN: "Blockiert — {n} offene Frage(n)",
    answerInInbox: "In der Inbox beantworten →",
    answeringResumes: "Antworten setzt dieses Ticket fort.",
    decisionRouted: "Eine Entscheidung wird geroutet.",
    allClear: "Alles erledigt — keine offenen Fragen.",
    noneForTicket: "Keine offenen Fragen für dieses Ticket.",
    cantAnswer: "Dieses Token kann nicht antworten (keine 'human'-Berechtigung). Warteschlange nur lesbar.",
    couldNotLoadQ: "Fragen konnten nicht geladen werden: ",
    blocking: "blockierend",
    advisory: "beratend",
    awaiting: "wartet auf ",
    awaitingSub: " — ein Mensch hat um mehr Kontext gebeten. Voller Verlauf in der Inbox.",
    inConversation: "im Gespräch",
    inConvN: "Im Gespräch — {n} Frage(n) beim Agenten",
    inConvSub: "Ein Mensch hat um mehr Recherche gebeten. Der nächste Beitrag liegt beim Agenten.",
    readThread: "Verlauf in der Inbox lesen →",
    state: "Status",
    claimedBy: "beansprucht von",
    unclaimed: "frei",
    question1: "1 Frage",
    questionsN: "{n} Fragen",
    openQ: "offene Frage(n)",
    allEpics: "Alle Epics",
    allTickets: "Alle Tickets",
    allTags: "Alle Tags",
    allValues: "Alle",
    tagsHdr: "Tags",
    groupEpic: "nach Epic",
    noEpic: "Ohne Epic",
    viewLabel: "Ansicht",
    viewBoard: "Board",
    viewEpics: "Epics",
    epHeld: "belegt",
    epStalled: "ohne Bewegung",
    epAwaiting: "Antwort offen",
    epFlagged: "auffällig",
    epReady: "bereit",
    epBacklog: "wartend",
    epHeldBy: "belegt von",
    epIdle: "untätig",
    epIndefinite: "ohne Ablauf",
    epNoLane: "Keine Initiative",
    epEmpty: "Keine Epics in diesem Projekt.",
    epEmptyHint:
      "Ein Epic bündelt die Arbeit einer Version; erstelle ein Ticket vom Typ epic.",
    epProgress: "Fortschritt",
    epColEpic: "Epic",
    epColState: "Status",
    epColLanes: "Initiativen",
    epColHolder: "Belegung",
    epColLastActivity: "Letzte Aktivität",
    epSortAsc: "aufsteigend sortiert",
    epSortDesc: "absteigend sortiert",
    epSortNone: "sortierbar",
    epFilterStateCategory: "Kategorie",
    epFilterLane: "Initiative",
    epFilterClaimed: "Belegung",
    epFilterAll: "Alle",
    epFilterClaimedYes: "Belegt",
    epFilterClaimedNo: "Frei",
    epPresets: "Schnellansichten",
    epPresetRecentCreated: "Zuletzt erstellt",
    epPresetNearlyComplete: "Fast fertig",
    epPresetNotStarted: "Noch nicht begonnen",
    epPresetStalled: "Ohne Bewegung",
    epPresetAwaiting: "Antwort offen",
    epPresetUnclaimed: "Frei",
    epPresetFlagged: "Auffällig",
    epUnclaimed: "frei",
    epLastActivityUnknown: "unbekannt (frei)",
    epStalledMarker: "ohne Bewegung",
    showMore: "+ {n} weitere",
    showLess: "weniger anzeigen",
    recommends: "empfiehlt:",
    notePlaceholder: "Notiz (optional)…",
    answerPlaceholder: "Deine Antwort…",
    approve: "Genehmigen",
    reject: "Ablehnen",
    yes: "Ja",
    no: "Nein",
    send: "Senden",
    noDescription: "(keine Beschreibung)",
    blockedByRel: "blockiert von ",
    agoSep: " · ",
    refLabel: "Ref ",
    settings: "Einstellungen",
    close: "Schließen",
    cancel: "Abbrechen",
    askLangHint: "Die menschlich sichtbare Sprache, in der Agenten Fragen an Menschen stellen sollen (z. B. \u201eGerman\u201c). Leer lassen für keine Vorgabe.",
    taTicket: "Nach Ticket filtern (ID oder Titel)",
    taClear: "Filter löschen",
    taNoMatch: "Kein Treffer für „{q}“",
    taMore: "+{n} weitere — weitertippen zum Eingrenzen",
    taCount: "{n} Treffer",
    taCount1: "1 Treffer",
    taCountMore: "{shown} von {n} angezeigt",
    clearFilters: "Filter zurücksetzen",
    noMatchFilters: "Keine Tickets passen zu diesen Filtern.",
    taTagValue: "Nach Tag-Wert filtern (Handle oder Name)",
    taLabel: "Nach Labels filtern (mehrere möglich)",
    allLabels: "Alle Labels",
    taAddMore: "weiteres hinzufügen…",
    taRemove: "„{v}“ entfernen",
    taAnyOf: "Zeigt Tickets mit einem BELIEBIGEN der gewählten Labels — mehr wählen erweitert, grenzt nie ein.",
    filters: "Filter",
  },
})

export type Strings = (typeof STR)['en']
