// DE/EN strings for /mindmaps.
// EN is the reference shape — a DE table that drifts is a compile error.
import { defineStrings } from '@/lib/i18n'

export const STR = defineStrings({
  en: {
    mindmaps: 'Mindmaps',
    board: 'Board',
    inbox: 'Inbox',
    documents: 'Documents',
    initiatives: 'Initiatives',
    schedules: 'Schedules',
    verification: 'Verification',
    environments: 'Environments',
    settings: 'Settings',
    project: 'Project',
    projectSearch: 'Search projects',
    projectNoMatch: 'No project matches',
    allProjects: 'All projects',
    navExpand: 'Expand',
    navCollapse: 'Collapse',
    navAccount: 'Account',
    signOut: 'Sign out',
    gateTokenSub: "A token with 'read'. Growing or promoting a map additionally needs 'write'.",
    gateLabel: 'API token',
    gateOpen: 'Open',
    gateNoRead: 'That token cannot read this instance.',
    tokenNeeded: 'A token is needed to open a mindmap.',
    requestFailed: 'Request failed',
    needWrite: "This token cannot change anything here — it needs the 'write' scope.",

    newMap: 'New mindmap',
    newMapPrompt: 'What is this brainstorm about? It becomes the root.',
    noMaps: 'No mindmaps in this project yet.',
    noneOpen: 'Nothing open',
    noneOpenHint: 'Pick a mindmap, or start one. It is scratch by design — throwing one away is ordinary.',
    deleteMap: 'Delete map',
    mapDeleted: 'Deleted. Anything its branches became is untouched.',
    confirmDeleteMap:
      'Delete this mindmap and its nodes? Whatever its branches became — epics, initiatives — stays.',
    confirmPrune: 'Remove this thought and everything under it?',

    branch: 'Branch',
    newThought: 'New thought',
    canvasEmpty: 'Nothing here yet',
    canvasEmptyHint: 'Add a branch, then press Enter for the next thought and Tab to go deeper.',
    keysHint: 'Enter: next thought · Tab: deeper · F2: edit · Delete: prune',
    addChild: 'Add underneath',
    addSibling: 'Add after',
    fit: 'Fit',
    tidy: 'Tidy up',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    cannotDrop: 'Cannot drop a branch onto its own child',

    makeEpic: 'Make an epic',
    makeInitiative: 'Make an initiative',
    promoteEpicHint:
      'An epic titled from this thought, with its direct children as tickets under it.',
    promoteIniHint: 'An initiative seeded with this whole branch.',
    alreadyPromoted: 'This branch already graduated.',
    promotedEpic: 'Epic {id} created. The node stays, pointing at it.',
    promotedInitiative: 'Initiative {id} created. The node stays, pointing at it.',
  },
  de: {
    mindmaps: 'Mindmaps',
    board: 'Board',
    inbox: 'Posteingang',
    documents: 'Dokumente',
    initiatives: 'Initiativen',
    schedules: 'Zeitpläne',
    verification: 'Verifikation',
    environments: 'Umgebungen',
    settings: 'Einstellungen',
    project: 'Projekt',
    projectSearch: 'Projekte suchen',
    projectNoMatch: 'Kein Projekt passt',
    allProjects: 'Alle Projekte',
    navExpand: 'Ausklappen',
    navCollapse: 'Einklappen',
    navAccount: 'Konto',
    signOut: 'Abmelden',
    gateTokenSub:
      "Ein Token mit 'read'. Zum Erweitern oder Überführen einer Map zusätzlich 'write'.",
    gateLabel: 'API-Token',
    gateOpen: 'Öffnen',
    gateNoRead: 'Dieses Token kann diese Instanz nicht lesen.',
    tokenNeeded: 'Zum Öffnen einer Mindmap wird ein Token benötigt.',
    requestFailed: 'Anfrage fehlgeschlagen',
    needWrite: "Dieses Token kann hier nichts ändern — es braucht den 'write'-Scope.",

    newMap: 'Neue Mindmap',
    newMapPrompt: 'Worum geht es? Das wird die Wurzel.',
    noMaps: 'Noch keine Mindmaps in diesem Projekt.',
    noneOpen: 'Nichts geöffnet',
    noneOpenHint:
      'Wähle eine Mindmap oder starte eine. Sie ist bewusst Notizzettel — eine wegzuwerfen ist normal.',
    deleteMap: 'Map löschen',
    mapDeleted: 'Gelöscht. Was aus ihren Ästen wurde, bleibt bestehen.',
    confirmDeleteMap:
      'Diese Mindmap samt Knoten löschen? Was aus ihren Ästen wurde — Epics, Initiativen — bleibt.',
    confirmPrune: 'Diesen Gedanken und alles darunter entfernen?',

    branch: 'Ast',
    newThought: 'Neuer Gedanke',
    canvasEmpty: 'Noch nichts hier',
    canvasEmptyHint:
      'Füge einen Ast hinzu, dann Enter für den nächsten Gedanken und Tab für eine Ebene tiefer.',
    keysHint: 'Enter: nächster Gedanke · Tab: tiefer · F2: bearbeiten · Entf: entfernen',
    addChild: 'Darunter hinzufügen',
    addSibling: 'Danach hinzufügen',
    fit: 'Einpassen',
    tidy: 'Aufräumen',
    zoomIn: 'Vergrößern',
    zoomOut: 'Verkleinern',
    cannotDrop: 'Ein Ast kann nicht auf sein eigenes Kind gelegt werden',

    makeEpic: 'Epic daraus machen',
    makeInitiative: 'Initiative daraus machen',
    promoteEpicHint:
      'Ein Epic mit diesem Gedanken als Titel und den direkten Kindern als Tickets darunter.',
    promoteIniHint: 'Eine Initiative, die mit diesem ganzen Ast startet.',
    alreadyPromoted: 'Dieser Ast wurde bereits überführt.',
    promotedEpic: 'Epic {id} erstellt. Der Knoten bleibt und zeigt darauf.',
    promotedInitiative: 'Initiative {id} erstellt. Der Knoten bleibt und zeigt darauf.',
  },
})
