// DE/EN strings for /mindmaps.
// EN is the reference shape — a DE table that drifts is a compile error.
import { defineStrings } from '@/lib/i18n'

export const STR = defineStrings({
  en: {
    specification: 'Specification',
    viewMap: 'Map',
    viewDocument: 'Document',
    viewTests: 'Tests',
    mindmaps: 'Mindmaps',
    board: 'Board',
    inbox: 'Inbox',
    documents: 'Documents',
    initiatives: 'Initiatives',
    schedules: 'Schedules',
    verification: 'Verification',
    environments: 'Environments',
    settings: 'Settings',
    navExpand: 'Expand',
    navCollapse: 'Collapse',
    navAccount: 'Account',
    signOut: 'Sign out',
    gateTokenSub: "A token with 'read'. Growing or promoting a map additionally needs 'write'.",
    gateLabel: 'API token',
    gateOpen: 'Open',
    gateNoRead: 'That token cannot read this instance.',
    tokenNeeded: 'A token is needed to open a mindmap.',
    requestFailed: 'Request failed',
    needWrite: "This token cannot change anything here — it needs the 'write' scope.",

    newMap: 'New mindmap',
    newMapPrompt: 'What is this brainstorm about? It becomes the root.',
    noProjects: 'No projects you can reach.',
    project: 'Project',
    projectSearch: 'Search projects…',
    projectNoMatch: 'No projects match “{q}”.',
    needProject: 'Pick a project first — a brainstorm belongs to one.',
    startHere: 'This project has no brainstorm yet.',
    startHereHint: 'One map per project. The title becomes the root, and everything hangs off it.',
    mapDeleted: 'Deleted. Anything its branches became is untouched.',
    confirmDeleteMap:
      'Delete this mindmap and its nodes? Whatever its branches became — epics, initiatives — stays.',

    branch: 'Branch',
    newThought: 'New thought',
    canvasEmpty: 'Nothing here yet',
    canvasEmptyHint: 'Add a branch, then press Enter for the next thought and Tab to go deeper.',
    addChild: 'Add underneath',
    addSibling: 'Add after',
    fit: 'Fit',
    tidy: 'Tidy up',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    cannotDrop: 'Cannot drop a branch onto its own child',

    promoteEpicHint:
      'An epic titled from this thought, with its direct children as tickets under it.',
    promoteIniHint: 'An initiative seeded with this whole branch.',
    promotedEpic: 'Epic {id} created. The node stays, pointing at it.',
    promotedInitiative: 'Initiative {id} created. The node stays, pointing at it.',

    connected: 'Live',
    connecting: 'Connecting…',
    disconnected: 'Offline',
    alsoHere: 'Also here',
    justYou: 'Just you',
    readOnlyBanner: "This token can read this map but not change it — that needs 'write'.",
    cancel: 'Cancel',

    relationLabelPrompt: 'What is the relation? A word or two — it is drawn on the line.',
    pickRelationTarget: 'Click the other node.',
    capNodes: 'This map is full at {max} thoughts. A branch this big wants to be an initiative.',
    capRelationships: 'This map is at its {max} relations.',
    hasNotes: 'Has notes',
    expandBranch: 'Unfold this branch',
    collapseBranch: 'Fold this branch',
    layoutRadial: 'Radial',
    layoutTree: 'Tree',

    editThought: 'Open this thought',
    renameThought: 'Rename this thought',
    nameField: 'Title of this thought',
    nameHint: 'A few words',
    nodeDialogTitle: '“{title}”',
    nodeDialogSubtitle:
      'Everything this thought holds. The map itself is for reading — changes land as you make them, the way they do in a shared document.',
    notes: 'Notes',
    notesHint: 'The long form. Never drawn on the canvas — the title is what stays readable at a glance.',
    notesCount: '{n} of {max} characters',
    kind: 'Kind',
    shape: 'Shape',
    color: 'Colour',
    colorNone: 'No colour',
    edgeLabel: 'Edge label',
    edgeLabelHint: 'Names the line to its parent',
    reviewed: 'A person has looked at this',
    origin: 'Written by',
    originHuman: 'person',
    originAgent: 'agent',
    attachmentsBadge: 'Attachments ({n})',
    attachmentsTitle: 'Attached to “{title}”',
    attachmentsSubtitle:
        'Pointers to things that live elsewhere. Nothing is uploaded — a shared map replays every byte in it to everyone who joins.',
    attachmentsEmpty: 'Nothing attached to this thought yet.',
    openAttachments: 'Attachments…',
    attachmentsCount: '{n} of {max}',
    attachmentsFull: 'This thought is at its {max} attachments.',
    attachmentKind: 'Kind',
    attachmentName: 'Name',
    attachmentGist: 'One line of what it says',
    attachmentRef: 'URL or path',
    addAttachment: 'Add attachment',
    attachSomething: 'Attach something',
    editAttachment: 'Edit',
    saveAttachment: 'Save',
    removeAttachment: 'Remove attachment',
    close: 'Close',
    droppedFileGist: 'A file that was dropped here. It still lives where you dropped it from.',
    dropHere: 'Drop it here to attach it',
    nodeActions: 'Actions for this thought',
    nodeMenu: 'This thought',
    relations: 'Relations',
    removeRelation: 'Remove relation',
    noRelations: 'No relations from this thought.',
    promotedLabel: 'became',
    kindThought: 'Thought',
    kindQuestion: 'Question',
    kindDecision: 'Decision',
    kindScreen: 'Screen',
    kindComponent: 'Component',
    shapeRounded: 'Rounded',
    shapeSquare: 'Square',
    shapePill: 'Pill',
    attPdf: 'PDF',
    attCode: 'Code',
    attTable: 'Table',
    attDiagram: 'Diagram',
    attAudio: 'Audio',
    attLink: 'Link',

    renameMapPrompt: 'A new title for this brainstorm. It is the root of the map.',
    hasRelations: 'Has relations',
    paletteScopeNode: 'This thought',
    paletteScopeMap: 'This map',
    palettePlaceholder: 'What do you want to do?',
    paletteNoMatch: 'Nothing here matches that.',
    paletteKeys: '↑↓ move · Enter run · Esc close',
    paletteHint: 'Press ⌘K for everything else — switching project included.',
    gotoPlaceholder: 'Which thought? Type any part of it.',
    projectPlaceholder: 'Which project?',
    cmdChild: 'Add a thought underneath',
    cmdSibling: 'Add a thought after this one',
    cmdRename: 'Rename this thought',
    cmdOpen: 'Open this thought',
    cmdOpenHint: 'Its notes, what is attached, and the lines running to other branches.',
    cmdRelate: 'Relate to…',
    cmdAttach: 'Attach something',
    cmdPromoteEpic: 'Make an epic',
    cmdPromoteInitiative: 'Make an initiative',
    cmdCollapse: 'Fold this branch',
    cmdExpand: 'Unfold this branch',
    cmdDelete: 'Remove this branch',
    cmdPlan: 'Read it as the plan',
    cmdTests: 'Show its tests',
    nodeTests: '{n} tests',
    nodeTestsFailing: '{n} tests, {m} not passing',
    cmdGoto: 'Go to a thought…',
    cmdFit: 'Fit the whole map',
    cmdTidy: 'Tidy up',
    cmdRenameMap: 'Rename this map',
    cmdProject: 'Switch project…',
    cmdDeleteMap: 'Delete this map',
    cmdNewMap: 'Start a brainstorm here',
    cmdRelateHint: 'Then click the other thought and name the line.',
    cmdDeleteHint: 'Everything under it goes too.',
    cmdPlanHint: 'The same tree written out, at the selected thought.',
    cmdTestsHint: 'What has to pass before this part is done.',
    cmdGotoHint: 'Selects it and brings it into view.',
    cmdDeleteMapHint: 'What its branches became stays.',

    pruneTitle: 'Remove this branch?',
    pruneBody: '“{title}” and the {n} thoughts under it go together. Nothing here is removed on its own.',
    pruneBodyLeaf: 'Remove “{title}”?',
    pruneConfirmTitle: 'Once more, then',
    pruneConfirmBody: 'This takes {n} thoughts off a map that is open in front of other people right now, and it cannot be undone.',
    pruneWatching: 'In this map right now: {names}',
    pruneNext: 'Continue',
    pruneRemove: 'Remove the branch',

    foldedSummary: 'Folded — {n} thoughts under this one',
    trustLens: 'Trust',
    openPlan: 'Plan',
    /** Dictation. One sentence spoken becomes one thought on the map. */
    voiceStart: 'Dictate',
    voiceStop: 'Stop',
    voiceStarting: 'Starting…',
    voiceHearing: 'Listening…',
    voiceNoMic: 'No microphone available, or the browser refused access to it.',
    voiceLost: 'Dictation stopped. Press Dictate to start again.',
    trustLensCmd: 'Turn the trust lens on or off',
    trustLensHint: 'Tints every thought by how much anybody has confirmed about it.',
    trustLegend: 'How sure are we?',
    trustConfirmed: 'A person wrote this and confirmed it',
    trustMachine: 'An agent wrote it and nobody has checked it',
    trustUnverified: 'A thought nobody has confirmed yet',

    questionEyebrow: 'open question',
    newQuestion: 'What is the question?',
    cmdAsk: 'Ask a question about this',
    cmdAskHint: 'A question hangs beside this thought until somebody answers it in their own words.',
    answer: 'Your answer',
    answerHint: 'In your own words. Nothing is asked of a model.',
    answerAction: '⏎ Answer',
    answerAbout: 'Goes into the notes on “{title}”, and this question goes.',
    answerAlone: 'This question is about nothing in particular, so the answer becomes its own notes.',

    detachTitle: 'Cut this line?',
    detachBody: '“{title}” stops hanging off “{parent}” and becomes a thought of its own. Nothing is removed.',
    detachCarries: '{n} thoughts under it come with it.',
    detachConfirmTitle: 'Once more, then',
    detachConfirmBody: 'This moves “{title}” out of the branch it is being read in, on a map that is open in front of other people right now.',
    detachNext: 'Continue',
    detachAction: 'Cut the line',
    detachRow: 'Detach from its parent',
    cutEdge: 'Cut the line: “{title}” stops hanging off “{parent}”',
  },
  de: {
    specification: 'Spezifikation',
    viewMap: 'Karte',
    viewDocument: 'Dokument',
    viewTests: 'Tests',
    mindmaps: 'Mindmaps',
    board: 'Board',
    inbox: 'Posteingang',
    documents: 'Dokumente',
    initiatives: 'Initiativen',
    schedules: 'Zeitpläne',
    verification: 'Verifikation',
    environments: 'Umgebungen',
    settings: 'Einstellungen',
    navExpand: 'Ausklappen',
    navCollapse: 'Einklappen',
    navAccount: 'Konto',
    signOut: 'Abmelden',
    gateTokenSub:
      "Ein Token mit 'read'. Zum Erweitern oder Überführen einer Map zusätzlich 'write'.",
    gateLabel: 'API-Token',
    gateOpen: 'Öffnen',
    gateNoRead: 'Dieses Token kann diese Instanz nicht lesen.',
    tokenNeeded: 'Zum Öffnen einer Mindmap wird ein Token benötigt.',
    requestFailed: 'Anfrage fehlgeschlagen',
    needWrite: "Dieses Token kann hier nichts ändern — es braucht den 'write'-Scope.",

    newMap: 'Neue Mindmap',
    newMapPrompt: 'Worum geht es? Das wird die Wurzel.',
    noProjects: 'Keine erreichbaren Projekte.',
    project: 'Projekt',
    projectSearch: 'Projekte suchen…',
    projectNoMatch: 'Keine Projekte für „{q}“.',
    needProject: 'Erst ein Projekt wählen — ein Brainstorm gehört zu einem.',
    startHere: 'Dieses Projekt hat noch kein Brainstorm.',
    startHereHint: 'Eine Map pro Projekt. Der Titel wird die Wurzel, alles andere hängt daran.',
    mapDeleted: 'Gelöscht. Was aus ihren Ästen wurde, bleibt bestehen.',
    confirmDeleteMap:
      'Diese Mindmap samt Knoten löschen? Was aus ihren Ästen wurde — Epics, Initiativen — bleibt.',

    branch: 'Ast',
    newThought: 'Neuer Gedanke',
    canvasEmpty: 'Noch nichts hier',
    canvasEmptyHint:
      'Füge einen Ast hinzu, dann Enter für den nächsten Gedanken und Tab für eine Ebene tiefer.',
    addChild: 'Darunter hinzufügen',
    addSibling: 'Danach hinzufügen',
    fit: 'Einpassen',
    tidy: 'Aufräumen',
    zoomIn: 'Vergrößern',
    zoomOut: 'Verkleinern',
    cannotDrop: 'Ein Ast kann nicht auf sein eigenes Kind gelegt werden',

    promoteEpicHint:
      'Ein Epic mit diesem Gedanken als Titel und den direkten Kindern als Tickets darunter.',
    promoteIniHint: 'Eine Initiative, die mit diesem ganzen Ast startet.',
    promotedEpic: 'Epic {id} erstellt. Der Knoten bleibt und zeigt darauf.',
    promotedInitiative: 'Initiative {id} erstellt. Der Knoten bleibt und zeigt darauf.',

    connected: 'Live',
    connecting: 'Verbinde…',
    disconnected: 'Offline',
    alsoHere: 'Auch hier',
    justYou: 'Nur du',
    readOnlyBanner: "Dieses Token kann die Map lesen, aber nicht ändern — dafür braucht es 'write'.",
    cancel: 'Abbrechen',

    relationLabelPrompt: 'Was ist die Beziehung? Ein, zwei Worte — sie stehen auf der Linie.',
    pickRelationTarget: 'Klicke den anderen Knoten an.',
    capNodes: 'Diese Map ist mit {max} Gedanken voll. Ein so großer Ast will eine Initiative sein.',
    capRelationships: 'Diese Map hat ihre {max} Beziehungen erreicht.',
    hasNotes: 'Hat Notizen',
    expandBranch: 'Ast aufklappen',
    collapseBranch: 'Ast einklappen',
    layoutRadial: 'Radial',
    layoutTree: 'Baum',

    editThought: 'Diesen Gedanken öffnen',
    renameThought: 'Diesen Gedanken umbenennen',
    nameField: 'Titel dieses Gedankens',
    nameHint: 'Ein paar Worte',
    nodeDialogTitle: '„{title}“',
    nodeDialogSubtitle:
      'Alles, was dieser Gedanke enthält. Die Karte selbst ist zum Lesen da — Änderungen landen sofort, wie in einem geteilten Dokument.',
    notes: 'Notizen',
    notesHint: 'Die Langform. Steht nie auf der Leinwand — der Titel ist das, was auf einen Blick lesbar bleibt.',
    notesCount: '{n} von {max} Zeichen',
    kind: 'Art',
    shape: 'Form',
    color: 'Farbe',
    colorNone: 'Keine Farbe',
    edgeLabel: 'Kantenbeschriftung',
    edgeLabelHint: 'Benennt die Linie zum Elternknoten',
    reviewed: 'Ein Mensch hat das angesehen',
    origin: 'Geschrieben von',
    originHuman: 'Mensch',
    originAgent: 'Agent',
    attachmentsBadge: 'Anhänge ({n})',
    attachmentsTitle: 'Angehängt an „{title}“',
    attachmentsSubtitle:
        'Verweise auf Dinge, die woanders liegen. Nichts wird hochgeladen — eine geteilte Map spielt jedes Byte darin jedem neu Hinzukommenden erneut zu.',
    attachmentsEmpty: 'An diesem Gedanken hängt noch nichts.',
    openAttachments: 'Anhänge…',
    attachmentsCount: '{n} von {max}',
    attachmentsFull: 'Dieser Gedanke hat seine {max} Anhänge erreicht.',
    attachmentKind: 'Art',
    attachmentName: 'Name',
    attachmentGist: 'Eine Zeile, worum es geht',
    attachmentRef: 'URL oder Pfad',
    addAttachment: 'Anhang hinzufügen',
    attachSomething: 'Etwas anhängen',
    editAttachment: 'Bearbeiten',
    saveAttachment: 'Speichern',
    removeAttachment: 'Anhang entfernen',
    close: 'Schließen',
    droppedFileGist:
        'Eine hierher gezogene Datei. Sie liegt weiterhin dort, woher sie gezogen wurde.',
    dropHere: 'Hier ablegen, um es anzuhängen',
    nodeActions: 'Aktionen für diesen Gedanken',
    nodeMenu: 'Dieser Gedanke',
    relations: 'Beziehungen',
    removeRelation: 'Beziehung entfernen',
    noRelations: 'Keine Beziehungen von diesem Gedanken.',
    promotedLabel: 'wurde zu',
    kindThought: 'Gedanke',
    kindQuestion: 'Frage',
    kindDecision: 'Entscheidung',
    kindScreen: 'Screen',
    kindComponent: 'Komponente',
    shapeRounded: 'Abgerundet',
    shapeSquare: 'Eckig',
    shapePill: 'Pille',
    attPdf: 'PDF',
    attCode: 'Code',
    attTable: 'Tabelle',
    attDiagram: 'Diagramm',
    attAudio: 'Audio',
    attLink: 'Link',

    renameMapPrompt: 'Ein neuer Titel für dieses Brainstorm. Er ist die Wurzel der Map.',
    hasRelations: 'Hat Beziehungen',
    paletteScopeNode: 'Dieser Gedanke',
    paletteScopeMap: 'Diese Map',
    palettePlaceholder: 'Was möchtest du tun?',
    paletteNoMatch: 'Dazu passt hier nichts.',
    paletteKeys: '↑↓ bewegen · Enter ausführen · Esc schließen',
    paletteHint: 'Alles Weitere liegt auf ⌘K — auch der Projektwechsel.',
    gotoPlaceholder: 'Welcher Gedanke? Tippe irgendeinen Teil davon.',
    projectPlaceholder: 'Welches Projekt?',
    cmdChild: 'Gedanken darunter hinzufügen',
    cmdSibling: 'Gedanken danach hinzufügen',
    cmdRename: 'Diesen Gedanken umbenennen',
    cmdOpen: 'Diesen Gedanken öffnen',
    cmdOpenHint: 'Seine Notizen, was daran hängt, und die Linien zu anderen Ästen.',
    cmdRelate: 'Beziehung ziehen zu…',
    cmdAttach: 'Etwas anhängen',
    cmdPromoteEpic: 'Epic daraus machen',
    cmdPromoteInitiative: 'Initiative daraus machen',
    cmdCollapse: 'Ast einklappen',
    cmdExpand: 'Ast aufklappen',
    cmdDelete: 'Diesen Ast entfernen',
    cmdPlan: 'Als Plan lesen',
    cmdTests: 'Tests dazu zeigen',
    nodeTests: '{n} Tests',
    nodeTestsFailing: '{n} Tests, {m} nicht bestanden',
    cmdGoto: 'Zu einem Gedanken springen…',
    cmdFit: 'Ganze Map einpassen',
    cmdTidy: 'Aufräumen',
    cmdRenameMap: 'Diese Map umbenennen',
    cmdProject: 'Projekt wechseln…',
    cmdDeleteMap: 'Diese Map löschen',
    cmdNewMap: 'Hier ein Brainstorm starten',
    cmdRelateHint: 'Dann den anderen Gedanken anklicken und die Linie benennen.',
    cmdDeleteHint: 'Alles darunter geht mit.',
    cmdPlanHint: 'Derselbe Baum ausgeschrieben, beim gewählten Gedanken.',
    cmdTestsHint: 'Was bestehen muss, bevor dieser Teil fertig ist.',
    cmdGotoHint: 'Wählt ihn aus und holt ihn ins Bild.',
    cmdDeleteMapHint: 'Was aus ihren Ästen wurde, bleibt.',

    pruneTitle: 'Diesen Ast entfernen?',
    pruneBody: '„{title}“ und die {n} Gedanken darunter gehen zusammen. Nichts davon lässt sich einzeln entfernen.',
    pruneBodyLeaf: '„{title}“ entfernen?',
    pruneConfirmTitle: 'Dann noch einmal',
    pruneConfirmBody: 'Das nimmt {n} Gedanken von einer Map, die gerade bei anderen offen ist, und es lässt sich nicht rückgängig machen.',
    pruneWatching: 'Gerade in dieser Map: {names}',
    pruneNext: 'Weiter',
    pruneRemove: 'Ast entfernen',

    foldedSummary: 'Eingeklappt — {n} Gedanken darunter',
    trustLens: 'Vertrauen',
    openPlan: 'Plan',
    voiceStart: 'Diktieren',
    voiceStop: 'Stopp',
    voiceStarting: 'Startet…',
    voiceHearing: 'Hört zu…',
    voiceNoMic: 'Kein Mikrofon verfügbar, oder der Browser hat den Zugriff verweigert.',
    voiceLost: 'Diktat beendet. Zum Neustart auf Diktieren drücken.',
    trustLensCmd: 'Vertrauenslinse ein- oder ausschalten',
    trustLensHint: 'Färbt jeden Gedanken danach, wie viel jemand daran bestätigt hat.',
    trustLegend: 'Wie sicher sind wir?',
    trustConfirmed: 'Von einem Menschen geschrieben und bestätigt',
    trustMachine: 'Von einem Agenten geschrieben, von niemandem geprüft',
    trustUnverified: 'Ein Gedanke, den noch niemand bestätigt hat',

    questionEyebrow: 'offene Frage',
    newQuestion: 'Wie lautet die Frage?',
    cmdAsk: 'Eine Frage dazu stellen',
    cmdAskHint: 'Die Frage hängt neben dem Gedanken, bis jemand sie mit eigenen Worten beantwortet.',
    answer: 'Deine Antwort',
    answerHint: 'In deinen eigenen Worten. Es wird kein Modell gefragt.',
    answerAction: '⏎ Antworten',
    answerAbout: 'Kommt in die Notizen von „{title}“, und diese Frage verschwindet.',
    answerAlone: 'Diese Frage bezieht sich auf nichts Bestimmtes — die Antwort wird ihre eigene Notiz.',

    detachTitle: 'Diese Linie durchtrennen?',
    detachBody: '„{title}“ hängt dann nicht mehr an „{parent}“, sondern steht für sich. Es wird nichts entfernt.',
    detachCarries: '{n} Gedanken darunter kommen mit.',
    detachConfirmTitle: 'Dann noch einmal',
    detachConfirmBody: 'Das holt „{title}“ aus dem Ast heraus, in dem es gerade gelesen wird — auf einer Map, die bei anderen offen ist.',
    detachNext: 'Weiter',
    detachAction: 'Linie durchtrennen',
    detachRow: 'Vom Elternknoten lösen',
    cutEdge: 'Linie durchtrennen: „{title}“ hängt dann nicht mehr an „{parent}“',
  },
})
