// DE/EN strings for /mindmaps.
// EN is the reference shape — a DE table that drifts is a compile error.
import { defineStrings } from '@/lib/i18n'

export const STR = defineStrings({
  en: {
    specification: 'Specification',
    viewMap: 'Map',
    viewDocument: 'Document',
    viewTests: 'Promises',
    mindmaps: 'Specification',
    board: 'Board',
    epics: "Epics",
    inbox: 'Inbox',
    documents: 'Documents',
    initiatives: 'Initiatives',
    schedules: 'Schedules',
    verification: 'Promises',
    environments: 'Environments',
    settings: 'Settings',
    navExpand: 'Expand',
    navCollapse: 'Collapse',
    navAccount: 'Account',
    signOut: 'Sign out',
    gateTokenSub: "A token with 'read'. Changing the specification or promoting a section additionally needs 'write'.",
    gateLabel: 'API token',
    gateOpen: 'Open',
    gateNoRead: 'That token cannot read this instance.',
    tokenNeeded: 'A token is needed to open the specification.',
    requestFailed: 'Request failed',
    needWrite: "This token cannot change anything here — it needs the 'write' scope.",

    newMap: 'New specification',
    newMapPrompt: 'What is this specification about? Its title becomes the root.',
    noProjects: 'No projects you can reach.',
    project: 'Project',
    projectSearch: 'Search projects…',
    projectNoMatch: 'No projects match “{q}”.',
    needProject: 'Pick a project first — a specification belongs to one.',
    startHere: 'This project has no specification yet.',
    startHereHint: 'One specification per project. Its title becomes the root, and every section hangs off it.',
    mapDeleted: 'Specification deleted. Epics and initiatives promoted from it are untouched.',
    deleteSpecFirst: 'Delete this specification? (1 of 2)',
    deleteSpecSecond: 'Confirm deletion (2 of 2)',
    deleteSpecWarning:
      'This deletes the project’s specification: every section with its text, comments, attachments, relationships and proposals, in the document, map and tests views alike. Epics and initiatives promoted from it stay. To empty it but keep its history and links, reset it in Settings instead.',
    deleteSpecIrreversible: 'Deleting cannot be undone.',
    deleteSpecContinue: 'Continue to final confirmation',
    deleteSpecType: 'Type the specification’s ID or title to confirm',
    deleteSpecFinal: 'Delete specification',
    deleteSpecBusy: 'Deleting…',

    branch: 'Branch',
    newThought: 'New section',
    canvasEmpty: 'Nothing here yet',
    canvasEmptyHint: 'Add a section, then press Enter for the next one and Tab to go deeper.',
    addChild: 'Add underneath',
    addSibling: 'Add after',
    fit: 'Fit all',
    findNode: 'Find a section',
    noNodeMatches: 'No matching sections',
    fitBranch: 'Fit branch',
    lockView: 'Lock zoom and position',
    unlockView: 'Unlock zoom and position',
    notesPreview: 'Read preview',
    missingSection: 'Missing section',
    editNotes: 'Edit notes',
    editInDocument: 'Edit in document',
    notesInDocument: 'This section has formatting or is long, so it is edited in the document view, where nothing of it is lost.',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    cannotDrop: 'Cannot drop a branch onto its own child',

    connected: 'Live',
    connecting: 'Connecting…',
    disconnected: 'Offline',
    alsoHere: 'Also here',
    justYou: 'Just you',
    readOnlyBanner: "This token can read this specification but not change it — that needs 'write'.",
    cancel: 'Cancel',

    relationLabelPrompt: 'What is the relation? A word or two — it is drawn on the line.',
    pickRelationTarget: 'Click the other section.',
    capNodes: 'The specification has reached its limit of {max} sections.',
    capRelationships: 'The specification has reached its limit of {max} relations.',
    hasNotes: 'Has text',
    expandBranch: 'Unfold this branch',
    collapseBranch: 'Fold this branch',
    layoutRadial: 'Radial',
    layoutTree: 'Tree',
    layoutCustom: 'Custom',
    nextLayout: 'Switch to {layout}',

    editThought: 'Open this section',
    renameThought: 'Rename this section',
    nameField: 'Title of this section',
    nameHint: 'A few words',
    nodeDialogTitle: '“{title}”',
    nodeDialogSubtitle:
      'Everything this section holds. The map itself is for reading — changes land as you make them, the way they do in a shared document.',
    notes: 'Notes',
    notesHint: "The section's text. Never drawn on the canvas — the title is what stays readable at a glance.",
    notesCount: '{n} of {max} characters',
    kind: 'Kind',
    shape: 'Shape',
    color: 'Colour',
    colorNone: 'No colour',
    edgeLabel: 'Edge label',
    edgeLabelHint: 'Names the line to its parent',
    reviewed: 'A person has looked at this',
    origin: 'Written by',
    originHuman: 'person',
    originAgent: 'agent',
    attachmentsBadge: 'Attachments ({n})',
    attachmentsTitle: 'Attached to “{title}”',
    attachmentsSubtitle:
        'Pointers to things that live elsewhere. Nothing is uploaded — a shared specification replays every byte in it to everyone who joins.',
    attachmentsEmpty: 'Nothing is referenced from this section yet.',
    openAttachments: 'Attachments…',
    attachmentsCount: '{n} of {max}',
    attachmentsFull: 'This section is at its {max} attachments.',
    attachmentKind: 'Kind',
    attachmentName: 'Name',
    attachmentGist: 'One line of what it says',
    attachmentRef: 'URL or path',
    addAttachment: 'Add attachment',
    attachSomething: 'Attach something',
    editAttachment: 'Edit',
    saveAttachment: 'Save',
    removeAttachment: 'Remove attachment',
    close: 'Close',
    droppedFileGist: 'A file that was dropped here. It still lives where you dropped it from.',
    dropHere: 'Drop it here to attach it',
    nodeActions: 'Actions for this section',
    nodeMenu: 'This section',
    relations: 'Relations',
    removeRelation: 'Remove relation',
    noRelations: 'No relations from this section.',
    promotedLabel: 'became',
    kindThought: 'Section',
    kindQuestion: 'Question',
    kindDecision: 'Decision',
    kindScreen: 'Screen',
    kindComponent: 'Component',
    shapeRounded: 'Rounded',
    shapeSquare: 'Square',
    shapePill: 'Pill',
    attPdf: 'PDF',
    attCode: 'Code',
    attTable: 'Table',
    attDiagram: 'Diagram',
    attAudio: 'Audio',
    attLink: 'Link',

    renameMapPrompt: 'A new title for this specification. It is the root of the map.',
    hasRelations: 'Has relations',
    paletteScopeNode: 'This section',
    paletteScopeMap: 'This map',
    palettePlaceholder: 'What do you want to do?',
    paletteNoMatch: 'Nothing here matches that.',
    paletteKeys: '↑↓ move · Enter run · Esc close',
    paletteHint: 'Press ⌘K for everything else — switching project included.',
    gotoPlaceholder: 'Which section? Type any part of it.',
    projectPlaceholder: 'Which project?',
    cmdChild: 'Add a section underneath',
    cmdSibling: 'Add a section after this one',
    cmdRename: 'Rename this section',
    cmdDocument: 'Open in document',
    cmdDocumentHint: 'Its section in the document, selected and scrolled to.',
    cmdDocumentFocus: 'Focus in document',
    cmdDocumentFocusHint: 'Its section in the document, on its own.',
    cmdOpen: 'Open this section',
    cmdOpenHint: 'Its text, what is attached, and the lines running to other branches.',
    cmdRelate: 'Relate to…',
    cmdAttach: 'Attach something',
    cmdCollapse: 'Fold this branch',
    cmdExpand: 'Unfold this branch',
    cmdDelete: 'Remove this branch',
    cmdPlan: 'Read it as the document',
    cmdTests: 'Show its promises',
    nodeTests: '{n} promises',
    nodeTestsFailing: "{n} promises, {m} don't work",
    cmdGoto: 'Go to a section…',
    cmdFit: 'Fit the whole map',
    cmdTidy: 'Show tree layout',
    cmdRenameMap: 'Rename the specification',
    cmdProject: 'Switch project…',
    cmdDeleteMap: 'Delete the specification…',
    cmdNewMap: 'Start the specification here',
    cmdRelateHint: 'Then click the other section and name the line.',
    cmdDeleteHint: 'Everything under it goes too.',
    cmdPlanHint: 'The same tree written out, at the selected section.',
    cmdTestsHint: 'What has to pass before this part is done.',
    cmdGotoHint: 'Selects it and brings it into view.',
    cmdDeleteMapHint: 'Admins only. Asks you to type its ID or title first.',

    pruneTitle: 'Remove this branch?',
    pruneBody: '“{title}” and the {n} sections under it go together. Nothing here is removed on its own.',
    pruneBodyLeaf: 'Remove “{title}”?',
    pruneConfirmTitle: 'Once more, then',
    pruneConfirmBody: 'This takes {n} sections out of a specification that is open in front of other people right now, and it cannot be undone.',
    pruneWatching: 'In this specification right now: {names}',
    pruneNext: 'Continue',
    pruneRemove: 'Remove the branch',

    foldedSummary: 'Folded — {n} sections under this one',
    trustLens: 'Trust',
    openPlan: 'Document',
    /** Dictation. One sentence spoken becomes one section on the map. */
    voiceStart: 'Dictate',
    voiceStop: 'Stop',
    voiceStarting: 'Starting…',
    voiceHearing: 'Listening…',
    voiceNoMic: 'No microphone available, or the browser refused access to it.',
    voiceLost: 'Dictation stopped. Press Dictate to start again.',
    trustLensCmd: 'Turn the trust lens on or off',
    trustLensHint: 'Tints every section by how much anybody has confirmed about it.',
    trustLegend: 'How sure are we?',
    trustConfirmed: 'A person wrote this and confirmed it',
    trustMachine: 'An agent wrote it and nobody has checked it',
    trustUnverified: 'A section nobody has confirmed yet',

    questionEyebrow: 'open question',
    newQuestion: 'What is the question?',
    cmdAsk: 'Ask a question about this',
    cmdAskHint: 'A question hangs beside this section until somebody answers it in their own words.',
    answer: 'Your answer',
    answerHint: 'In your own words. Nothing is asked of a model.',
    answerAction: '⏎ Answer',
    answerAbout: 'Goes into the text of “{title}”, and this question goes.',
    answerAlone: 'This question is about nothing in particular, so the answer becomes its own text.',

    detachTitle: 'Cut this line?',
    detachBody: '“{title}” stops hanging off “{parent}” and becomes a section of its own. Nothing is removed.',
    detachCarries: '{n} sections under it come with it.',
    detachConfirmTitle: 'Once more, then',
    detachConfirmBody: 'This moves “{title}” out of the branch it is being read in, in a specification that is open in front of other people right now.',
    detachNext: 'Continue',
    detachAction: 'Cut the line',
    detachRow: 'Detach from its parent',
    cutEdge: 'Cut the line: “{title}” stops hanging off “{parent}”',
  },
  de: {
    specification: 'Spezifikation',
    viewMap: 'Karte',
    viewDocument: 'Dokument',
    viewTests: 'Zusagen',
    mindmaps: 'Spezifikation',
    board: 'Board',
    epics: "Epics",
    inbox: 'Posteingang',
    documents: 'Dokumente',
    initiatives: 'Initiativen',
    schedules: 'Zeitpläne',
    verification: 'Zusagen',
    environments: 'Umgebungen',
    settings: 'Einstellungen',
    navExpand: 'Ausklappen',
    navCollapse: 'Einklappen',
    navAccount: 'Konto',
    signOut: 'Abmelden',
    gateTokenSub:
      "Ein Token mit 'read'. Zum Ändern der Spezifikation oder Überführen eines Abschnitts zusätzlich 'write'.",
    gateLabel: 'API-Token',
    gateOpen: 'Öffnen',
    gateNoRead: 'Dieses Token kann diese Instanz nicht lesen.',
    tokenNeeded: 'Zum Öffnen der Spezifikation wird ein Token benötigt.',
    requestFailed: 'Anfrage fehlgeschlagen',
    needWrite: "Dieses Token kann hier nichts ändern — es braucht den 'write'-Scope.",

    newMap: 'Neue Spezifikation',
    newMapPrompt: 'Worum geht es in dieser Spezifikation? Ihr Titel wird die Wurzel.',
    noProjects: 'Keine erreichbaren Projekte.',
    project: 'Projekt',
    projectSearch: 'Projekte suchen…',
    projectNoMatch: 'Keine Projekte für „{q}“.',
    needProject: 'Erst ein Projekt wählen — eine Spezifikation gehört zu einem.',
    startHere: 'Dieses Projekt hat noch keine Spezifikation.',
    startHereHint: 'Eine Spezifikation pro Projekt. Ihr Titel wird die Wurzel, jeder Abschnitt hängt daran.',
    mapDeleted: 'Spezifikation gelöscht. Daraus erstellte Epics und Initiativen bleiben unberührt.',
    deleteSpecFirst: 'Diese Spezifikation löschen? (1 von 2)',
    deleteSpecSecond: 'Löschen bestätigen (2 von 2)',
    deleteSpecWarning:
      'Dies löscht die Spezifikation des Projekts: alle Abschnitte samt Text, Kommentaren, Anhängen, Beziehungen und Vorschlägen – in Dokument-, Map- und Testansicht gleichermaßen. Daraus erstellte Epics und Initiativen bleiben. Um sie zu leeren und Historie und Verknüpfungen zu behalten, setze sie stattdessen in den Einstellungen zurück.',
    deleteSpecIrreversible: 'Das Löschen kann nicht rückgängig gemacht werden.',
    deleteSpecContinue: 'Weiter zur letzten Bestätigung',
    deleteSpecType: 'Zur Bestätigung ID oder Titel der Spezifikation eingeben',
    deleteSpecFinal: 'Spezifikation löschen',
    deleteSpecBusy: 'Wird gelöscht…',

    branch: 'Ast',
    newThought: 'Neuer Abschnitt',
    canvasEmpty: 'Noch nichts hier',
    canvasEmptyHint:
      'Füge einen Abschnitt hinzu, dann Enter für den nächsten und Tab für eine Ebene tiefer.',
    addChild: 'Darunter hinzufügen',
    addSibling: 'Danach hinzufügen',
    fit: 'Alles einpassen',
    findNode: 'Abschnitt suchen',
    noNodeMatches: 'Keine passenden Abschnitte',
    fitBranch: 'Zweig einpassen',
    lockView: 'Zoom und Position sperren',
    unlockView: 'Zoom und Position entsperren',
    notesPreview: 'Lesevorschau',
    missingSection: 'Abschnitt fehlt',
    editNotes: 'Notizen bearbeiten',
    editInDocument: 'Im Dokument bearbeiten',
    notesInDocument: 'Dieser Abschnitt ist formatiert oder lang und wird deshalb in der Dokumentansicht bearbeitet, wo nichts davon verloren geht.',
    zoomIn: 'Vergrößern',
    zoomOut: 'Verkleinern',
    cannotDrop: 'Ein Ast kann nicht auf sein eigenes Kind gelegt werden',

    connected: 'Live',
    connecting: 'Verbinde…',
    disconnected: 'Offline',
    alsoHere: 'Auch hier',
    justYou: 'Nur du',
    readOnlyBanner: "Dieses Token kann die Spezifikation lesen, aber nicht ändern — dafür braucht es 'write'.",
    cancel: 'Abbrechen',

    relationLabelPrompt: 'Was ist die Beziehung? Ein, zwei Worte — sie stehen auf der Linie.',
    pickRelationTarget: 'Klicke den anderen Abschnitt an.',
    capNodes: 'Die Spezifikation hat ihre Grenze von {max} Abschnitten erreicht.',
    capRelationships: 'Die Spezifikation hat ihre Grenze von {max} Beziehungen erreicht.',
    hasNotes: 'Hat Text',
    expandBranch: 'Ast aufklappen',
    collapseBranch: 'Ast einklappen',
    layoutRadial: 'Radial',
    layoutTree: 'Tree',
    layoutCustom: 'Custom',
    nextLayout: 'Zu {layout} wechseln',

    editThought: 'Diesen Abschnitt öffnen',
    renameThought: 'Diesen Abschnitt umbenennen',
    nameField: 'Titel dieses Abschnitts',
    nameHint: 'Ein paar Worte',
    nodeDialogTitle: '„{title}“',
    nodeDialogSubtitle:
      'Alles, was dieser Abschnitt enthält. Die Karte selbst ist zum Lesen da — Änderungen landen sofort, wie in einem geteilten Dokument.',
    notes: 'Notizen',
    notesHint: 'Der Text des Abschnitts. Steht nie auf der Leinwand — der Titel ist das, was auf einen Blick lesbar bleibt.',
    notesCount: '{n} von {max} Zeichen',
    kind: 'Art',
    shape: 'Form',
    color: 'Farbe',
    colorNone: 'Keine Farbe',
    edgeLabel: 'Kantenbeschriftung',
    edgeLabelHint: 'Benennt die Linie zum Elternknoten',
    reviewed: 'Ein Mensch hat das angesehen',
    origin: 'Geschrieben von',
    originHuman: 'Mensch',
    originAgent: 'Agent',
    attachmentsBadge: 'Anhänge ({n})',
    attachmentsTitle: 'Angehängt an „{title}“',
    attachmentsSubtitle:
        'Verweise auf Dinge, die woanders liegen. Nichts wird hochgeladen — eine geteilte Spezifikation spielt jedes Byte darin jedem neu Hinzukommenden erneut zu.',
    attachmentsEmpty: 'Dieser Abschnitt verweist noch auf nichts.',
    openAttachments: 'Anhänge…',
    attachmentsCount: '{n} von {max}',
    attachmentsFull: 'Dieser Abschnitt hat seine {max} Anhänge erreicht.',
    attachmentKind: 'Art',
    attachmentName: 'Name',
    attachmentGist: 'Eine Zeile, worum es geht',
    attachmentRef: 'URL oder Pfad',
    addAttachment: 'Anhang hinzufügen',
    attachSomething: 'Etwas anhängen',
    editAttachment: 'Bearbeiten',
    saveAttachment: 'Speichern',
    removeAttachment: 'Anhang entfernen',
    close: 'Schließen',
    droppedFileGist:
        'Eine hierher gezogene Datei. Sie liegt weiterhin dort, woher sie gezogen wurde.',
    dropHere: 'Hier ablegen, um es anzuhängen',
    nodeActions: 'Aktionen für diesen Abschnitt',
    nodeMenu: 'Dieser Abschnitt',
    relations: 'Beziehungen',
    removeRelation: 'Beziehung entfernen',
    noRelations: 'Keine Beziehungen von diesem Abschnitt.',
    promotedLabel: 'wurde zu',
    kindThought: 'Abschnitt',
    kindQuestion: 'Frage',
    kindDecision: 'Entscheidung',
    kindScreen: 'Screen',
    kindComponent: 'Komponente',
    shapeRounded: 'Abgerundet',
    shapeSquare: 'Eckig',
    shapePill: 'Pille',
    attPdf: 'PDF',
    attCode: 'Code',
    attTable: 'Tabelle',
    attDiagram: 'Diagramm',
    attAudio: 'Audio',
    attLink: 'Link',

    renameMapPrompt: 'Ein neuer Titel für diese Spezifikation. Er ist die Wurzel der Map.',
    hasRelations: 'Hat Beziehungen',
    paletteScopeNode: 'Dieser Abschnitt',
    paletteScopeMap: 'Diese Map',
    palettePlaceholder: 'Was möchtest du tun?',
    paletteNoMatch: 'Dazu passt hier nichts.',
    paletteKeys: '↑↓ bewegen · Enter ausführen · Esc schließen',
    paletteHint: 'Alles Weitere liegt auf ⌘K — auch der Projektwechsel.',
    gotoPlaceholder: 'Welcher Abschnitt? Tippe irgendeinen Teil davon.',
    projectPlaceholder: 'Welches Projekt?',
    cmdChild: 'Abschnitt darunter hinzufügen',
    cmdSibling: 'Abschnitt danach hinzufügen',
    cmdRename: 'Diesen Abschnitt umbenennen',
    cmdDocument: 'Im Dokument öffnen',
    cmdDocumentHint: 'Sein Abschnitt im Dokument, ausgewählt und ins Bild geholt.',
    cmdDocumentFocus: 'Im Dokument fokussieren',
    cmdDocumentFocusHint: 'Sein Abschnitt im Dokument, für sich allein.',
    cmdOpen: 'Diesen Abschnitt öffnen',
    cmdOpenHint: 'Sein Text, was daran hängt, und die Linien zu anderen Ästen.',
    cmdRelate: 'Beziehung ziehen zu…',
    cmdAttach: 'Etwas anhängen',
    cmdCollapse: 'Ast einklappen',
    cmdExpand: 'Ast aufklappen',
    cmdDelete: 'Diesen Ast entfernen',
    cmdPlan: 'Als Dokument lesen',
    cmdTests: 'Zusagen dazu zeigen',
    nodeTests: '{n} Zusagen',
    nodeTestsFailing: '{n} Zusagen, {m} funktionieren nicht',
    cmdGoto: 'Zu einem Abschnitt springen…',
    cmdFit: 'Ganze Map einpassen',
    cmdTidy: 'Baumlayout anzeigen',
    cmdRenameMap: 'Spezifikation umbenennen',
    cmdProject: 'Projekt wechseln…',
    cmdDeleteMap: 'Spezifikation löschen…',
    cmdNewMap: 'Hier die Spezifikation beginnen',
    cmdRelateHint: 'Dann den anderen Abschnitt anklicken und die Linie benennen.',
    cmdDeleteHint: 'Alles darunter geht mit.',
    cmdPlanHint: 'Derselbe Baum ausgeschrieben, beim gewählten Abschnitt.',
    cmdTestsHint: 'Was bestehen muss, bevor dieser Teil fertig ist.',
    cmdGotoHint: 'Wählt ihn aus und holt ihn ins Bild.',
    cmdDeleteMapHint: 'Nur für Admins. Verlangt vorher ID oder Titel.',

    pruneTitle: 'Diesen Ast entfernen?',
    pruneBody: '„{title}“ und die {n} Abschnitte darunter gehen zusammen. Nichts davon lässt sich einzeln entfernen.',
    pruneBodyLeaf: '„{title}“ entfernen?',
    pruneConfirmTitle: 'Dann noch einmal',
    pruneConfirmBody: 'Das nimmt {n} Abschnitte aus einer Spezifikation, die gerade bei anderen offen ist, und es lässt sich nicht rückgängig machen.',
    pruneWatching: 'Gerade in dieser Spezifikation: {names}',
    pruneNext: 'Weiter',
    pruneRemove: 'Ast entfernen',

    foldedSummary: 'Eingeklappt — {n} Abschnitte darunter',
    trustLens: 'Vertrauen',
    openPlan: 'Dokument',
    voiceStart: 'Diktieren',
    voiceStop: 'Stopp',
    voiceStarting: 'Startet…',
    voiceHearing: 'Hört zu…',
    voiceNoMic: 'Kein Mikrofon verfügbar, oder der Browser hat den Zugriff verweigert.',
    voiceLost: 'Diktat beendet. Zum Neustart auf Diktieren drücken.',
    trustLensCmd: 'Vertrauenslinse ein- oder ausschalten',
    trustLensHint: 'Färbt jeden Abschnitt danach, wie viel jemand daran bestätigt hat.',
    trustLegend: 'Wie sicher sind wir?',
    trustConfirmed: 'Von einem Menschen geschrieben und bestätigt',
    trustMachine: 'Von einem Agenten geschrieben, von niemandem geprüft',
    trustUnverified: 'Ein Abschnitt, den noch niemand bestätigt hat',

    questionEyebrow: 'offene Frage',
    newQuestion: 'Wie lautet die Frage?',
    cmdAsk: 'Eine Frage dazu stellen',
    cmdAskHint: 'Die Frage hängt neben dem Abschnitt, bis jemand sie mit eigenen Worten beantwortet.',
    answer: 'Deine Antwort',
    answerHint: 'In deinen eigenen Worten. Es wird kein Modell gefragt.',
    answerAction: '⏎ Antworten',
    answerAbout: 'Kommt in den Text von „{title}“, und diese Frage verschwindet.',
    answerAlone: 'Diese Frage bezieht sich auf nichts Bestimmtes — die Antwort wird ihr eigener Text.',

    detachTitle: 'Diese Linie durchtrennen?',
    detachBody: '„{title}“ hängt dann nicht mehr an „{parent}“, sondern ist ein eigener Abschnitt. Es wird nichts entfernt.',
    detachCarries: '{n} Abschnitte darunter kommen mit.',
    detachConfirmTitle: 'Dann noch einmal',
    detachConfirmBody: 'Das holt „{title}“ aus dem Ast heraus, in dem es gerade gelesen wird — in einer Spezifikation, die bei anderen offen ist.',
    detachNext: 'Weiter',
    detachAction: 'Linie durchtrennen',
    detachRow: 'Vom Elternknoten lösen',
    cutEdge: 'Linie durchtrennen: „{title}“ hängt dann nicht mehr an „{parent}“',
  },
})
