// DE/EN strings for /environments.
// EN is the reference shape — a DE table that drifts is a compile error.
import { defineStrings } from '@/lib/i18n'

export const STR = defineStrings({
  en: {
    specification: 'Specification',
    board: 'Board',
    epics: "Epics",
    inbox: 'Inbox',
    documents: 'Documents',
    initiatives: 'Initiatives',
    mindmaps: 'Mindmaps',
    schedules: 'Schedules',
    verification: 'Verification',
    environments: 'Environments',
    settings: 'Settings',

    gateTokenSub: "A token with 'read'. Registering or editing an environment additionally needs 'write'.",
    gateLabel: 'API token',
    gateOpen: 'Open',
    tokenNeeded: 'A token is needed to read this project.',
    gateNoRead: "That token cannot read. Use one carrying the 'read' scope.",
    requestFailed: 'The request failed.',
    allProjects: 'All projects',
    project: 'Project',
    projectSearch: 'Search projects',
    projectNoMatch: 'No project matches',
    navExpand: 'Expand',
    navCollapse: 'Collapse',
    navAccount: 'Account',
    signOut: 'Sign out',
    refresh: 'Refresh',

    newEnvironment: 'New environment',
    needWrite: "Registering an environment needs a token with the 'write' scope.",
    empty:
      'No environments yet. An environment is where a check can be run — a URL, how to bring the thing up, and whether writing to it is safe. Without one, every verdict is a claim nobody can reproduce.',
    emptyHint: 'Agents can register their own: an ephemeral preview instance is exactly the case this is for.',

    showArchived: 'Show archived',
    archived: 'archived',
    readOnly: 'read-only',
    writable: 'writable',
    bringUp: 'Bring up',
    teardown: 'Teardown',
    credentials: 'Credentials',
    credentialsNote: 'a pointer — Takomo stores no secrets',
    dataState: 'Data',
    notes: 'Notes',
    edit: 'Edit',
    archive: 'Archive',
    unarchive: 'Restore',
    confirmArchive:
      'Archive this environment? Verdicts taken there keep referencing it, and you can restore it.',

    fSlug: 'Slug',
    fSlugHint: 'What an agent types. Cannot be changed later — checks address environments by it.',
    fName: 'Name',
    fKind: 'Kind',
    fBaseUrl: 'Base URL',
    fBaseUrlPh: 'https://staging.example.com',
    fBringUp: 'How to bring it up',
    fBringUpPh: 'backlot up --ttl 900',
    fBringUpHint: 'Prose or a command. Takomo never runs it — it hands it to whoever needs it next.',
    fTeardown: 'How to give it back',
    fTeardownPh: 'backlot release',
    fDataState: 'What is in it',
    fWritable: 'Destructive cases may run here',
    fWritableHint: 'Advisory. Takomo executes nothing and cannot enforce it. Production defaults to off.',
    fCredentials: 'Where the credential lives',
    fCredentialsPh: 'env:STAGING_TOKEN',
    fCredentialsHint:
      'A POINTER, never a credential: every token with read can see this field.',
    fNotes: 'Caveats',
    fNotesPh: 'Reseeded 03:00 UTC; shares the payment sandbox',
    create: 'Register',
    save: 'Save',
    cancel: 'Cancel',
    secretRefused:
      'That looks like a credential, not a pointer to one. Send where it lives instead — env:NAME, a vault path, a runbook URL.',

    kindLocal: 'local',
    kindEphemeral: 'ephemeral',
    kindShared: 'shared',
    kindStaging: 'staging',
    kindProduction: 'production',
    kindOther: 'other',
    dsSeeded: 'seeded',
    dsEmpty: 'empty',
    dsProductionLike: 'production-like',
    dsUnknown: 'unknown',
  },
  de: {
    specification: 'Spezifikation',
    board: 'Board',
    epics: "Epics",
    inbox: 'Inbox',
    documents: 'Dokumente',
    initiatives: 'Initiativen',
    mindmaps: 'Mindmaps',
    schedules: 'Zeitpläne',
    verification: 'Verifizierung',
    environments: 'Umgebungen',
    settings: 'Einstellungen',

    gateTokenSub:
      "Ein Token mit 'read'. Zum Anlegen oder Ändern einer Umgebung wird zusätzlich 'write' benötigt.",
    gateLabel: 'API-Token',
    gateOpen: 'Öffnen',
    tokenNeeded: 'Zum Lesen dieses Projekts wird ein Token benötigt.',
    gateNoRead: "Dieses Token kann nicht lesen. Bitte eines mit 'read' verwenden.",
    requestFailed: 'Die Anfrage ist fehlgeschlagen.',
    allProjects: 'Alle Projekte',
    project: 'Projekt',
    projectSearch: 'Projekte suchen',
    projectNoMatch: 'Kein Projekt passt',
    navExpand: 'Ausklappen',
    navCollapse: 'Einklappen',
    navAccount: 'Konto',
    signOut: 'Abmelden',
    refresh: 'Aktualisieren',

    newEnvironment: 'Neue Umgebung',
    needWrite: "Zum Anlegen einer Umgebung wird ein Token mit 'write' benötigt.",
    empty:
      'Noch keine Umgebungen. Eine Umgebung ist der Ort, an dem eine Prüfung läuft — eine URL, wie man sie hochfährt, und ob Schreiben dort sicher ist. Ohne sie ist jedes Urteil eine Behauptung, die niemand reproduzieren kann.',
    emptyHint:
      'Agenten können ihre eigene registrieren: eine kurzlebige Vorschau-Instanz ist genau dieser Fall.',

    showArchived: 'Archivierte anzeigen',
    archived: 'archiviert',
    readOnly: 'nur lesen',
    writable: 'beschreibbar',
    bringUp: 'Hochfahren',
    teardown: 'Zurückgeben',
    credentials: 'Zugangsdaten',
    credentialsNote: 'ein Verweis — Takomo speichert keine Geheimnisse',
    dataState: 'Daten',
    notes: 'Hinweise',
    edit: 'Bearbeiten',
    archive: 'Archivieren',
    unarchive: 'Wiederherstellen',
    confirmArchive:
      'Diese Umgebung archivieren? Dort erteilte Urteile verweisen weiterhin darauf, und sie lässt sich wiederherstellen.',

    fSlug: 'Kürzel',
    fSlugHint:
      'Was ein Agent eingibt. Später nicht änderbar — Prüfungen sprechen Umgebungen darüber an.',
    fName: 'Name',
    fKind: 'Art',
    fBaseUrl: 'Basis-URL',
    fBaseUrlPh: 'https://staging.example.com',
    fBringUp: 'Wie man sie hochfährt',
    fBringUpPh: 'backlot up --ttl 900',
    fBringUpHint:
      'Text oder ein Befehl. Takomo führt ihn nie aus — er wird an den nächsten weitergereicht.',
    fTeardown: 'Wie man sie zurückgibt',
    fTeardownPh: 'backlot release',
    fDataState: 'Was darin ist',
    fWritable: 'Destruktive Fälle dürfen hier laufen',
    fWritableHint:
      'Nur ein Hinweis. Takomo führt nichts aus und kann nichts erzwingen. Bei Produktion standardmäßig aus.',
    fCredentials: 'Wo die Zugangsdaten liegen',
    fCredentialsPh: 'env:STAGING_TOKEN',
    fCredentialsHint:
      'Ein VERWEIS, nie ein Geheimnis: jedes Token mit read sieht dieses Feld.',
    fNotes: 'Vorbehalte',
    fNotesPh: 'Wird um 03:00 UTC neu befüllt; teilt sich die Zahlungs-Sandbox',
    create: 'Anlegen',
    save: 'Speichern',
    cancel: 'Abbrechen',
    secretRefused:
      'Das sieht nach Zugangsdaten aus, nicht nach einem Verweis darauf. Bitte angeben, wo sie liegen — env:NAME, ein Vault-Pfad, eine Runbook-URL.',

    kindLocal: 'lokal',
    kindEphemeral: 'kurzlebig',
    kindShared: 'geteilt',
    kindStaging: 'Staging',
    kindProduction: 'Produktion',
    kindOther: 'sonstige',
    dsSeeded: 'befüllt',
    dsEmpty: 'leer',
    dsProductionLike: 'produktionsnah',
    dsUnknown: 'unbekannt',
  },
})
