// DE/EN strings for /documents.
// EN is the reference shape — a DE table that drifts is a compile error.
import { defineStrings } from '@/lib/i18n'

export const STR = defineStrings({
  en: {
    board: 'Board',
    inbox: 'Inbox',
    documents: 'Documents',
    initiatives: 'Initiatives',
    mindmaps: 'Mindmaps',
    schedules: 'Schedules',
    verification: 'Verification',
    environments: 'Environments',
    settings: 'Settings',

    gateTokenSub: "A token with 'read'. Editing a document additionally needs 'write'.",
    gateLabel: 'API token',
    gateOpen: 'Open',
    tokenNeeded: 'A token is needed to read this project.',
    gateNoRead: "That token cannot read. Use one carrying the 'read' scope.",
    requestFailed: 'The request failed.',
    allProjects: 'All projects',
    project: 'Project',
    projectSearch: 'Search projects',
    projectNoMatch: 'No project matches',
    navExpand: 'Expand',
    navCollapse: 'Collapse',
    navAccount: 'Account',
    signOut: 'Sign out',
    refresh: 'Refresh',

    newDocument: 'New document',
    newDocumentTitle: 'Title',
    newDocumentFolder: 'Folder (optional)',
    create: 'Create',
    cancel: 'Cancel',
    needWrite: "Creating a document needs a token with the 'write' scope.",
    pickProject: 'Pick a project to see its documents.',

    empty:
      'No documents yet. A document is prose you and your agents write at the same time — nobody overwrites anybody, because every change is merged rather than saved.',
    emptyHint: 'Open one in two windows to see what that means.',

    selectPrompt: 'Pick a document on the left, or start a new one.',
    connecting: 'Connecting…',
    connected: 'Live',
    disconnected: 'Reconnecting…',
    readOnlyBanner:
      'Your token can read this document but not change it. Edits you type here are not applied.',
    placeholder: 'Document body',
    alsoHere: 'Also here',
    justYou: 'Just you',

    outlineExpand: 'Open this section',
    outlineCollapse: 'Close this section',
    outlineFolded: '{n} sections inside',
    outlineGroup: 'A folder. No document of this name — open it to see what is filed here.',
    outlineWaiting: '{n} proposals waiting',

    archive: 'Archive',
    unarchive: 'Restore',
    archived: 'archived',
    showArchived: 'Show archived',
    confirmArchive: 'Archive this document? Its text is kept, and you can restore it.',

    status: 'Status',
    statusDraft: 'draft',
    statusReview: 'review',
    statusSettled: 'settled',
    statusArchived: 'archived',

    rename: 'Rename',
    saved: 'Saved',
    historyOne: '1 revision stored',
    historyMany: '{n} revisions stored',

    proposalsHeading: 'Proposed changes',
    proposalsEmpty:
      'Nothing proposed. An agent can suggest changes here — it never writes into the text itself, so every change is one you accept or reject.',
    proposalPending: 'waiting',
    proposalAccepted: 'accepted',
    proposalRejected: 'rejected',
    proposalAccept: 'Accept',
    proposalReject: 'Reject',
    proposalBy: 'from',
    proposalPartial: 'Part of this proposal could not be offered:',
    opReplace: 'replaces',
    opInsert: 'inserts after',
    opDelete: 'deletes',
    proposalNeedWrite: "Deciding needs a token with the 'write' scope.",
    waitingOne: '1 proposal waiting',
    waitingMany: '{n} proposals waiting',

    askHint: 'Ask an agent to change something — it proposes, you decide',
    agentOff: 'No document agent configured on this server (TAKOMO_TENSORX_API_KEY).',
    menuPlaceholder: 'What should change? Or just start typing…',
    menuFreeText: 'Ask exactly this',
    menuScoped: 'this block:',
    menuWhole: 'whole document',
    menuClose: 'Close',
    menuRunning: 'Thinking… the result arrives as a proposal, not as text.',

    sTighten: 'Tighten',
    sSimpler: 'Say it more simply',
    sAsCommitment: 'Phrase as a commitment',
    sAsCommitmentHint: 'A sentence you could check the software against',
    sFindContradiction: 'Does this contradict anything?',
    sFindContradictionHint: 'Marks it as an open question rather than picking a side',
    sAsList: 'Turn into a list',
    sExpandSection: 'Write out this section',
    sSplitSection: 'Split into subsections',
    sAddMissingItems: 'Add missing items',
    sWhatIsMissing: "What's missing here?",
    sWhatIsMissingHint: 'Adds open questions, does not answer them',
    sContradictions: 'Find contradictions',
    sSummarize: 'Summarize at the top',
    sAddHeadings: 'Add headings',
    sAddHeadingsHint: 'Structure only — the text itself is left alone',
  },
  de: {
    board: 'Board',
    inbox: 'Posteingang',
    documents: 'Dokumente',
    initiatives: 'Initiativen',
    mindmaps: 'Mindmaps',
    schedules: 'Zeitpläne',
    verification: 'Nachweis',
    environments: 'Umgebungen',
    settings: 'Einstellungen',

    gateTokenSub: "Ein Token mit 'read'. Zum Bearbeiten zusätzlich 'write'.",
    gateLabel: 'API-Token',
    gateOpen: 'Öffnen',
    tokenNeeded: 'Zum Lesen dieses Projekts wird ein Token gebraucht.',
    gateNoRead: "Dieses Token darf nicht lesen. Es braucht den Scope 'read'.",
    requestFailed: 'Die Anfrage ist fehlgeschlagen.',
    allProjects: 'Alle Projekte',
    project: 'Projekt',
    projectSearch: 'Projekte suchen',
    projectNoMatch: 'Kein Projekt passt',
    navExpand: 'Ausklappen',
    navCollapse: 'Einklappen',
    navAccount: 'Konto',
    signOut: 'Abmelden',
    refresh: 'Neu laden',

    newDocument: 'Neues Dokument',
    newDocumentTitle: 'Titel',
    newDocumentFolder: 'Ordner (optional)',
    create: 'Anlegen',
    cancel: 'Abbrechen',
    needWrite: "Zum Anlegen wird ein Token mit dem Scope 'write' gebraucht.",
    pickProject: 'Projekt wählen, um dessen Dokumente zu sehen.',

    empty:
      'Noch keine Dokumente. Ein Dokument ist Text, den ihr und eure Agenten gleichzeitig schreibt — niemand überschreibt jemanden, weil jede Änderung zusammengeführt statt gespeichert wird.',
    emptyHint: 'Öffne eines in zwei Fenstern, dann sieht man, was das heißt.',

    selectPrompt: 'Links ein Dokument wählen oder ein neues anfangen.',
    connecting: 'Verbinde…',
    connected: 'Live',
    disconnected: 'Verbinde neu…',
    readOnlyBanner:
      'Dein Token darf dieses Dokument lesen, aber nicht ändern. Was du hier tippst, wird nicht übernommen.',
    placeholder: 'Dokumenttext',
    alsoHere: 'Auch hier',
    justYou: 'Nur du',

    outlineExpand: 'Abschnitt aufklappen',
    outlineCollapse: 'Abschnitt zuklappen',
    outlineFolded: '{n} Abschnitte darin',
    outlineGroup: 'Ein Ordner. Kein Dokument dieses Namens — aufklappen zeigt, was darin liegt.',
    outlineWaiting: '{n} Vorschläge offen',

    archive: 'Archivieren',
    unarchive: 'Zurückholen',
    archived: 'archiviert',
    showArchived: 'Archivierte zeigen',
    confirmArchive:
      'Dieses Dokument archivieren? Der Text bleibt erhalten und du kannst es zurückholen.',

    status: 'Status',
    statusDraft: 'Entwurf',
    statusReview: 'in Durchsicht',
    statusSettled: 'festgezurrt',
    statusArchived: 'archiviert',

    rename: 'Umbenennen',
    saved: 'Gesichert',
    historyOne: '1 Fassung gespeichert',
    historyMany: '{n} Fassungen gespeichert',

    proposalsHeading: 'Vorgeschlagene Änderungen',
    proposalsEmpty:
      'Nichts vorgeschlagen. Ein Agent kann hier Änderungen vorschlagen — er schreibt nie selbst in den Text, also ist jede Änderung eine, die du annimmst oder verwirfst.',
    proposalPending: 'offen',
    proposalAccepted: 'angenommen',
    proposalRejected: 'verworfen',
    proposalAccept: 'Annehmen',
    proposalReject: 'Verwerfen',
    proposalBy: 'von',
    proposalPartial: 'Ein Teil dieses Vorschlags konnte nicht angeboten werden:',
    opReplace: 'ersetzt',
    opInsert: 'fügt ein nach',
    opDelete: 'löscht',
    proposalNeedWrite: "Zum Entscheiden wird ein Token mit dem Scope 'write' gebraucht.",
    waitingOne: '1 Vorschlag offen',
    waitingMany: '{n} Vorschläge offen',

    askHint: 'Einen Agenten um eine Änderung bitten — er schlägt vor, du entscheidest',
    agentOff: 'Auf diesem Server ist kein Dokument-Agent konfiguriert (TAKOMO_TENSORX_API_KEY).',
    menuPlaceholder: 'Was soll sich ändern? Oder einfach lostippen…',
    menuFreeText: 'Genau das fragen',
    menuScoped: 'dieser Block:',
    menuWhole: 'ganzes Dokument',
    menuClose: 'Schließen',
    menuRunning: 'Denkt nach… das Ergebnis kommt als Vorschlag, nicht als Text.',

    sTighten: 'Kürzen',
    sSimpler: 'Einfacher formulieren',
    sAsCommitment: 'Als Zusage formulieren',
    sAsCommitmentHint: 'Ein Satz, bei dem man nachschauen kann, ob die Software sich so verhält',
    sFindContradiction: 'Widerspricht das etwas?',
    sFindContradictionHint: 'Markiert es als offene Frage, statt eine Seite zu wählen',
    sAsList: 'In eine Liste verwandeln',
    sExpandSection: 'Abschnitt ausformulieren',
    sSplitSection: 'In Unterabschnitte teilen',
    sAddMissingItems: 'Fehlende Punkte ergänzen',
    sWhatIsMissing: 'Was fehlt hier?',
    sWhatIsMissingHint: 'Schreibt offene Fragen, beantwortet sie nicht',
    sContradictions: 'Widersprüche suchen',
    sSummarize: 'Zusammenfassung an den Anfang',
    sAddHeadings: 'Überschriften ergänzen',
    sAddHeadingsHint: 'Nur Gliederung — der Text selbst bleibt',
  },
})
