// DE/EN strings for /documents — the plan, written out.
// EN is the reference shape — a DE table that drifts is a compile error.
import { defineStrings } from '@/lib/i18n'

export const STR = defineStrings({
  en: {
    specification: 'Specification',
    viewMap: 'Map',
    viewDocument: 'Document',
    viewTests: 'Tests',
    outline: 'Outline',
    board: 'Board',
    inbox: 'Inbox',
    documents: 'Documents',
    initiatives: 'Initiatives',
    mindmaps: 'Mindmaps',
    schedules: 'Schedules',
    verification: 'Verification',
    environments: 'Environments',
    settings: 'Settings',

    gateTokenSub: "A token with 'read'. Writing a section additionally needs 'write'.",
    gateLabel: 'API token',
    gateOpen: 'Open',
    tokenNeeded: 'A token is needed to read this project.',
    gateNoRead: "That token cannot read. Use one carrying the 'read' scope.",
    requestFailed: 'The request failed.',
    allProjects: 'All projects',
    project: 'Project',
    projectSearch: 'Search projects',
    projectNoMatch: 'No project matches',
    navExpand: 'Expand',
    navCollapse: 'Collapse',
    navAccount: 'Account',
    signOut: 'Sign out',
    refresh: 'Refresh',

    pickProject: 'Pick a project to read its plan.',
    noPlan: 'This project has no plan yet.',
    noPlanHint:
      'A plan starts on the map, where thoughts are grown and grouped. Every thought there is a section here.',
    openMap: 'Open the map',

    connecting: 'Connecting…',
    connected: 'Live',
    disconnected: 'Reconnecting…',
    alsoHere: 'Also here',
    justYou: 'Just you',
    readOnlyBanner:
      'Your token can read this plan but not change it. What you type here is not applied.',
    needWrite: "This needs a token with the 'write' scope.",

    empty: 'The plan is empty.',
    emptyHint: 'Add a thought on the map and it appears here as section 1.',
    proseEmpty: 'Nothing written here yet.',
    proseLabel: 'Section {n}',
    untitled: 'Untitled section',

    outlineExpand: 'Open this section',
    outlineCollapse: 'Close this section',
    outlineFolded: '{n} sections inside',

    standingConfirmed: 'agreed',
    standingChanged: 'changed since',
    standingUnseen: 'unread',

    review: 'I have read this',
    reviewHint: 'Records that you agree with this section as it now reads',
    showOnMap: 'Show it on the map',
    history: 'History',
    hideHistory: 'Hide history',
    historyEmpty: 'Nothing recorded for this section yet.',
    historyMore: '{n} older entries',

    proposals: 'Proposals',
    hideProposals: 'Hide proposals',
    pendingBadge: '{n} waiting',
    railPending: '{n} proposals waiting for a decision',
    proposalsHeading: 'What an agent offers here',
    proposalsEmpty: 'Nothing has been offered for this section.',
    proposalPending: 'undecided',
    proposalAccepted: 'accepted',
    proposalRejected: 'rejected',
    accept: 'Accept',
    reject: 'Reject',
    proposalBy: 'from',
    proposalPartial: 'The server dropped part of this before you saw it:',
    opReplace: 'rewrites',
    opInsert: 'adds after',
    opDelete: 'removes',
    proposalReadOnly: 'Deciding needs a token that may change the plan.',
    applySkipped: '{n} of these changes no longer fit the section and were left out:',

    kindAuthored: 'written',
    kindRenamed: 'renamed',
    kindEdited: 'edited',
    kindMoved: 'moved',
    kindPruned: 'removed',
    kindReviewed: 'read',
    kindProposed: 'proposed',
    kindAccepted: 'accepted',
    kindRejected: 'rejected',
  },
  de: {
    specification: 'Spezifikation',
    viewMap: 'Karte',
    viewDocument: 'Dokument',
    viewTests: 'Tests',
    outline: 'Gliederung',
    board: 'Board',
    inbox: 'Posteingang',
    documents: 'Dokumente',
    initiatives: 'Initiativen',
    mindmaps: 'Mindmaps',
    schedules: 'Zeitpläne',
    verification: 'Nachweis',
    environments: 'Umgebungen',
    settings: 'Einstellungen',

    gateTokenSub: "Ein Token mit 'read'. Zum Schreiben eines Abschnitts zusätzlich 'write'.",
    gateLabel: 'API-Token',
    gateOpen: 'Öffnen',
    tokenNeeded: 'Zum Lesen dieses Projekts wird ein Token gebraucht.',
    gateNoRead: "Dieses Token darf nicht lesen. Es braucht den Scope 'read'.",
    requestFailed: 'Die Anfrage ist fehlgeschlagen.',
    allProjects: 'Alle Projekte',
    project: 'Projekt',
    projectSearch: 'Projekte suchen',
    projectNoMatch: 'Kein Projekt passt',
    navExpand: 'Ausklappen',
    navCollapse: 'Einklappen',
    navAccount: 'Konto',
    signOut: 'Abmelden',
    refresh: 'Neu laden',

    pickProject: 'Projekt wählen, um dessen Plan zu lesen.',
    noPlan: 'Dieses Projekt hat noch keinen Plan.',
    noPlanHint:
      'Ein Plan beginnt auf der Map, wo Gedanken wachsen und gruppiert werden. Jeder Gedanke dort ist hier ein Abschnitt.',
    openMap: 'Map öffnen',

    connecting: 'Verbinde…',
    connected: 'Live',
    disconnected: 'Verbinde neu…',
    alsoHere: 'Auch hier',
    justYou: 'Nur du',
    readOnlyBanner:
      'Dein Token darf diesen Plan lesen, aber nicht ändern. Was du hier tippst, wird nicht übernommen.',
    needWrite: "Dafür wird ein Token mit dem Scope 'write' gebraucht.",

    empty: 'Der Plan ist leer.',
    emptyHint: 'Leg auf der Map einen Gedanken an, dann steht er hier als Abschnitt 1.',
    proseEmpty: 'Hier steht noch nichts.',
    proseLabel: 'Abschnitt {n}',
    untitled: 'Abschnitt ohne Titel',

    outlineExpand: 'Abschnitt aufklappen',
    outlineCollapse: 'Abschnitt zuklappen',
    outlineFolded: '{n} Abschnitte darin',

    standingConfirmed: 'bestätigt',
    standingChanged: 'seitdem geändert',
    standingUnseen: 'ungelesen',

    review: 'Habe ich gelesen',
    reviewHint: 'Hält fest, dass du diesem Abschnitt so wie er dasteht zustimmst',
    showOnMap: 'Auf der Map zeigen',
    history: 'Verlauf',
    hideHistory: 'Verlauf ausblenden',
    historyEmpty: 'Für diesen Abschnitt ist noch nichts festgehalten.',
    historyMore: '{n} ältere Einträge',

    proposals: 'Vorschläge',
    hideProposals: 'Vorschläge ausblenden',
    pendingBadge: '{n} offen',
    railPending: '{n} Vorschläge warten auf eine Entscheidung',
    proposalsHeading: 'Was ein Agent hier vorschlägt',
    proposalsEmpty: 'Für diesen Abschnitt wurde noch nichts vorgeschlagen.',
    proposalPending: 'offen',
    proposalAccepted: 'angenommen',
    proposalRejected: 'verworfen',
    accept: 'Annehmen',
    reject: 'Verwerfen',
    proposalBy: 'von',
    proposalPartial: 'Der Server hat einen Teil davon schon vorher verworfen:',
    opReplace: 'ersetzt',
    opInsert: 'ergänzt nach',
    opDelete: 'entfernt',
    proposalReadOnly: 'Zum Entscheiden braucht es ein Token, das den Plan ändern darf.',
    applySkipped: '{n} dieser Änderungen passen nicht mehr zum Abschnitt und blieben aus:',

    kindAuthored: 'geschrieben',
    kindRenamed: 'umbenannt',
    kindEdited: 'bearbeitet',
    kindMoved: 'verschoben',
    kindPruned: 'entfernt',
    kindReviewed: 'gelesen',
    kindProposed: 'vorgeschlagen',
    kindAccepted: 'angenommen',
    kindRejected: 'verworfen',
  },
})
