// DE/EN strings for /initiatives, ported verbatim from src/initiatives.html.
//
// `defineStrings` makes EN the reference shape: a DE table missing a key — or
// carrying one EN does not have — is a COMPILE error. The page it replaces
// relied on a Rust test that parsed the HTML and compared key sets, and that
// test enumerated the pages by hand.
import { defineStrings } from '@/lib/i18n'

export const STR = defineStrings({
  en: {
    initiatives: 'Initiatives',
    schedules: 'Schedules',
    board: 'Board',
    inbox: 'Inbox',
    settings: 'Settings',
    gateTokenSub: "A token with 'read' and 'write' — initiatives are read and fed here.",
    gateLabel: 'API token',
    gateOpen: 'Open',
    allProjects: 'All projects',
    newInitiative: 'New initiative',
    newSub:
      'An idea that is not yet work. A title and a sentence are enough — everything else grows through entries.',
    fTitle: 'Title',
    fTitlePh: 'What is the idea called?',
    fSummary: 'Short description',
    fSummaryPh: 'One or two sentences.',
    fLabels: 'Labels',
    fLabelsPh: 'comma-separated',
    fTags: 'Tags',
    fTagsPh: 'person:ada, component:billing',
    create: 'Create',
    cancel: 'Cancel',
    statusOpen: 'Open',
    statusParked: 'Parked',
    statusDistilled: 'Distilled',
    all: 'All',
    searchPh: 'Search title and summary',
    rEntries: 'Entries',
    rAttachments: 'Attachments',
    rChars: 'Characters',
    rSize: 'Size',
    rLast: 'Last entry',
    entriesHdr: 'Collection',
    addEntryHdr: 'Add an entry',
    eKind: 'Kind',
    eKindHint: 'note, research, feedback, transcript, document …',
    eSource: 'Source',
    eSourceHint: 'Required — where did this come from? agent:w1, person:ada, claude:chat',
    eSourceUri: 'Link',
    eSourceUriPh: 'https://… (optional)',
    eTitle: 'Heading',
    eTitlePh: 'optional',
    eText: 'Text',
    eTextPh: 'Markdown. A note, a finding, feedback …',
    eOrigin: 'Written at',
    eOriginHint: 'optional — when the content is older than now',
    attach: 'Attach a file',
    attachClear: 'remove',
    append: 'Append',
    appending: 'Appending …',
    appended: 'Entry appended.',
    created: 'Initiative created.',
    savedTitle: 'Title saved.',
    savedSummary: 'Summary saved.',
    savedStatus: 'Status saved.',
    download: 'Download',
    aStatus: 'Status of this initiative',
    aAttach: 'Attach a document to this entry',
    loadMore: 'Load more',
    by: 'by',
    wrote: 'written',
    noneSelected: 'No initiative selected',
    noneSelectedHint: 'Pick one on the left — or start a new one.',
    emptyList: 'No initiatives yet',
    emptyListHint: 'An idea that is not yet work belongs here. Agents keep feeding it over MCP.',
    emptyEntries: 'No entries yet',
    emptyEntriesHint:
      'The first entry can be a note — or the document that started the idea.',
    needProject: 'Pick a project above to create an initiative.',
    needTitle: 'A title is required.',
    needSource: 'A source is required — it is what makes the entry weighable later.',
    needBody: 'Text or an attachment — one of the two has to be there.',
    tokenNeeded: 'Enter a token.',
    writeNeeded: "This token can only read. Writing needs the 'write' scope.",
    refresh: 'Refresh',
    signOut: 'Sign out',
    navExpand: 'Expand navigation',
    navCollapse: 'Collapse navigation',
    navAccount: 'Account',
    projectSearch: 'Search projects',
    projectNoMatch: 'No project matches “{q}”',
    project: 'project',
    requestFailed: 'Request failed',
    fileUnreadable: 'Could not read the file',
    dismiss: 'Dismiss',
  },
  de: {
    initiatives: 'Initiativen',
    schedules: 'Zeitpläne',
    board: 'Board',
    inbox: 'Inbox',
    settings: 'Einstellungen',
    gateTokenSub:
      "Token mit 'read' und 'write' — Initiativen werden hier gelesen und gefüttert.",
    gateLabel: 'API-Token',
    gateOpen: 'Öffnen',
    allProjects: 'Alle Projekte',
    newInitiative: 'Neue Initiative',
    newSub:
      'Eine Idee, die noch keine Arbeit ist. Titel und ein Satz reichen — alles andere wächst über Einträge.',
    fTitle: 'Titel',
    fTitlePh: 'Wie heißt die Idee?',
    fSummary: 'Kurzbeschreibung',
    fSummaryPh: 'In einem oder zwei Sätzen.',
    fLabels: 'Labels',
    fLabelsPh: 'komma-getrennt',
    fTags: 'Tags',
    fTagsPh: 'person:ada, component:billing',
    create: 'Anlegen',
    cancel: 'Abbrechen',
    statusOpen: 'Offen',
    statusParked: 'Geparkt',
    statusDistilled: 'Destilliert',
    all: 'Alle',
    searchPh: 'Titel und Kurzbeschreibung durchsuchen',
    rEntries: 'Einträge',
    rAttachments: 'Anhänge',
    rChars: 'Zeichen',
    rSize: 'Größe',
    rLast: 'Letzter Eintrag',
    entriesHdr: 'Sammlung',
    addEntryHdr: 'Eintrag hinzufügen',
    eKind: 'Art',
    eKindHint: 'note, research, feedback, transcript, document …',
    eSource: 'Quelle',
    eSourceHint: 'Pflicht — woher kommt das? agent:w1, person:ada, claude:chat',
    eSourceUri: 'Link',
    eSourceUriPh: 'https://… (optional)',
    eTitle: 'Überschrift',
    eTitlePh: 'optional',
    eText: 'Text',
    eTextPh: 'Markdown. Notiz, Ergebnis, Feedback …',
    eOrigin: 'Verfasst am',
    eOriginHint: 'optional — wenn der Inhalt älter ist als jetzt',
    attach: 'Datei anhängen',
    attachClear: 'entfernen',
    append: 'Anhängen',
    appending: 'Wird angehängt …',
    appended: 'Eintrag angehängt.',
    created: 'Initiative angelegt.',
    savedTitle: 'Titel gespeichert.',
    savedSummary: 'Kurzbeschreibung gespeichert.',
    savedStatus: 'Status gespeichert.',
    download: 'Herunterladen',
    aStatus: 'Status dieser Initiative',
    aAttach: 'Dokument an diesen Eintrag anhängen',
    loadMore: 'Mehr laden',
    by: 'von',
    wrote: 'verfasst',
    noneSelected: 'Keine Initiative ausgewählt',
    noneSelectedHint: 'Links eine auswählen — oder eine neue anlegen.',
    emptyList: 'Noch keine Initiativen',
    emptyListHint:
      'Eine Idee, die noch keine Arbeit ist, gehört hierher. Über MCP füttern Agenten sie weiter.',
    emptyEntries: 'Noch keine Einträge',
    emptyEntriesHint:
      'Der erste Eintrag kann eine Notiz sein — oder das Dokument, das die Idee ausgelöst hat.',
    needProject: 'Wähle oben ein Projekt, um eine Initiative anzulegen.',
    needTitle: 'Ein Titel ist nötig.',
    needSource: 'Eine Quelle ist nötig — sie macht den Eintrag später gewichtbar.',
    needBody: 'Text oder Anhang — eines von beiden muss da sein.',
    tokenNeeded: 'Token eingeben.',
    writeNeeded: "Dieses Token darf nur lesen. Schreiben braucht den 'write'-Scope.",
    refresh: 'Aktualisieren',
    signOut: 'Abmelden',
    navExpand: 'Navigation ausklappen',
    navCollapse: 'Navigation einklappen',
    navAccount: 'Konto',
    projectSearch: 'Projekte suchen',
    projectNoMatch: 'Kein Projekt passt zu „{q}“',
    project: 'Projekt',
    requestFailed: 'Anfrage fehlgeschlagen',
    fileUnreadable: 'Datei konnte nicht gelesen werden',
    dismiss: 'Schließen',
  },
})

export type Strings = (typeof STR)['en']
