// DE/EN strings for /initiatives, ported verbatim from src/initiatives.html.
//
// `defineStrings` makes EN the reference shape: a DE table missing a key — or
// carrying one EN does not have — is a COMPILE error. The page it replaces
// relied on a Rust test that parsed the HTML and compared key sets, and that
// test enumerated the pages by hand.
import { defineStrings } from '@/lib/i18n'

export const STR = defineStrings({
  en: {
    initiatives: 'Initiatives',
    schedules: 'Schedules',
    verification: 'Verification',
    environments: 'Environments',
    board: 'Board',
    inbox: 'Inbox',
    settings: 'Settings',
    gateTokenSub: "A token with 'read' and 'write' — initiatives are read and fed here.",
    gateLabel: 'API token',
    gateOpen: 'Open',
    allProjects: 'All projects',
    newInitiative: 'New initiative',
    newSub:
      'An idea that is not yet work. A title and a sentence are enough — everything else grows through entries.',
    fTitle: 'Title',
    fTitlePh: 'What is the idea called?',
    fSummary: 'Short description',
    fSummaryPh: 'One or two sentences.',
    fLabels: 'Labels',
    fLabelsPh: 'comma-separated',
    fTags: 'Tags',
    fTagsPh: 'person:ada, component:billing',
    create: 'Create',
    cancel: 'Cancel',
    statusOpen: 'Open',
    statusParked: 'Parked',
    statusDistilled: 'Distilled',
    all: 'All',
    searchPh: 'Search title and summary',
    rEntries: 'Entries',
    rAttachments: 'Attachments',
    rChars: 'Characters',
    rSize: 'Size',
    rLast: 'Last entry',
    vHeading: 'Versions',
    vDone: 'done',
    vReady: 'ready',
    vBacklog: 'backlog',
    vAwaiting: 'awaiting an answer',
    vEmpty: 'No versions filed yet.',
    vEmptyHint: 'File work under this lane by tagging a ticket or epic with this initiative.',
    vParkedWithReadyWork: 'Parked, but work is still being handed out',
    entriesHdr: 'Collection',
    addEntryHdr: 'Add an entry',
    paneBusiness: 'Business',
    paneTechnical: 'Technical',
    paneVerification: 'Verification',
    paneLog: 'Log',
    paneUnwritten: 'This view has not been written',
    paneUnwrittenHint:
      "An agent writes a pane by appending a 'view' entry carrying meta.pane — until then there is only the log.",
    uncited: 'no source',
    citeHint:
      'Click a numbered mark to see where that sentence came from — the entry, who produced it, when it was written and when it landed.',
    lineageHdr: 'Lineage',
    landed: 'landed',
    threadOpen: 'open',
    threadRunning: 'running',
    threadResolved: 'resolved',
    aCitation: 'Source',
    originHdr: 'How it came in',
    amendHdr: 'Proposed amendment',
    amendBy: 'proposed by',
    accept: 'Accept',
    reject: 'Reject',
    working: 'Working …',
    diffSame: 'unchanged',
    diffChanged: 'changed',
    diffAdded: 'added',
    diffRemoved: 'removed',
    diffWas: 'was:',
    accepted: 'Amendment accepted — this view is now live.',
    acceptedNote: 'Accepted the proposed amendment.',
    rejected: 'Amendment rejected. The view is unchanged.',
    rejectedNote: 'Rejected the proposed amendment.',
    dispatch: 'Send an agent',
    dispatching: 'Filing …',
    dispatched: 'Ticket filed:',
    dispatchFallbackTitle: 'Follow up on an initiative note',
    threadTicket: 'ticket',
    eKind: 'Kind',
    eKindHint: 'note, research, feedback, transcript, document …',
    eSource: 'Source',
    eSourceHint: 'Required — where did this come from? agent:w1, person:ada, claude:chat',
    eSourceUri: 'Link',
    eSourceUriPh: 'https://… (optional)',
    eTitle: 'Heading',
    eTitlePh: 'optional',
    eText: 'Text',
    eTextPh: 'Markdown. A note, a finding, feedback …',
    eOrigin: 'Written at',
    eOriginHint: 'optional — when the content is older than now',
    attach: 'Attach a file',
    attachClear: 'remove',
    append: 'Append',
    appending: 'Appending …',
    appended: 'Entry appended.',
    created: 'Initiative created.',
    savedTitle: 'Title saved.',
    savedSummary: 'Summary saved.',
    savedStatus: 'Status saved.',
    download: 'Download',
    aStatus: 'Status of this initiative',
    aAttach: 'Attach a document to this entry',
    loadMore: 'Load more',
    by: 'by',
    wrote: 'written',
    noneSelected: 'No initiative selected',
    noneSelectedHint: 'Pick one on the left — or start a new one.',
    emptyList: 'No initiatives yet',
    emptyListHint: 'An idea that is not yet work belongs here. Agents keep feeding it over MCP.',
    emptyEntries: 'No entries yet',
    emptyEntriesHint:
      'The first entry can be a note — or the document that started the idea.',
    needProject: 'Pick a project above to create an initiative.',
    needTitle: 'A title is required.',
    needSource: 'A source is required — it is what makes the entry weighable later.',
    needBody: 'Text or an attachment — one of the two has to be there.',
    tokenNeeded: 'Enter a token.',
    writeNeeded: "This token can only read. Writing needs the 'write' scope.",
    refresh: 'Refresh',
    signOut: 'Sign out',
    navExpand: 'Expand navigation',
    navCollapse: 'Collapse navigation',
    navAccount: 'Account',
    projectSearch: 'Search projects',
    projectNoMatch: 'No project matches “{q}”',
    project: 'project',
    requestFailed: 'Request failed',
    fileUnreadable: 'Could not read the file',
    dismiss: 'Dismiss',

    // ---- the explorer and the document surface ----
    explorerEmpty: 'No documents yet',
    explorerEmptyHint: 'Create one, or let an agent open it over MCP.',
    explorerToggle: 'Toggle folder',
    explorerUnfiled: 'Unfiled',
    explorerFilterPh: 'Filter documents',
    explorerWaitingNote: '1 open note',
    explorerWaitingNotes: '{n} open notes',
    explorerWaitingAmendment: '1 suggested change awaiting a decision',
    explorerWaitingAmendments: '{n} suggested changes awaiting a decision',
    explorerWaitingOnly: 'Waiting',
    folder: 'Folder',
    folderPh: 'product/billing',
    folderSaved: 'Moved',
    folderNone: 'Not in a folder',
    orphanHeading: 'Notes that lost their words',
    orphanHint: 'The prose these were written against has been rewritten.',
    suggestionMark: 'Suggested change',

    // ---- the selection pane ----
    selIdle: 'Nothing selected',
    selIdleHint: 'Highlight any passage to comment on it, suggest a change, file it as work, ask a person, or attach a source.',
    selHeading: 'Selected passage',
    opComment: 'Comment',
    opSuggest: 'Suggest edit',
    opTicket: 'Make a ticket',
    opAsk: 'Ask a person',
    opAskWho: 'Ask',
    opAskAnyone: 'Anyone with the expertise',
    opCite: 'Attach a source',
    opCommentPh: 'What is worth saying about this passage?',
    opSuggestPh: 'The words you would put here instead.',
    opTicketPh: 'What should be done about it?',
    opAskPh: 'What do you need decided?',
    opCitePh: 'Choose the evidence that backs it…',
    opSubmit: 'Record',
    openNotes: 'Open notes',
    pendingSuggestions: 'Suggested changes',
    noteBy: 'by',
    resolve: 'Mark resolved',
    orphanWarning: 'These words are no longer in the document.',
    ticketMade: 'ticket',
    replaces: 'Replaces',
    replacesWith: 'With',
    noEvidence: 'Nothing to cite yet — append research, a transcript or a document first.',

    // ---- what each operation records ----
    commented: 'Note recorded',
    suggested: 'Suggestion recorded',
    cited: 'Source attached',
    asked: 'Question routed to the inbox',
    orphanRefused: 'That passage has changed; the suggestion cannot be applied.',
    docEmptyForOp: 'Write a pane first — there is no prose to attach this to.',

    // ---- writing a pane ----
    writePane: 'Write',
    revisePane: 'Revise',
    paneEditorHint:
      'Blank line between paragraphs. A [1] mark cites the first source below — the reader sees a different number, assigned across the whole document.',
    paneCites: 'What this pane cites',
    paneCitesHint: 'Use these numbers in the text.',
    paneNoCites: 'Nothing cited yet. Highlight a passage and attach a source to add one.',
    paneSave: 'Save',
    paneSaved: 'Saved — the earlier wording is still in the log.',
  },
  de: {
    initiatives: 'Initiativen',
    schedules: 'Zeitpläne',
    verification: 'Verifizierung',
    environments: 'Umgebungen',
    board: 'Board',
    inbox: 'Inbox',
    settings: 'Einstellungen',
    gateTokenSub:
      "Token mit 'read' und 'write' — Initiativen werden hier gelesen und gefüttert.",
    gateLabel: 'API-Token',
    gateOpen: 'Öffnen',
    allProjects: 'Alle Projekte',
    newInitiative: 'Neue Initiative',
    newSub:
      'Eine Idee, die noch keine Arbeit ist. Titel und ein Satz reichen — alles andere wächst über Einträge.',
    fTitle: 'Titel',
    fTitlePh: 'Wie heißt die Idee?',
    fSummary: 'Kurzbeschreibung',
    fSummaryPh: 'In einem oder zwei Sätzen.',
    fLabels: 'Labels',
    fLabelsPh: 'komma-getrennt',
    fTags: 'Tags',
    fTagsPh: 'person:ada, component:billing',
    create: 'Anlegen',
    cancel: 'Abbrechen',
    statusOpen: 'Offen',
    statusParked: 'Geparkt',
    statusDistilled: 'Destilliert',
    all: 'Alle',
    searchPh: 'Titel und Kurzbeschreibung durchsuchen',
    rEntries: 'Einträge',
    rAttachments: 'Anhänge',
    rChars: 'Zeichen',
    rSize: 'Größe',
    rLast: 'Letzter Eintrag',
    vHeading: 'Versionen',
    vDone: 'fertig',
    vReady: 'bereit',
    vBacklog: 'wartend',
    vAwaiting: 'Antwort offen',
    vEmpty: 'Noch keine Versionen angelegt.',
    vEmptyHint:
      'Arbeit gehört zu dieser Spur, indem ein Ticket oder Epic mit dieser Initiative getaggt wird.',
    vParkedWithReadyWork: 'Zurückgestellt, aber Arbeit wird weiter ausgegeben',
    entriesHdr: 'Sammlung',
    addEntryHdr: 'Eintrag hinzufügen',
    paneBusiness: 'Fachlich',
    paneTechnical: 'Technisch',
    paneVerification: 'Absicherung',
    paneLog: 'Verlauf',
    paneUnwritten: 'Diese Sicht wurde noch nicht geschrieben',
    paneUnwrittenHint:
      "Ein Agent schreibt eine Sicht, indem er einen 'view'-Eintrag mit meta.pane anhängt — bis dahin gibt es nur den Verlauf.",
    uncited: 'ohne Quelle',
    citeHint:
      'Auf eine nummerierte Marke klicken, um zu sehen, woher der Satz stammt — der Eintrag, wer ihn erzeugt hat, wann er verfasst wurde und wann er hier ankam.',
    lineageHdr: 'Herkunft',
    landed: 'angekommen',
    threadOpen: 'offen',
    threadRunning: 'läuft',
    threadResolved: 'erledigt',
    aCitation: 'Quelle',
    originHdr: 'Wie es hereinkam',
    amendHdr: 'Vorgeschlagene Änderung',
    amendBy: 'vorgeschlagen von',
    accept: 'Übernehmen',
    reject: 'Ablehnen',
    working: 'Wird ausgeführt …',
    diffSame: 'unverändert',
    diffChanged: 'geändert',
    diffAdded: 'neu',
    diffRemoved: 'entfernt',
    diffWas: 'vorher:',
    accepted: 'Änderung übernommen — diese Sicht ist jetzt aktiv.',
    acceptedNote: 'Vorgeschlagene Änderung übernommen.',
    rejected: 'Änderung abgelehnt. Die Sicht bleibt unverändert.',
    rejectedNote: 'Vorgeschlagene Änderung abgelehnt.',
    dispatch: 'Agent beauftragen',
    dispatching: 'Wird angelegt …',
    dispatched: 'Ticket angelegt:',
    dispatchFallbackTitle: 'Notiz aus einer Initiative weiterverfolgen',
    threadTicket: 'Ticket',
    eKind: 'Art',
    eKindHint: 'note, research, feedback, transcript, document …',
    eSource: 'Quelle',
    eSourceHint: 'Pflicht — woher kommt das? agent:w1, person:ada, claude:chat',
    eSourceUri: 'Link',
    eSourceUriPh: 'https://… (optional)',
    eTitle: 'Überschrift',
    eTitlePh: 'optional',
    eText: 'Text',
    eTextPh: 'Markdown. Notiz, Ergebnis, Feedback …',
    eOrigin: 'Verfasst am',
    eOriginHint: 'optional — wenn der Inhalt älter ist als jetzt',
    attach: 'Datei anhängen',
    attachClear: 'entfernen',
    append: 'Anhängen',
    appending: 'Wird angehängt …',
    appended: 'Eintrag angehängt.',
    created: 'Initiative angelegt.',
    savedTitle: 'Titel gespeichert.',
    savedSummary: 'Kurzbeschreibung gespeichert.',
    savedStatus: 'Status gespeichert.',
    download: 'Herunterladen',
    aStatus: 'Status dieser Initiative',
    aAttach: 'Dokument an diesen Eintrag anhängen',
    loadMore: 'Mehr laden',
    by: 'von',
    wrote: 'verfasst',
    noneSelected: 'Keine Initiative ausgewählt',
    noneSelectedHint: 'Links eine auswählen — oder eine neue anlegen.',
    emptyList: 'Noch keine Initiativen',
    emptyListHint:
      'Eine Idee, die noch keine Arbeit ist, gehört hierher. Über MCP füttern Agenten sie weiter.',
    emptyEntries: 'Noch keine Einträge',
    emptyEntriesHint:
      'Der erste Eintrag kann eine Notiz sein — oder das Dokument, das die Idee ausgelöst hat.',
    needProject: 'Wähle oben ein Projekt, um eine Initiative anzulegen.',
    needTitle: 'Ein Titel ist nötig.',
    needSource: 'Eine Quelle ist nötig — sie macht den Eintrag später gewichtbar.',
    needBody: 'Text oder Anhang — eines von beiden muss da sein.',
    tokenNeeded: 'Token eingeben.',
    writeNeeded: "Dieses Token darf nur lesen. Schreiben braucht den 'write'-Scope.",
    refresh: 'Aktualisieren',
    signOut: 'Abmelden',
    navExpand: 'Navigation ausklappen',
    navCollapse: 'Navigation einklappen',
    navAccount: 'Konto',
    projectSearch: 'Projekte suchen',
    projectNoMatch: 'Kein Projekt passt zu „{q}“',
    project: 'Projekt',
    requestFailed: 'Anfrage fehlgeschlagen',
    fileUnreadable: 'Datei konnte nicht gelesen werden',
    dismiss: 'Schließen',

    explorerEmpty: 'Noch keine Dokumente',
    explorerEmptyHint: 'Lege eines an, oder lass es einen Agenten über MCP eröffnen.',
    explorerToggle: 'Ordner auf- oder zuklappen',
    explorerUnfiled: 'Ohne Ordner',
    explorerFilterPh: 'Dokumente filtern',
    explorerWaitingNote: '1 offene Anmerkung',
    explorerWaitingNotes: '{n} offene Anmerkungen',
    explorerWaitingAmendment: '1 Änderungsvorschlag wartet auf eine Entscheidung',
    explorerWaitingAmendments: '{n} Änderungsvorschläge warten auf eine Entscheidung',
    explorerWaitingOnly: 'Wartend',
    folder: 'Ordner',
    folderPh: 'produkt/abrechnung',
    folderSaved: 'Verschoben',
    folderNone: 'In keinem Ordner',
    orphanHeading: 'Notizen ohne Textstelle',
    orphanHint: 'Der Text, zu dem sie geschrieben wurden, ist überarbeitet worden.',
    suggestionMark: 'Änderungsvorschlag',

    selIdle: 'Nichts ausgewählt',
    selIdleHint: 'Markiere eine Stelle, um sie zu kommentieren, eine Änderung vorzuschlagen, sie als Arbeit anzulegen, jemanden zu fragen oder eine Quelle anzuhängen.',
    selHeading: 'Markierte Stelle',
    opComment: 'Kommentieren',
    opSuggest: 'Änderung vorschlagen',
    opTicket: 'Ticket anlegen',
    opAsk: 'Person fragen',
    opAskWho: 'Fragen',
    opAskAnyone: 'Jede Person mit der Expertise',
    opCite: 'Quelle anhängen',
    opCommentPh: 'Was ist zu dieser Stelle zu sagen?',
    opSuggestPh: 'Die Worte, die hier stattdessen stehen sollen.',
    opTicketPh: 'Was soll damit geschehen?',
    opAskPh: 'Was soll entschieden werden?',
    opCitePh: 'Belegende Quelle auswählen…',
    opSubmit: 'Festhalten',
    openNotes: 'Offene Notizen',
    pendingSuggestions: 'Änderungsvorschläge',
    noteBy: 'von',
    resolve: 'Als erledigt markieren',
    orphanWarning: 'Diese Worte stehen nicht mehr im Dokument.',
    ticketMade: 'Ticket',
    replaces: 'Ersetzt',
    replacesWith: 'Durch',
    noEvidence: 'Noch nichts zum Zitieren — hänge zuerst Recherche, ein Transkript oder ein Dokument an.',

    commented: 'Notiz festgehalten',
    suggested: 'Vorschlag festgehalten',
    cited: 'Quelle angehängt',
    asked: 'Frage an den Posteingang geleitet',
    orphanRefused: 'Diese Stelle hat sich geändert; der Vorschlag lässt sich nicht anwenden.',
    docEmptyForOp: 'Schreibe zuerst einen Abschnitt — es gibt noch keinen Text dafür.',

    writePane: 'Schreiben',
    revisePane: 'Überarbeiten',
    paneEditorHint:
      'Leerzeile zwischen Absätzen. Eine [1]-Marke zitiert die erste Quelle unten — Lesende sehen eine andere Nummer, die über das ganze Dokument vergeben wird.',
    paneCites: 'Was dieser Abschnitt zitiert',
    paneCitesHint: 'Verwende diese Nummern im Text.',
    paneNoCites: 'Noch nichts zitiert. Markiere eine Stelle und hänge eine Quelle an.',
    paneSave: 'Speichern',
    paneSaved: 'Gespeichert — der frühere Wortlaut steht weiterhin im Verlauf.',
  },
})

export type Strings = (typeof STR)['en']
