import { defineStrings } from '@/lib/i18n'
export const STR = defineStrings({
  en: {
    assignee: 'Claimed by', anyState: 'Any ticket status', anyAssignee: 'Any claim holder', noResearch: 'Not researched', title: 'Bugs', loading: 'Loading…', projectNeeded: 'Select a project to review its bugs.', description: 'Every bug is a ticket. Research starts only when you request it.',
    reportRequired: 'Add a title and describe the problem in Description or Actual behavior.', researchInput: 'Research input', originalRequest: 'Original request', reportSnapshot: 'Bug report at request time', report: 'Report bug', bugTitle: 'Title', body: 'Description', steps: 'Steps to reproduce', expected: 'Expected behavior', actual: 'Actual behavior', create: 'Create bug ticket', cancel: 'Cancel',
    open: 'Open bugs', needs_triage: 'Needs triage', ready_for_review: 'Ready for review', in_progress: 'In progress', all: 'All', search: 'Search bugs', severity: 'Severity', unknown: 'Unknown', low: 'Low', medium: 'Medium', high: 'High', critical: 'Critical',
    empty: 'No bugs match this view.', previous: 'Previous', next: 'Next', refresh: 'Refresh', triage: 'Triage', ready: 'Ready', needs_information: 'Needs information', duplicate: 'Duplicate', not_a_bug: 'Not a bug', confirmed: 'Confirmed',
    ticket: 'Open ticket', select: 'Select a bug to review its details.', research: 'Research with Codex', config: 'Research settings', repository: 'Repository', revision: 'Revision', enabled: 'Enable research', save: 'Save', notConfigured: 'Configure a repository before requesting research.',
    history: 'Research history', noRuns: 'No research requested.', queued: 'Queued', running: 'Running', completed: 'Completed', failed: 'Failed', cancelled: 'Cancelled', steer: 'Send guidance', guidance: 'Guidance for Codex', retry: 'Research again',
    review: 'Human review', accept: 'Accept findings', reject: 'Request changes', unreviewed: 'Not reviewed', accepted: 'Accepted', rejected: 'Changes requested', result: 'Research findings', observations: 'Observations', hypotheses: 'Hypotheses', evidence: 'Evidence',
    priority: 'Priority', ticketVersion: 'Ticket version', reportedBy: 'Reported by', reportedAt: 'Reported at',
    inspectionOnly: 'Code inspection; runtime reproduction has not been verified.', automatic: 'Refreshes every 5 seconds.', readOnly: 'You have read-only access.', duplicateOf: 'Duplicate of ticket', note: 'Review note', status: 'Ticket status', researchStatus: 'Research status', reviewHint: 'Research completion does not confirm the bug or close its ticket.',
  },
  de: {
    assignee: 'Übernommen von', anyState: 'Jeder Ticketstatus', anyAssignee: 'Alle Übernehmenden', noResearch: 'Nicht recherchiert', title: 'Fehler', loading: 'Lädt…', projectNeeded: 'Ein Projekt auswählen, um seine Fehler zu prüfen.', description: 'Jeder Fehler ist ein Ticket. Recherche startet nur auf Anfrage.',
    reportRequired: 'Titel angeben und das Problem unter Beschreibung oder Tatsächliches Verhalten schildern.', researchInput: 'Recherchegrundlage', originalRequest: 'Ursprüngliche Anfrage', reportSnapshot: 'Fehlermeldung zum Anfragezeitpunkt', report: 'Fehler melden', bugTitle: 'Titel', body: 'Beschreibung', steps: 'Schritte zur Reproduktion', expected: 'Erwartetes Verhalten', actual: 'Tatsächliches Verhalten', create: 'Fehlerticket erstellen', cancel: 'Abbrechen',
    open: 'Offene Fehler', needs_triage: 'Zu sichten', ready_for_review: 'Zur Prüfung', in_progress: 'In Bearbeitung', all: 'Alle', search: 'Fehler suchen', severity: 'Schweregrad', unknown: 'Unbekannt', low: 'Niedrig', medium: 'Mittel', high: 'Hoch', critical: 'Kritisch',
    empty: 'Keine Fehler passen zu dieser Ansicht.', previous: 'Zurück', next: 'Weiter', refresh: 'Aktualisieren', triage: 'Sichtung', ready: 'Bereit', needs_information: 'Informationen fehlen', duplicate: 'Duplikat', not_a_bug: 'Kein Fehler', confirmed: 'Bestätigt',
    ticket: 'Ticket öffnen', select: 'Einen Fehler auswählen, um seine Details zu prüfen.', research: 'Mit Codex recherchieren', config: 'Recherche-Einstellungen', repository: 'Repository', revision: 'Revision', enabled: 'Recherche aktivieren', save: 'Speichern', notConfigured: 'Vor der Recherche ein Repository konfigurieren.',
    history: 'Rechercheverlauf', noRuns: 'Noch keine Recherche angefragt.', queued: 'Wartend', running: 'Läuft', completed: 'Abgeschlossen', failed: 'Fehlgeschlagen', cancelled: 'Abgebrochen', steer: 'Hinweis senden', guidance: 'Hinweise für Codex', retry: 'Erneut recherchieren',
    review: 'Menschliche Prüfung', accept: 'Ergebnisse annehmen', reject: 'Überarbeitung anfordern', unreviewed: 'Ungeprüft', accepted: 'Angenommen', rejected: 'Überarbeitung angefragt', result: 'Rechercheergebnisse', observations: 'Beobachtungen', hypotheses: 'Hypothesen', evidence: 'Belege',
    priority: 'Priorität', ticketVersion: 'Ticketversion', reportedBy: 'Gemeldet von', reportedAt: 'Gemeldet am',
    inspectionOnly: 'Codeprüfung; Reproduktion zur Laufzeit wurde nicht verifiziert.', automatic: 'Aktualisiert alle 5 Sekunden.', readOnly: 'Du hast nur Lesezugriff.', duplicateOf: 'Duplikat von Ticket', note: 'Prüfnotiz', status: 'Ticketstatus', researchStatus: 'Recherchestatus', reviewHint: 'Eine abgeschlossene Recherche bestätigt den Fehler nicht und schließt das Ticket nicht.',
  },
})
