import { defineStrings } from '@/lib/i18n'
export const DOCUMENT_LINKS = defineStrings({
  en: {
    linked: 'Document reference available',
    replacing: 'Linking a new section will dismiss the selected suggestion.', cancel: 'Cancel change', captured: 'Original section title', reviewed: 'Reviewed by',
    backfill: 'Find matches for tickets without references', scheduled: '{n} tickets queued for matching.', more: 'Load more',
    title: 'Document references', accepted: 'Linked sections', suggestions: 'Suggested matches', none: 'No document reference yet.', primary: 'Primary heading', makePrimary: 'Make primary', clearPrimary: 'Clear primary', direct: 'Original source', manual: 'Manually linked', automatic: 'Automatically matched', source: 'Source', related: 'Related', missing: 'Section removed', stale: 'Section changed since linking', version: 'Source version', history: 'Reference history', removed: 'Removed', reason: 'Reason', add: 'Link section', select: 'Choose a document section', accept: 'Accept', change: 'Choose another section', remove: 'Remove reference', dismiss: 'Dismiss suggestion', queued: 'Matching queued', running: 'Finding document matches…', completed: 'Matching complete', failed: 'Matching failed', cancelled: 'Matching cancelled', retry: 'Find matches again', noMatch: 'No matching section found — this may be a documentation gap.', ambiguity: 'Several sections may fit. Review the suggestions.', readOnly: 'Document references are read-only.', loading: 'Loading document references…', error: 'Could not load document references.', refresh: 'Retry', open: 'Open section', policy: 'Document classification', suggest: 'Suggest matches for review', auto: 'Automatically accept unique title matches; suggest other matches', policyHint: 'Choose when matching runs and how its results are reviewed. Existing manual references remain intact.', save: 'Save classification policy', saved: 'Classification policy saved.', without: 'Without a document reference', group: 'Group by document heading', ungrouped: 'No primary document heading', secondary: 'Also linked', tickets: 'Associated tickets', limited: 'Showing {n} of {total} references.', noSections: 'This project has no document sections yet.',
  },
  de: {
    linked: 'Dokumentbezug vorhanden',
    replacing: 'Die neue Verknüpfung verwirft den ausgewählten Vorschlag.', cancel: 'Änderung abbrechen', captured: 'Ursprünglicher Abschnittstitel', reviewed: 'Geprüft von',
    backfill: 'Tickets ohne Dokumentbezug zuordnen', scheduled: '{n} Tickets zur Zuordnung eingereiht.', more: 'Weitere laden',
    title: 'Dokumentbezüge', accepted: 'Verknüpfte Abschnitte', suggestions: 'Vorgeschlagene Zuordnungen', none: 'Noch kein Dokumentbezug.', primary: 'Primärer Abschnitt', makePrimary: 'Als primär markieren', clearPrimary: 'Primärmarkierung entfernen', direct: 'Ursprüngliche Quelle', manual: 'Manuell verknüpft', automatic: 'Automatisch zugeordnet', source: 'Quelle', related: 'Verwandt', missing: 'Abschnitt entfernt', stale: 'Abschnitt seit der Verknüpfung geändert', version: 'Quellversion', history: 'Verknüpfungsverlauf', removed: 'Entfernt', reason: 'Begründung', add: 'Abschnitt verknüpfen', select: 'Dokumentabschnitt auswählen', accept: 'Annehmen', change: 'Anderen Abschnitt wählen', remove: 'Verknüpfung entfernen', dismiss: 'Vorschlag verwerfen', queued: 'Zuordnung wartet', running: 'Passende Dokumentabschnitte werden gesucht…', completed: 'Zuordnung abgeschlossen', failed: 'Zuordnung fehlgeschlagen', cancelled: 'Zuordnung storniert', retry: 'Erneut zuordnen', noMatch: 'Kein passender Abschnitt gefunden — möglicherweise eine Dokumentationslücke.', ambiguity: 'Mehrere Abschnitte könnten passen. Prüfe die Vorschläge.', readOnly: 'Dokumentbezüge sind schreibgeschützt.', loading: 'Dokumentbezüge werden geladen…', error: 'Dokumentbezüge konnten nicht geladen werden.', refresh: 'Erneut versuchen', open: 'Abschnitt öffnen', policy: 'Dokumentzuordnung', suggest: 'Zuordnungen zur Prüfung vorschlagen', auto: 'Eindeutige Titelübereinstimmung übernehmen; andere Treffer vorschlagen', policyHint: 'Lege fest, wann Zuordnungen starten und wie Ergebnisse geprüft werden. Bestehende manuelle Verknüpfungen bleiben erhalten.', save: 'Zuordnungseinstellung speichern', saved: 'Zuordnungseinstellung gespeichert.', without: 'Ohne Dokumentbezug', group: 'Nach Dokumentabschnitt gruppieren', ungrouped: 'Ohne primären Dokumentabschnitt', secondary: 'Außerdem verknüpft', tickets: 'Zugehörige Tickets', limited: '{n} von {total} Verknüpfungen angezeigt.', noSections: 'Dieses Projekt hat noch keine Dokumentabschnitte.',
  },
})
