import { defineStrings } from '@/lib/i18n'

export const STR = defineStrings({
  en: {
    sourceSnapshot: 'Source selection and limits', extractionReady: 'Draft ready. Review the generated sections and source references in Document or Mindmap.', extraction: 'Repository extraction', repository: 'Repository', scope: 'Selected source', started: 'Started at', openMindmap: 'Open mindmap',
    model: 'Model', tokens: 'Token usage', inputTokens: 'Input', cachedTokens: 'Cached input (included)', outputTokens: 'Output', reasoningTokens: 'Reasoning (included)', totalTokens: 'Total',
    noUsage: 'Not recorded. Older workers and runs may not report usage.', usageHint: 'Observed usage for this run. Cached and reasoning tokens are subsets; no monetary cost is inferred. Interrupted runs may be partial.',
    preparing: 'Preparing selected source', drafting: 'Reading code and drafting', publishing: 'Publishing draft for review',
    documentClassification: 'Ticket document matching', openTicket: 'Open ticket',
    documentDiscussion: 'Document discussion', openDocument: 'Open document',
    organizeLanes: 'Organize pending work', openLanes: 'Open lanes', laneSnapshot: 'Work and lane snapshot',
    cancelled: 'Cancelled', openBug: 'Open bug ticket', bugSnapshot: 'Bug report snapshot', title: 'Agent queue', openSection: 'Open section', description: 'Inspect all worker runs, including repository extractions, their status and token usage.',
    refresh: 'Refresh', automatic: 'Automatic updates', loading: 'Loading…',
    all: 'All statuses', queued: 'Queued', running: 'Running', completed: 'Completed', failed: 'Failed',
    empty: 'No requests match this view.', recent: 'Recent requests', status: 'Status', section: 'Section',
    created: 'Queued at', finished: 'Finished at', worker: 'Worker', boundWorker: 'Conversation worker',
    job: 'Request', detail: 'Request details', select: 'Select a request to inspect its details.',
    prompt: 'Prompt', snapshot: 'Section snapshot', response: 'Codex reply', error: 'Error',
    noResponse: 'No reply recorded.', waiting: 'Waiting for a worker to claim this request.',
    boundWaiting: 'Waiting for the conversation worker to claim this request.',
    lease: 'Lease expires', deadline: 'Execution deadline', requestedBy: 'Requested by',
    conversation: 'Conversation ID', thread: 'Codex thread ID', turn: 'Codex turn ID', attempt: 'Attempt ID',
    revision: 'Source revision', map: 'Document ID', node: 'Section ID', history: 'Conversation history',
    member: 'Project member', codex: 'Codex', count: 'Showing', of: 'of', noValue: 'Not recorded',
    unavailable: 'Could not load requests.', detailUnavailable: 'Could not load request details.',
    lastUpdated: 'Last refreshed', stale: 'Refresh failed; displayed data may be out of date.',
    readOnly: 'Inspection only. Requests and documents cannot be changed here.',
    limited: 'Only the latest 100 matching requests are shown. Narrow the project or status to inspect others.',
    timestampHint: 'Times are shown in your local time zone.',
  },
  de: {
    sourceSnapshot: 'Quellbereich und Grenzen', extractionReady: 'Entwurf bereit. Prüfe die erzeugten Abschnitte und Quellen im Dokument oder in der Mindmap.', extraction: 'Repository-Extraktion', repository: 'Repository', scope: 'Ausgewählter Quellbereich', started: 'Gestartet am', openMindmap: 'Mindmap öffnen',
    model: 'Modell', tokens: 'Tokenverbrauch', inputTokens: 'Eingabe', cachedTokens: 'Cache-Eingabe (enthalten)', outputTokens: 'Ausgabe', reasoningTokens: 'Reasoning (enthalten)', totalTokens: 'Gesamt',
    noUsage: 'Nicht gespeichert. Ältere Worker und Läufe melden möglicherweise keinen Verbrauch.', usageHint: 'Beobachteter Verbrauch dieses Laufs. Cache und Reasoning sind Teilmengen; Geldkosten werden nicht abgeleitet. Abgebrochene Läufe können unvollständig sein.',
    preparing: 'Quellbereich wird vorbereitet', drafting: 'Code wird gelesen und Entwurf erstellt', publishing: 'Entwurf wird zur Prüfung veröffentlicht',
    documentClassification: 'Ticket-Dokumentzuordnung', openTicket: 'Ticket öffnen',
    documentDiscussion: 'Dokumentgespräch', openDocument: 'Dokument öffnen',
    organizeLanes: 'Offene Arbeit organisieren', openLanes: 'Lanes öffnen', laneSnapshot: 'Arbeit und Lanes zum Anfragezeitpunkt',
    cancelled: 'Abgebrochen', openBug: 'Fehlerticket öffnen', bugSnapshot: 'Fehlermeldung zum Anfragezeitpunkt', title: 'Agenten-Queue', openSection: 'Abschnitt öffnen', description: 'Alle Worker-Läufe inklusive Repository-Extraktionen, Status und Tokenverbrauch prüfen.',
    refresh: 'Aktualisieren', automatic: 'Automatisch aktualisieren', loading: 'Lädt…',
    all: 'Alle Status', queued: 'Wartend', running: 'Läuft', completed: 'Abgeschlossen', failed: 'Fehlgeschlagen',
    empty: 'Keine Anfragen passen zu dieser Ansicht.', recent: 'Letzte Anfragen', status: 'Status', section: 'Abschnitt',
    created: 'Eingereiht am', finished: 'Beendet am', worker: 'Worker', boundWorker: 'Konversations-Worker',
    job: 'Anfrage', detail: 'Anfragedetails', select: 'Eine Anfrage auswählen, um ihre Details zu prüfen.',
    prompt: 'Prompt', snapshot: 'Abschnitt zum Anfragezeitpunkt', response: 'Codex-Antwort', error: 'Fehler',
    noResponse: 'Keine Antwort gespeichert.', waiting: 'Wartet darauf, dass ein Worker die Anfrage übernimmt.',
    boundWaiting: 'Wartet darauf, dass der Konversations-Worker die Anfrage übernimmt.',
    lease: 'Lease läuft ab', deadline: 'Ausführungsfrist', requestedBy: 'Angefragt von',
    conversation: 'Konversations-ID', thread: 'Codex-Thread-ID', turn: 'Codex-Turn-ID', attempt: 'Versuchs-ID',
    revision: 'Quellrevision', map: 'Dokument-ID', node: 'Abschnitts-ID', history: 'Konversationsverlauf',
    member: 'Projektmitglied', codex: 'Codex', count: 'Angezeigt', of: 'von', noValue: 'Nicht gespeichert',
    unavailable: 'Anfragen konnten nicht geladen werden.', detailUnavailable: 'Anfragedetails konnten nicht geladen werden.',
    lastUpdated: 'Zuletzt aktualisiert', stale: 'Aktualisierung fehlgeschlagen; angezeigte Daten sind möglicherweise veraltet.',
    readOnly: 'Nur zur Einsicht. Anfragen und Dokumente können hier nicht geändert werden.',
    limited: 'Nur die letzten 100 passenden Anfragen werden angezeigt. Projekt oder Status eingrenzen, um andere zu prüfen.',
    timestampHint: 'Zeitangaben in deiner lokalen Zeitzone.',
  },
})
