// DE/EN strings for /inbox, extracted verbatim from src/inbox.html.
//
// 119 keys — too many to hand-transcribe without a silent typo, so they were
// lifted mechanically from the page and checked for key-set and order equality
// before being written here. EN is the reference shape: a DE table that drifts is
// now a compile error rather than an `undefined` rendered to German readers.
import { defineStrings } from '@/lib/i18n'

export const STR = defineStrings({
  en: {
    inbox: "Inbox",
    initiatives: "Initiatives",
    schedules: "Schedules",
    board: "Board",
    settings: "Settings",
    kbd: "j / k move · ↵ answer",
    folders: "Folders",
    open: "Open",
    answered: "Answered",
    withdrawn: "Withdrawn",
    expired: "Expired",
    scope: "Scope",
    mine: "mine",
    tagsHdr: "Tags",
    allTags: "All tags",
    allValues: "All",
    listHintOpen: "urgency · age",
    listHintAns: "most recent",
    crit: "Critical",
    high: "High",
    normal: "Normal",
    low: "Low",
    allClear: "All clear",
    noneForTicket: "No questions for this ticket.",
    allClearSub: "No open questions. The fleet is working.",
    folderEmpty: "Nothing in this folder.",
    back: "All questions",
    nothingSel: "Nothing selected",
    nothingSelSub: "Pick a question from the list.",
    ticketUpdate: "Ticket update",
    typeAnswer: "Type your answer…",
    submit: "Submit",
    askFollow: "Ask a follow-up…",
    to: "to",
    share: "Create answer link",
    withdraw: "Withdraw",
    undo: "Undo",
    decision: "Decision",
    answeredBy: "answered by you",
    stallTag: "ticket stalled",
    stallTitle: "Ticket not resumed",
    stallLead1: "The answer is recorded, but ",
    stallLead2: " did not move: it is still blocked and out of the ready queue, so no agent will pick it up.",
    stallNoExit: "No transition out of the blocked state could be taken automatically — every one needs a claim, a guard, or a scope this token lacks.",
    stallRefused: "The server could not carry the resume. The ticket records the exact reason.",
    stallBarrier: "Another blocking question on this ticket is still open. It resumes once the last one is answered.",
    stallUnknown: "The ticket thread records why.",
    closed: "This question is closed.",
    reopen: "Reopen",
    reopened: "Question reopened.",
    ticketCtx: "Ticket context",
    status: "Status",
    claimed: "claimed by",
    openTicket: "Open ticket →",
    blockedQ: "Blocked — 1 open question",
    blockedSub: "This ticket is parked on the question you are viewing.",
    description: "Description",
    dependencies: "Dependencies",
    links: "Links",
    backToQ: "Back to the question",
    backToList: "Back to list",
    withdrawTitle: "Withdraw this question?",
    withdrawBody: "The question closes and the agent gets no answer. The ticket stays blocked.",
    cancel: "Cancel",
    recommended: "Recommended",
    confVery: "Very strong recommendation",
    confStrong: "Strong recommendation",
    confMod: "Moderate — worth a look",
    confTent: "Tentative",
    approve: "Approve",
    confirm: "Confirm",
    holdApprove: "Reject",
    holdConfirm: "Decline",
    nothingChanges: "Nothing changes.",
    gate: "You can answer this — expert for ",
    resumedInto: " resumed",
    recorded: "Recorded — decision logged",
    blockedEvt: "Blocked — waiting on your answer.",
    waitingAgent: "Waiting on ",
    waitingAgent2: " — you asked for more context.",
    noReply: " was notified. The reply appears here.",
    advisory: "Advisory — no state change",
    readonly: "This token can't answer (no 'human' scope).",
    suggested: "Agent suggested:",
    agentSuggests: "recommends",
    gateTokenSub: "Questions waiting for a human. Paste a token (needs the 'human' scope to answer).",
    gateLabel: "Token",
    gateOpen: "Open inbox",
    selectQuestion: "Select a question to read and answer.",
    answerLinkCreated: "Answer link created (single-use).",
    withdrawn2: "Question withdrawn.",
    cancelled: "Not sent — cancelled.",
    sendFirst: "Select an answer first.",
    typeFirst: "Type an answer first.",
    allProjects: "All projects",
    allTickets: "All tickets",
    taTicket: "Filter by ticket (id or title)",
    taClear: "Clear filter",
    taNoMatch: "No match for “{q}”",
    taMore: "+{n} more — keep typing to narrow",
    taCount: "{n} matches",
    taCount1: "1 match",
    taCountMore: "showing {shown} of {n}",
    taQCount: "{n} questions",
    taQCount1: "1 question",
    followupSent: "Sent to the agent — the reply appears here.",
    advTag: "advisory",
    askedBy: "asked by",
    customDivider: "or your own instruction",
    customPlaceholder: "Write your own instruction …",
    linkTitle: "Answer link created",
    linkBody: "A single-use link that lets someone answer just this one question — no token of their own needed. Share it only with the intended person.",
    linkOnce: "Shown only once — copy it now.",
    copy: "Copy",
    copied: "Copied",
    done: "Done",
    validUntil: "Valid until",
    copyFail: "Copy failed — select it manually.",
    msgMore: "Show full reply",
    msgLess: "Collapse reply",
    morePending: "more pending",
    sendFollow: "Send follow-up",
    followFirst: "Type a follow-up first.",
  },
  de: {
    inbox: "Inbox",
    initiatives: "Initiativen",
    schedules: "Zeitpläne",
    board: "Board",
    settings: "Einstellungen",
    kbd: "j / k bewegen · ↵ antworten",
    folders: "Ordner",
    open: "Offen",
    answered: "Beantwortet",
    withdrawn: "Zurückgezogen",
    expired: "Abgelaufen",
    scope: "Bereich",
    mine: "nur meine",
    tagsHdr: "Tags",
    allTags: "Alle Tags",
    allValues: "Alle",
    listHintOpen: "Dringlichkeit · Alter",
    listHintAns: "neueste",
    crit: "Kritisch",
    high: "Hoch",
    normal: "Normal",
    low: "Niedrig",
    allClear: "Alles erledigt",
    noneForTicket: "Keine Fragen für dieses Ticket.",
    allClearSub: "Keine offenen Fragen. Die Flotte arbeitet.",
    folderEmpty: "Nichts in diesem Ordner.",
    back: "Alle Fragen",
    nothingSel: "Nichts ausgewählt",
    nothingSelSub: "Wähle links eine Frage aus.",
    ticketUpdate: "Ticket-Update",
    typeAnswer: "Antwort eingeben…",
    submit: "Absenden",
    askFollow: "Rückfrage stellen…",
    to: "an",
    share: "Antwort-Link erstellen",
    withdraw: "Zurückziehen",
    undo: "Rückgängig",
    decision: "Entscheidung",
    answeredBy: "beantwortet von dir",
    stallTag: "Ticket steht",
    stallTitle: "Ticket nicht fortgesetzt",
    stallLead1: "Die Antwort ist gespeichert, aber ",
    stallLead2: " hat sich nicht bewegt: Es bleibt blockiert und außerhalb der Warteschlange, also nimmt es kein Agent auf.",
    stallNoExit: "Kein Übergang aus dem blockierten Zustand ließ sich automatisch nehmen — jeder verlangt einen Claim, einen Guard oder ein Recht, das dieses Token nicht hat.",
    stallRefused: "Der Server konnte den Übergang nicht ausführen. Das Ticket nennt den genauen Grund.",
    stallBarrier: "Auf diesem Ticket ist noch eine blockierende Frage offen. Es wird erst fortgesetzt, wenn die letzte beantwortet ist.",
    stallUnknown: "Warum, steht im Ticket-Verlauf.",
    closed: "Diese Frage ist geschlossen.",
    reopen: "Wieder öffnen",
    reopened: "Frage wieder geöffnet.",
    ticketCtx: "Ticket-Kontext",
    status: "Status",
    claimed: "beansprucht von",
    openTicket: "Ticket öffnen →",
    blockedQ: "Blockiert — 1 offene Frage",
    blockedSub: "Dieses Ticket wartet auf die Frage, die du gerade siehst.",
    description: "Beschreibung",
    dependencies: "Abhängigkeiten",
    links: "Links",
    backToQ: "Zurück zur Frage",
    backToList: "Zurück zur Liste",
    withdrawTitle: "Frage zurückziehen?",
    withdrawBody: "Die Frage wird geschlossen und der Agent bekommt keine Antwort. Das Ticket bleibt blockiert.",
    cancel: "Abbrechen",
    recommended: "Empfehlung",
    confVery: "Sehr starke Empfehlung",
    confStrong: "Starke Empfehlung",
    confMod: "Mittel — sehenswert",
    confTent: "Vorläufig",
    approve: "Genehmigen",
    confirm: "Bestätigen",
    holdApprove: "Ablehnen",
    holdConfirm: "Ablehnen",
    nothingChanges: "Nichts ändert sich.",
    gate: "Du kannst antworten — Experte für ",
    resumedInto: " fortgesetzt",
    recorded: "Erfasst — Entscheidung aufgezeichnet",
    blockedEvt: "Blockiert — wartet auf deine Antwort.",
    waitingAgent: "Wartet auf ",
    waitingAgent2: " — du hast um mehr Kontext gebeten.",
    noReply: " wurde benachrichtigt. Die Antwort erscheint hier.",
    advisory: "Beratend — kein Statuswechsel",
    readonly: "Dieses Token kann nicht antworten (keine 'human'-Berechtigung).",
    suggested: "Vorschlag des Agenten:",
    agentSuggests: "empfiehlt",
    gateTokenSub: "Fragen, die auf einen Menschen warten. Token einfügen (Berechtigung 'human' zum Antworten).",
    gateLabel: "Token",
    gateOpen: "Inbox öffnen",
    selectQuestion: "Wähle eine Frage zum Lesen und Beantworten.",
    answerLinkCreated: "Antwort-Link erstellt (einmalig gültig).",
    withdrawn2: "Frage zurückgezogen.",
    cancelled: "Nicht gesendet — abgebrochen.",
    sendFirst: "Zuerst eine Antwort wählen.",
    typeFirst: "Zuerst eine Antwort eingeben.",
    allProjects: "Alle Projekte",
    allTickets: "Alle Tickets",
    taTicket: "Nach Ticket filtern (ID oder Titel)",
    taClear: "Filter löschen",
    taNoMatch: "Kein Treffer für „{q}“",
    taMore: "+{n} weitere — weitertippen zum Eingrenzen",
    taCount: "{n} Treffer",
    taCount1: "1 Treffer",
    taCountMore: "{shown} von {n} angezeigt",
    taQCount: "{n} Fragen",
    taQCount1: "1 Frage",
    followupSent: "An den Agenten gesendet — die Antwort erscheint hier.",
    advTag: "beratend",
    askedBy: "gefragt von",
    customDivider: "oder eigene Anweisung",
    customPlaceholder: "Eigene Anweisung schreiben …",
    linkTitle: "Antwort-Link erstellt",
    linkBody: "Ein einmalig gültiger Link, mit dem genau diese Frage beantwortet werden kann — ohne eigenes Token. Teile ihn nur mit der vorgesehenen Person.",
    linkOnce: "Wird nur einmal angezeigt — jetzt kopieren.",
    copy: "Kopieren",
    copied: "Kopiert",
    done: "Fertig",
    validUntil: "Gültig bis",
    copyFail: "Kopieren fehlgeschlagen — manuell markieren.",
    msgMore: "Ganze Antwort zeigen",
    msgLess: "Antwort einklappen",
    morePending: "weitere ausstehend",
    sendFollow: "Rückfrage senden",
    followFirst: "Zuerst eine Rückfrage eingeben.",
  },
})

export type Strings = (typeof STR)['en']
