// DE/EN strings for the Tests view of the specification workspace.
// EN is the reference shape — a DE table that drifts is a compile error.
import { defineStrings } from '@/lib/i18n'

export const STR = defineStrings({
  en: {
    heading: 'What must work?',
    intro:
      'A behavior describes what the software must do. Link the tests that show it; CI and agents report runs, and the status follows from the latest results.',
    newBehavior: 'New behavior',
    loading: 'Loading …',
    needWrite: "Changing behaviors needs a token with the 'write' scope.",
    noAccess: 'Cannot access tests in {project}',
    loadFailed: 'Could not load data',
    noAccessHint:
      'Choose a project you can access, or use your profile to sign in with an authorized account.',
    retryHint: 'Reload the page to try again.',

    statusVerified: 'Verified',
    statusFailing: 'Failing',
    statusStale: 'Stale',
    statusUntested: 'Untested',
    all: 'All',
    freshness: 'Verified means a linked test passed in the last {days} days.',
    overview: 'Filter by status',

    progress: '{n} of {total} behaviors verified',
    progressLabel: 'Verification progress',
    latestRun: 'Last run {age} ago',
    latestRunBy: 'by {actor}',
    latestRunResult: '{passed} passed, {failed} failed',
    noRun: 'No test run reported yet.',

    search: 'Search behaviors',
    filterSection: 'Filter section',
    allSections: 'All sections',
    noSection: 'No section',
    noSectionGroup: 'Not tied to a section',
    sectionProgress: '{n}/{total} verified',
    toggleSection: 'Show or hide {section}',
    clearFilters: 'Clear filters',
    emptyFiltered: 'No behaviors match these filters.',
    emptySection: 'No behaviors for this section yet.',
    empty:
      'No behaviors yet. Describe what the software must do, link the tests that show it, and let CI or an agent report runs.',
    truncated: 'Showing {shown} of {total}. Narrow the list with search or a status.',

    sumFailing: 'Fails: {test}',
    sumVerified: 'Passed {age} ago',
    sumStale: 'Last passed {age} ago — run it again',
    sumUntested: 'Not checked yet',
    sumNoTests: 'No test linked yet',
    tests: 'tests',
    test: 'test',
    noTests: 'No linked tests',

    shownBy: 'Shown by',
    derivation:
      'The status follows from the newest result of each test: one failure makes the behavior failing, one pass in the last {days} days makes it verified.',
    kindBrowser: 'Browser',
    kindComponent: 'Component',
    kindUnit: 'Unit',
    kindIntegration: 'Integration',
    kindContract: 'API contract',
    kindAgent: 'Agent check',
    kindOther: 'Test',
    neverReported: 'never reported',
    ago: '{age} ago',

    fTitle: 'Title',
    fTitlePh: 'Failed save keeps edits and allows retry',
    fStatement: 'Behavior',
    fStatementPh: 'When saving fails, the edits stay in the editor and retrying saves them.',
    fStatementHint: 'Plain language, or given / when / then. Markdown is supported.',
    fSection: 'Section of the specification',
    fTests: 'Linked tests',
    fTestsPh: 'playwright:editor.spec.ts › keeps edits on save failure',
    fTestsHint: 'One test key per line, exactly as CI or the agent reports it.',
    create: 'Create',
    cancel: 'Cancel',
    edit: 'Edit',
    save: 'Save',
    saved: 'Saved.',
    delete: 'Delete',
    confirmDelete:
      'Delete this behavior? Its links are removed; reported results stay with their runs.',
    titleRequired: 'A behavior needs a title.',

    linkTest: 'Link a test',
    addTest: 'Link',
    addTestPh: 'Test key, as CI reports it',
    removeTest: 'Unlink {test}',
    history: 'History',
    noHistory: 'No results reported for the linked tests yet.',
    technical: 'Technical details',
    copyKey: 'Copy key',
    copied: 'Copied',
    createdBy: 'Created by {actor}',
    pass: 'passed',
    fail: 'failed',

    unlinked: '{n} reported tests belong to no behavior',
    unlinkedHint:
      'These keys were reported in runs but no behavior links them. Link each to the behavior it shows, or add a behavior for it.',
    linkTo: 'Link to …',
    linkToLabel: 'Link {test} to a behavior',
  },
  de: {
    heading: 'Was muss funktionieren?',
    intro:
      'Ein Verhalten beschreibt, was die Software tun muss. Verknüpfe die Tests, die es zeigen; CI und Agenten melden Läufe, und der Status folgt aus den neuesten Ergebnissen.',
    newBehavior: 'Neues Verhalten',
    loading: 'Laden …',
    needWrite: "Zum Ändern von Verhalten braucht das Token den Scope 'write'.",
    noAccess: 'Kein Zugriff auf Tests in {project}',
    loadFailed: 'Daten konnten nicht geladen werden',
    noAccessHint:
      'Wähle ein zugängliches Projekt oder melde dich im Profil mit einem berechtigten Konto an.',
    retryHint: 'Lade die Seite neu, um es erneut zu versuchen.',

    statusVerified: 'Verifiziert',
    statusFailing: 'Fehlschlagend',
    statusStale: 'Veraltet',
    statusUntested: 'Ungetestet',
    all: 'Alle',
    freshness:
      'Verifiziert heißt: Ein verknüpfter Test war in den letzten {days} Tagen erfolgreich.',
    overview: 'Nach Status filtern',

    progress: '{n} von {total} Verhalten verifiziert',
    progressLabel: 'Verifizierungsstand',
    latestRun: 'Letzter Lauf vor {age}',
    latestRunBy: 'von {actor}',
    latestRunResult: '{passed} bestanden, {failed} fehlgeschlagen',
    noRun: 'Noch kein Testlauf gemeldet.',

    search: 'Verhalten suchen',
    filterSection: 'Abschnitt filtern',
    allSections: 'Alle Abschnitte',
    noSection: 'Kein Abschnitt',
    noSectionGroup: 'Keinem Abschnitt zugeordnet',
    sectionProgress: '{n}/{total} verifiziert',
    toggleSection: '{section} ein- oder ausblenden',
    clearFilters: 'Filter löschen',
    emptyFiltered: 'Kein Verhalten passt zu diesen Filtern.',
    emptySection: 'Noch kein Verhalten für diesen Abschnitt.',
    empty:
      'Noch kein Verhalten. Beschreibe, was die Software tun muss, verknüpfe die Tests, die es zeigen, und lass CI oder einen Agenten Läufe melden.',
    truncated: '{shown} von {total} angezeigt. Grenze die Liste mit Suche oder Status ein.',

    sumFailing: 'Schlägt fehl: {test}',
    sumVerified: 'Bestanden vor {age}',
    sumStale: 'Zuletzt bestanden vor {age} — erneut prüfen',
    sumUntested: 'Noch nicht geprüft',
    sumNoTests: 'Noch kein Test verknüpft',
    tests: 'Tests',
    test: 'Test',
    noTests: 'Keine verknüpften Tests',

    shownBy: 'Belegt durch',
    derivation:
      'Der Status folgt aus dem neuesten Ergebnis jedes Tests: Ein Fehlschlag macht das Verhalten fehlschlagend, ein Erfolg in den letzten {days} Tagen macht es verifiziert.',
    kindBrowser: 'Browser',
    kindComponent: 'Komponente',
    kindUnit: 'Unit',
    kindIntegration: 'Integration',
    kindContract: 'API-Vertrag',
    kindAgent: 'Agentenprüfung',
    kindOther: 'Test',
    neverReported: 'noch nie gemeldet',
    ago: 'vor {age}',

    fTitle: 'Titel',
    fTitlePh: 'Fehlgeschlagenes Speichern behält Änderungen und erlaubt Wiederholen',
    fStatement: 'Verhalten',
    fStatementPh:
      'Wenn das Speichern fehlschlägt, bleiben die Änderungen im Editor und ein erneuter Versuch speichert sie.',
    fStatementHint: 'Klare Sprache oder Gegeben / Wenn / Dann. Markdown wird unterstützt.',
    fSection: 'Abschnitt der Spezifikation',
    fTests: 'Verknüpfte Tests',
    fTestsPh: 'playwright:editor.spec.ts › keeps edits on save failure',
    fTestsHint: 'Ein Testschlüssel pro Zeile, genau so, wie CI oder der Agent ihn meldet.',
    create: 'Anlegen',
    cancel: 'Abbrechen',
    edit: 'Bearbeiten',
    save: 'Speichern',
    saved: 'Gespeichert.',
    delete: 'Löschen',
    confirmDelete:
      'Dieses Verhalten löschen? Die Verknüpfungen werden entfernt; gemeldete Ergebnisse bleiben bei ihren Läufen.',
    titleRequired: 'Ein Verhalten braucht einen Titel.',

    linkTest: 'Test verknüpfen',
    addTest: 'Verknüpfen',
    addTestPh: 'Testschlüssel, wie CI ihn meldet',
    removeTest: '{test} lösen',
    history: 'Verlauf',
    noHistory: 'Für die verknüpften Tests wurden noch keine Ergebnisse gemeldet.',
    technical: 'Technische Details',
    copyKey: 'Schlüssel kopieren',
    copied: 'Kopiert',
    createdBy: 'Angelegt von {actor}',
    pass: 'bestanden',
    fail: 'fehlgeschlagen',

    unlinked: '{n} gemeldete Tests gehören zu keinem Verhalten',
    unlinkedHint:
      'Diese Schlüssel wurden in Läufen gemeldet, aber kein Verhalten verknüpft sie. Verknüpfe jeden mit dem Verhalten, das er zeigt, oder lege eines dafür an.',
    linkTo: 'Verknüpfen mit …',
    linkToLabel: '{test} mit einem Verhalten verknüpfen',
  },
})
