// DE/EN strings for the Promises view of the specification workspace.
// EN is the reference shape — a DE table that drifts is a compile error.
//
// Words are chosen from the reader's side: a behavior is a *promise* the
// software makes, a test is *evidence* for it, and a status says whether the
// promise holds ("works"), not what the test runner saw.
import { defineStrings } from '@/lib/i18n'

export const STR = defineStrings({
  en: {
    heading: 'What have we promised?',
    newBehavior: 'New promise',
    loading: 'Loading …',
    needWrite: "Changing promises needs a token with the 'write' scope.",
    noAccess: 'Cannot access promises in {project}',
    loadFailed: 'Could not load data',
    noAccessHint:
      'Choose a project you can access, or use your profile to sign in with an authorized account.',
    retryHint: 'Reload the page to try again.',

    statusVerified: 'Works',
    statusFailing: "Doesn't work",
    statusStale: 'Not checked lately',
    statusUntested: 'Never checked',
    all: 'All',
    freshness: 'A promise works when its evidence passed in the last {days} days and none of it fails.',
    overview: 'Filter by status',

    // The report
    reportLabel: 'What changed',
    periodWeek: 'This week',
    periodMonth: 'This month',
    headline: '{n} of {total} promises work',
    headlineSection: '{n} of {total} promises in this section work',
    deltaUp: '{n} more than {period} ago',
    deltaDown: '{n} fewer than {period} ago',
    deltaSame: 'as many as {period} ago',
    periodAgoWeek: 'a week',
    periodAgoMonth: 'a month',
    trendLabel: 'Working promises per period: {values}',
    movedWorking: 'work now',
    movedRepaired: 'repaired',
    movedBroke: 'stopped working',
    movedStillFailing: '{n} still not working',
    movedStale: '{n} not checked for a while now',
    nothingMoved: 'Nothing changed in this period.',
    wasBroken: 'was broken',
    since: 'since {age}',
    milestone: '{section}: all {n} promises work.',
    milestoneHint: 'Complete in this period.',
    latestRun: 'Last check {age} ago',
    latestRunBy: 'by {actor}',
    noRun: 'Nothing has been checked yet.',
    more: 'and {n} more',

    search: 'Search promises',
    filterSection: 'Filter section',
    allSections: 'All sections',
    noSection: 'No section',
    noSectionGroup: 'Not tied to a section',
    sectionSays: '{n} of {total} work',
    sectionAllWork: 'All {n} work',
    sectionFailing: '{n} not working',
    sectionStale: '{n} not checked lately',
    sectionUntested: '{n} never checked',
    toggleSection: 'Show or hide {section}',
    clearFilters: 'Clear filters',
    emptyFiltered: 'No promises match these filters.',
    emptySection: 'No promises for this section yet.',
    empty:
      'No promises yet. Write down what the software must do, link the evidence that shows it, and let CI, an agent or a person report checks.',
    truncated: 'Showing {shown} of {total}. Narrow the list with search or a status.',

    // The row's right-hand side
    sideSince: 'since {age}',
    sideNew: 'new this week',
    sideNewMonth: 'new this month',
    sideRepaired: 'working again',
    sideChecked: 'checked {age} ago',
    sideLast: 'last {age} ago',
    sideEvidence: '{n} evidence linked',
    sideNoEvidence: 'no evidence yet',
    whatHappened: 'What happened:',
    failedEvidence: '{test} failed.',

    // Opened
    promise: 'The promise',
    shownBy: 'How we know',
    noTests: 'No evidence linked yet. Link a test, or check it yourself.',
    kindBrowser: 'Clicked through in a browser',
    kindComponent: 'Component check',
    kindUnit: 'Code check',
    kindIntegration: 'Integration check',
    kindContract: 'API contract',
    kindAgent: 'Checked by an agent',
    kindManual: 'Checked by hand',
    kindOther: 'Check',
    manualName: 'Checked by a person',
    neverReported: 'never checked',
    ago: '{age} ago',
    pass: 'passed',
    fail: 'failed',
    lifeLabel: 'Track record',
    lifeStrip: 'Last {n} checks, oldest first',
    lifeStreak: 'Passed the last {n} checks in a row.',
    lifeStreakOne: 'Passed the last check.',
    lifeFailing: 'Failing for the last {n} checks.',
    lifeFailingOne: 'The last check failed.',
    lifeLastWorked: 'Last worked {age} ago.',
    lifeNever: 'No check reported yet.',

    fTitle: 'Title',
    fTitlePh: 'Failed save keeps edits and allows retry',
    fStatement: 'Promise',
    fStatementPh: 'When saving fails, the edits stay in the editor and retrying saves them.',
    fStatementHint: 'Plain language, or given / when / then. Markdown is supported.',
    fSection: 'Section of the specification',
    fTests: 'Evidence (test keys)',
    fTestsPh: 'playwright:editor.spec.ts › keeps edits on save failure',
    fTestsHint: 'One test key per line, exactly as CI or the agent reports it.',
    create: 'Create',
    cancel: 'Cancel',
    edit: 'Edit',
    save: 'Save',
    saved: 'Saved.',
    delete: 'Delete',
    confirmDelete:
      'Delete this promise? Its links are removed; reported results stay with their checks.',
    titleRequired: 'A promise needs a title.',

    linkTest: 'Link evidence',
    addTest: 'Link',
    addTestPh: 'Test key, as CI reports it',
    removeTest: 'Unlink {test}',
    checkByHand: 'Checked it myself',
    checkWorks: 'It works',
    checkBroken: "It doesn't work",
    checkNotePh: 'What did you see? (optional)',
    checkNote: 'Checked by hand in Takomo',
    checkSaved: 'Recorded.',
    checkPrompt: 'Try it yourself, then record what you saw.',
    history: 'All checks',
    noHistory: 'No checks reported for this evidence yet.',
    technical: 'Technical details',
    copyKey: 'Copy key',
    copied: 'Copied',
    createdBy: 'Created by {actor}',

    unlinked: '{n} reported tests belong to no promise',
    unlinkedHint:
      'These keys were reported in checks but no promise links them. Link each to the promise it shows, or add a promise for it.',
    linkTo: 'Link to …',
    linkToLabel: 'Link {test} to a promise',
  },
  de: {
    heading: 'Was haben wir zugesagt?',
    newBehavior: 'Neue Zusage',
    loading: 'Laden …',
    needWrite: "Zum Ändern von Zusagen braucht das Token den Scope 'write'.",
    noAccess: 'Kein Zugriff auf Zusagen in {project}',
    loadFailed: 'Daten konnten nicht geladen werden',
    noAccessHint:
      'Wähle ein zugängliches Projekt oder melde dich im Profil mit einem berechtigten Konto an.',
    retryHint: 'Lade die Seite neu, um es erneut zu versuchen.',

    statusVerified: 'Funktioniert',
    statusFailing: 'Funktioniert nicht',
    statusStale: 'Länger nicht geprüft',
    statusUntested: 'Noch nie geprüft',
    all: 'Alle',
    freshness:
      'Eine Zusage funktioniert, wenn ein Beleg in den letzten {days} Tagen bestanden hat und keiner fehlschlägt.',
    overview: 'Nach Status filtern',

    reportLabel: 'Was sich getan hat',
    periodWeek: 'Diese Woche',
    periodMonth: 'Diesen Monat',
    headline: '{n} von {total} Zusagen funktionieren',
    headlineSection: '{n} von {total} Zusagen in diesem Abschnitt funktionieren',
    deltaUp: '{n} mehr als vor {period}',
    deltaDown: '{n} weniger als vor {period}',
    deltaSame: 'so viele wie vor {period}',
    periodAgoWeek: 'einer Woche',
    periodAgoMonth: 'einem Monat',
    trendLabel: 'Funktionierende Zusagen je Zeitraum: {values}',
    movedWorking: 'funktionieren neu',
    movedRepaired: 'wieder repariert',
    movedBroke: 'kaputtgegangen',
    movedStillFailing: '{n} funktionieren weiterhin nicht',
    movedStale: '{n} inzwischen länger nicht geprüft',
    nothingMoved: 'In diesem Zeitraum hat sich nichts verändert.',
    wasBroken: 'war kaputt',
    since: 'seit {age}',
    milestone: '{section}: alle {n} Zusagen funktionieren.',
    milestoneHint: 'In diesem Zeitraum vollständig geworden.',
    latestRun: 'Letzte Prüfung vor {age}',
    latestRunBy: 'von {actor}',
    noRun: 'Noch nichts geprüft.',
    more: 'und {n} weitere',

    search: 'Zusagen suchen',
    filterSection: 'Abschnitt filtern',
    allSections: 'Alle Abschnitte',
    noSection: 'Kein Abschnitt',
    noSectionGroup: 'Keinem Abschnitt zugeordnet',
    sectionSays: '{n} von {total} funktionieren',
    sectionAllWork: 'Alle {n} funktionieren',
    sectionFailing: '{n} funktioniert nicht',
    sectionStale: '{n} länger nicht geprüft',
    sectionUntested: '{n} noch nie geprüft',
    toggleSection: '{section} ein- oder ausblenden',
    clearFilters: 'Filter löschen',
    emptyFiltered: 'Keine Zusage passt zu diesen Filtern.',
    emptySection: 'Noch keine Zusage für diesen Abschnitt.',
    empty:
      'Noch keine Zusagen. Schreib auf, was die Software tun muss, verknüpfe die Belege dafür, und lass CI, einen Agenten oder einen Menschen Prüfungen melden.',
    truncated: '{shown} von {total} angezeigt. Grenze die Liste mit Suche oder Status ein.',

    sideSince: 'seit {age}',
    sideNew: 'neu diese Woche',
    sideNewMonth: 'neu diesen Monat',
    sideRepaired: 'wieder repariert',
    sideChecked: 'geprüft vor {age}',
    sideLast: 'zuletzt vor {age}',
    sideEvidence: '{n} Belege verknüpft',
    sideNoEvidence: 'noch kein Beleg',
    whatHappened: 'Was ist passiert:',
    failedEvidence: '{test} ist fehlgeschlagen.',

    promise: 'Die Zusage',
    shownBy: 'So wissen wir es',
    noTests: 'Noch kein Beleg verknüpft. Verknüpfe einen Test oder prüfe es selbst.',
    kindBrowser: 'Im Browser nachgeklickt',
    kindComponent: 'Komponentenprüfung',
    kindUnit: 'Prüfung im Code',
    kindIntegration: 'Integrationsprüfung',
    kindContract: 'API-Vertrag',
    kindAgent: 'Von einem Agenten geprüft',
    kindManual: 'Von Hand geprüft',
    kindOther: 'Prüfung',
    manualName: 'Von einem Menschen geprüft',
    neverReported: 'noch nie geprüft',
    ago: 'vor {age}',
    pass: 'bestanden',
    fail: 'fehlgeschlagen',
    lifeLabel: 'Verlauf',
    lifeStrip: 'Letzte {n} Prüfungen, älteste zuerst',
    lifeStreak: 'Die letzten {n} Prüfungen in Folge bestanden.',
    lifeStreakOne: 'Die letzte Prüfung bestanden.',
    lifeFailing: 'Die letzten {n} Prüfungen fehlgeschlagen.',
    lifeFailingOne: 'Die letzte Prüfung ist fehlgeschlagen.',
    lifeLastWorked: 'Zuletzt funktionierte es vor {age}.',
    lifeNever: 'Noch keine Prüfung gemeldet.',

    fTitle: 'Titel',
    fTitlePh: 'Fehlgeschlagenes Speichern behält Änderungen und erlaubt Wiederholen',
    fStatement: 'Zusage',
    fStatementPh:
      'Wenn das Speichern fehlschlägt, bleiben die Änderungen im Editor und ein erneuter Versuch speichert sie.',
    fStatementHint: 'Klare Sprache oder Gegeben / Wenn / Dann. Markdown wird unterstützt.',
    fSection: 'Abschnitt der Spezifikation',
    fTests: 'Belege (Testschlüssel)',
    fTestsPh: 'playwright:editor.spec.ts › keeps edits on save failure',
    fTestsHint: 'Ein Testschlüssel pro Zeile, genau so, wie CI oder der Agent ihn meldet.',
    create: 'Anlegen',
    cancel: 'Abbrechen',
    edit: 'Bearbeiten',
    save: 'Speichern',
    saved: 'Gespeichert.',
    delete: 'Löschen',
    confirmDelete:
      'Diese Zusage löschen? Die Verknüpfungen werden entfernt; gemeldete Ergebnisse bleiben bei ihren Prüfungen.',
    titleRequired: 'Eine Zusage braucht einen Titel.',

    linkTest: 'Beleg verknüpfen',
    addTest: 'Verknüpfen',
    addTestPh: 'Testschlüssel, wie CI ihn meldet',
    removeTest: '{test} lösen',
    checkByHand: 'Selbst geprüft',
    checkWorks: 'Funktioniert',
    checkBroken: 'Funktioniert nicht',
    checkNotePh: 'Was hast du gesehen? (optional)',
    checkNote: 'Von Hand in Takomo geprüft',
    checkSaved: 'Gemeldet.',
    checkPrompt: 'Probier es selbst aus und melde dann, was du gesehen hast.',
    history: 'Alle Prüfungen',
    noHistory: 'Für diese Belege wurden noch keine Prüfungen gemeldet.',
    technical: 'Technische Details',
    copyKey: 'Schlüssel kopieren',
    copied: 'Kopiert',
    createdBy: 'Angelegt von {actor}',

    unlinked: '{n} gemeldete Tests gehören zu keiner Zusage',
    unlinkedHint:
      'Diese Schlüssel wurden in Prüfungen gemeldet, aber keine Zusage verknüpft sie. Verknüpfe jeden mit der Zusage, die er belegt, oder lege eine dafür an.',
    linkTo: 'Verknüpfen mit …',
    linkToLabel: '{test} mit einer Zusage verknüpfen',
  },
})
