import { defineStrings } from '@/lib/i18n'
export const ORGANIZER_STR = defineStrings({
  en: {
    savedSpecification: 'Uses saved specification text; unsaved changes are not included.', organize: 'Organize pending work', intro: 'Ask Codex to group pending tickets without an active lane and prepare their context. Review the proposal before applying it.', instructions: 'What should the agent consider?', placeholder: 'Priorities, related areas, constraints or questions to resolve…', request: 'Ask Codex', requesting: 'Requesting…', cancel: 'Cancel', loading: 'Loading organizer…', retry: 'Retry', queueHint: 'A configured agent service must pick up this request.', queueLink: 'Open agent queue', queued: 'Waiting for Codex', running: 'Preparing a proposal', completed: 'Proposal ready', failed: 'Preparation failed', accepted: 'Proposal applied', history: 'Preparation history', conversation: 'Preparation conversation', newLane: 'New lane', existingLane: 'Existing lane', purpose: 'Purpose', context: 'Proposed context', reason: 'Grouping and readiness', tickets: 'Tickets to add', ready: 'Ready for a handoff', needs_clarification: 'Needs clarification', readinessNote: 'Readiness is the agent’s recommendation. Execution still requires a separate handoff and Send.', accept: 'Accept all proposed changes', accepting: 'Applying…', acceptanceNote: 'Accepting creates the proposed lanes, adds tickets and saves context. It does not send work for execution.', acceptedNote: 'Lane changes were applied. Open a lane to review its context and prepare an execution handoff.', unassigned: 'Left unassigned', noChanges: 'No lane changes proposed.', limited: 'Showing the latest {n} of {total} preparation requests.', currentContext: 'Current context in the request snapshot', source: 'Ticket details in the request snapshot', permission: 'Organizing and accepting require human write access.', timestamp: 'Requested', noProposal: 'The agent completed without a usable proposal. Request a new preparation.', failedHint: 'Check the error and submit another request when it is resolved.', defaultMessage: 'Group the pending tickets into coherent new or existing lanes. Prepare useful context and explain readiness and unresolved questions.', show: 'Review proposal', hide: 'Hide proposal',
  },
  de: {
    savedSpecification: 'Verwendet gespeicherten Spezifikationstext; ungespeicherte Änderungen sind nicht enthalten.', organize: 'Offene Arbeit organisieren', intro: 'Bitte Codex, offene Tickets ohne aktive Lane zu gruppieren und ihren Kontext vorzubereiten. Prüfe den Vorschlag vor dem Übernehmen.', instructions: 'Was soll der Agent berücksichtigen?', placeholder: 'Prioritäten, verwandte Bereiche, Einschränkungen oder offene Fragen…', request: 'Codex fragen', requesting: 'Anfrage läuft…', cancel: 'Abbrechen', loading: 'Organisation laden…', retry: 'Erneut versuchen', queueHint: 'Ein konfigurierter Agentendienst muss diese Anfrage abholen.', queueLink: 'Agenten-Queue öffnen', queued: 'Wartet auf Codex', running: 'Vorschlag wird vorbereitet', completed: 'Vorschlag bereit', failed: 'Vorbereitung fehlgeschlagen', accepted: 'Vorschlag übernommen', history: 'Vorbereitungsverlauf', conversation: 'Vorbereitungsgespräch', newLane: 'Neue Lane', existingLane: 'Bestehende Lane', purpose: 'Zweck', context: 'Vorgeschlagener Kontext', reason: 'Gruppierung und Bereitschaft', tickets: 'Hinzuzufügende Tickets', ready: 'Bereit für eine Übergabe', needs_clarification: 'Klärung erforderlich', readinessNote: 'Die Einschätzung stammt vom Agenten. Die Ausführung erfordert weiterhin eine separate Übergabe und Senden.', accept: 'Alle vorgeschlagenen Änderungen übernehmen', accepting: 'Wird übernommen…', acceptanceNote: 'Die Übernahme erstellt vorgeschlagene Lanes, fügt Tickets hinzu und speichert Kontext. Sie startet keine Ausführung.', acceptedNote: 'Die Lane-Änderungen wurden übernommen. Öffne eine Lane, um den Kontext zu prüfen und eine Übergabe vorzubereiten.', unassigned: 'Nicht zugeordnet', noChanges: 'Keine Lane-Änderungen vorgeschlagen.', limited: 'Die letzten {n} von {total} Vorbereitungsanfragen werden angezeigt.', currentContext: 'Bisheriger Kontext im Anfrage-Snapshot', source: 'Ticketdetails im Anfrage-Snapshot', permission: 'Organisation und Übernahme erfordern menschlichen Schreibzugriff.', timestamp: 'Angefragt', noProposal: 'Der Agent hat keinen verwendbaren Vorschlag geliefert. Fordere eine neue Vorbereitung an.', failedHint: 'Prüfe den Fehler und stelle danach eine neue Anfrage.', defaultMessage: 'Gruppiere offene Tickets in zusammengehörige neue oder bestehende Lanes. Bereite hilfreichen Kontext vor und erläutere Bereitschaft und offene Fragen.', show: 'Vorschlag prüfen', hide: 'Vorschlag ausblenden',
  },
})
