import { defineStrings } from '@/lib/i18n'
export const STR = defineStrings({
  en: {
    loadMore: 'Load more', unapplied: 'The lane changed during preparation. Review this result and save the relevant context manually.', title: 'Lanes', loading: 'Loading…', retry: 'Retry', selectProject: 'Select a project to organize its work.', newLane: 'New lane', laneTitle: 'Title', purpose: 'Purpose', context: 'Durable context', create: 'Create lane', save: 'Save', cancel: 'Cancel', empty: 'No lanes yet. Collect related work in a lane, then prepare it with an agent.', back: 'All lanes', tickets: 'Tickets', add: 'Add ticket', remove: 'Remove', search: 'Find a project ticket', noTickets: 'No tickets collected yet.', preparation: 'Preparation', implementation: 'Implementation', review: 'Review', provider: 'Agent', instructions: 'Instructions', draft: 'Draft', queued: 'Queued', running: 'Running', completed: 'Completed', failed: 'Failed', cancelled: 'Cancelled', handoffs: 'Handoffs', newHandoff: 'Prepare a handoff', saveDraft: 'Save draft', send: 'Send to agent', revision: 'Target revision', parent: 'Implementation to review', choose: 'Select…', result: 'Result / findings', reviewAction: 'Request review', fixAction: 'Prepare fixes', readOnly: 'This lane is read-only.', selectTickets: 'Select tickets for this assignment', selected: 'Selected tickets', draftHint: 'Saving a draft records its scope. Sending it explicitly starts agent work.', sendPermission: 'Sending requires a human with write access or an administrator.', noHandoffs: 'No handoffs yet.', history: 'Preparation results and review findings remain here so the next agent can resume the work.', snapshot: 'Assignment context', truncated: 'Showing the first {n} of {total}.', archived: 'Archived', refresh: 'Refresh', preparing: 'Ask an agent to organize and prepare these tickets', noMatch: 'No matching tickets.',
  },
  de: {
    loadMore: 'Mehr laden', unapplied: 'Die Lane wurde während der Vorbereitung geändert. Prüfe das Ergebnis und speichere den relevanten Kontext manuell.', title: 'Lanes', loading: 'Laden…', retry: 'Erneut versuchen', selectProject: 'Wähle ein Projekt, um seine Arbeit zu organisieren.', newLane: 'Neue Lane', laneTitle: 'Titel', purpose: 'Zweck', context: 'Dauerhafter Kontext', create: 'Lane erstellen', save: 'Speichern', cancel: 'Abbrechen', empty: 'Noch keine Lanes. Sammle zusammengehörige Arbeit und bereite sie mit einem Agenten vor.', back: 'Alle Lanes', tickets: 'Tickets', add: 'Ticket hinzufügen', remove: 'Entfernen', search: 'Projektticket suchen', noTickets: 'Noch keine Tickets gesammelt.', preparation: 'Vorbereitung', implementation: 'Umsetzung', review: 'Review', provider: 'Agent', instructions: 'Anweisungen', draft: 'Entwurf', queued: 'In Warteschlange', running: 'Läuft', completed: 'Abgeschlossen', failed: 'Fehlgeschlagen', cancelled: 'Abgebrochen', handoffs: 'Übergaben', newHandoff: 'Übergabe vorbereiten', saveDraft: 'Entwurf speichern', send: 'An Agent senden', revision: 'Zu prüfende Revision', parent: 'Umsetzung für das Review', choose: 'Auswählen…', result: 'Ergebnis / Befunde', reviewAction: 'Review anfordern', fixAction: 'Korrekturen vorbereiten', readOnly: 'Diese Lane ist schreibgeschützt.', selectTickets: 'Tickets für diesen Auftrag auswählen', selected: 'Ausgewählte Tickets', draftHint: 'Ein Entwurf hält den Umfang fest. Erst das Senden startet die Agentenarbeit.', sendPermission: 'Das Senden erfordert einen Menschen mit Schreibzugriff oder einen Administrator.', noHandoffs: 'Noch keine Übergaben.', history: 'Vorbereitungsergebnisse und Review-Befunde bleiben hier, damit der nächste Agent weiterarbeiten kann.', snapshot: 'Auftragskontext', truncated: 'Die ersten {n} von {total} werden angezeigt.', archived: 'Archiviert', refresh: 'Aktualisieren', preparing: 'Bitte einen Agenten, diese Tickets zu ordnen und vorzubereiten', noMatch: 'Keine passenden Tickets.',
  },
})
